website/src/Link.js
Ignore clicks with modifier keys such as `alt`, `cmd`, `ctrl` and `shift`.
Closes #9
=> Don’t handle click with modifier keys.

src/views/CardStackStyleInterpolator.js
The duplicated `index + 1` here looks like a typo to me. I think we still need to use a "0.99-cliff" to quickly set the opacity of the previous scene to 0 for performance reason.
- Run NavigationPlayground on an Android emulator
- Select "Stack Example"
- Select "GO TO A PROFILE SCREEN"
- Use Hierarchy Viewer to find the view of the old scene
- Its `alpha` value should be `0`.
=> Use 0.99-cliff in inputRange of CardStyleInterpolator for Android

docs/api/navigators/StackNavigator.md, docs/guides/Screen-Nav-Options.md, src/TypeDefinition.js, src/navigators/StackNavigator.js, src/routers/StackRouter.js, src/routers/TabRouter.js, src/routers/createConfigGetter.js
For context: this is old #222 pull request that already got `lgtm`, just with the difference that Object.assign is removed. 
Todo: 
- <s>docs</s>
- <s>support in TabBar</s>
- support `style` on header (next PR)
This basically makes it possible to define `navigationOptions` inside `NavigationStackRouterConfig`, so that you don't have to repeat them all over the place.
Proper docs have to land tomorrow that explain how to use it and how to mimic `merge` (explain 2nd parameter to the function because I guess it's nowhere documented)
=> Implement default `navigationOptions`

docs/guides/Redux-Integration.md
Correction for docs, addNavigationHelpers was missing, which if applied copy/paste style would lead to crashes
=> Correct Redux example with addNavigationHelpers

docs/api/navigators/StackNavigator.md, src/TypeDefinition.js, src/views/CardStack.js, src/views/Header.js
Allows setting custom `style` property on a header to change e.g. backgroundColor. Fixes #18. Also fixes `headerComponent` by fixing an old property reference
Go to any example in playground and define `header.backgroundColor`. Reload.
=> Allow custom style

src/withCachedChildNavigation.js
When a component is wrapped with the withCachedChildNavigation, the component name was not always displayed. This fixes that which facilitates debugging.
When using debugger tools such as `react-native-debugger`, attempting to inspect the component tree shows various components as `withCachedChildNavigation(undefined)`. Closed inspection showed that this HOC relies only in `.displayName` of the wrapped component, which is not always set.
This change resolves that issue. Tested locally.
=> withCachedChildNavigation: set proper component name

docs/api/navigators/StackNavigator.md, src/TypeDefinition.js, src/views/CardStack.js
Fixes #14 
Also sorted out some eslint issues
=> Add header.left property

docs/api/navigators/StackNavigator.md
The current code as it was, depended on the "state" param, but the title was being defined as a string template literal.
=> Minor fix in documentation in the "Screen Navigation Options" sample (state undefined)

docs/guides/Guide-Headers.md
First of all, awesome library! 😸 
I was stepping through the guides, and noticed (what I believe to be) an error with one of the code samples. When [setting the header title](https://reactnavigation.org/docs/intro/headers), the current code gives the error `undefined is not an object (evaluating 'navigation.state')`.
To fix, I just changed it to stay inline with the other code examples, taking in `state` from the navigation param passed in and using that (`state.params.user`).
```js
title: ({ state }) => `Chat with ${state.params.user}`
```
It could also be done by taking in the navigation object, instead of using destructuring
```js
title: (navigation) => `Chat with ${navigation.state.params.user}`
```
=> Fix 'setting the header title' example in the guides

scripts/compile-docs.js
1. _Added nodes.js cross platform path separator in scripts/compile-docs.js_
2. _cross platform path separator_
3. _npm i_
4. _Only tested on Windows, but should work on Mac/Unix too._
=> Added nodes.js cross platform path separator in scripts/compile-docs.js

docs/guides/Screen-Navigation-Prop.md
Fixes a small typo in the docs: `it's` -> `its`
=> Fix typo in screen navigation prop

docs/api/navigators/TabNavigator.md, docs/api/routers/TabRouter.md, examples/NavigationPlayground/js/CustomTabs.js
This fixes https://github.com/react-community/react-navigation/issues/119 which is just a documentation issue. The documentation says that the property "initialTab" should be used for displaying an initial route in a TabRouter. The correct name for this property is "initialRouteName". Furthermore the correct value for the "backBehavior" property is "initialRoute" according to the source code of [TabRouter](https://github.com/react-community/react-navigation/blob/master/src/routers/TabRouter.js)
=> fixed initialRouteName documentation

src/TypeDefinition.js, src/views/TabView/TabBarBottom.js, src/views/TabView/TabBarTop.js, src/views/TabView/TabView.js
>Explain the **motivation** for making this change. What existing problem does the pull request solve?
The tabBar navigationOptions only allow a label to be a string. When an app requires more complex layout, the label needs to match, for example having multiline text. This change solves that by allowing a component to be passed through as the `label` component.
```
function A() {
return <Text>Page</Text>;
}
function WithComponent() {
return <Text>Page</Text>;
}
WithComponent.navigationOptions = {
tabBar: {
label: (
<View>
<Text>SAT</Text>
<Text>28</Text>
</View>
)
},
}
const Test = TabNavigator({
A: { screen: WithComponent },
B: { screen: A },
C: { screen: A },
D: { screen: A },
}, {
tabBarOptions: {
scrollEnabled: true,
tabStyle: {
width: 50,
height: 50,
padding: 0,
}
},
})
```
Output …
=> Support label as component in TabNavigator

docs/api/navigators/DrawerNavigator.md, docs/api/navigators/StackNavigator.md, docs/api/navigators/TabNavigator.md
Added `screenProps` example and fixed various wordings issues, if everything looks good I will start updating other `navigator` docs so they are in alignment.
=> Add `screenProps` example and fix various wordings

src/views/HeaderBackButton.js
Tinting was just added in #109. In a related issue [it was decided][1] that that the `tintColor` option should control back button tinting as well.
However `<Image>` takes `tintColor` [as a style][0] and not as a prop, so currently the option has no effect on the button’s colour.
Please let me know if any changes are required. Thanks!
[0]: https://facebook.github.io/react-native/releases/0.41/docs/image.html#style
[1]: https://github.com/react-community/react-navigation/issues/36#issuecomment-276294877
=> Fix back button tinting

docs/api/navigators/StackNavigator.md, src/TypeDefinition.js, src/navigators/StackNavigator.js
Currently it is not possible to set the style for an individual card in the CardStack when using the default StackNavigator. My proposal is to add `cardStyle` option to `stackConfig`.
=> Add support for cardStyle prop

examples/HelloHybrid/HybridContainer.js
So in HelloHybrid for ios there is a typo in `router` that cause **of undefined** exception
=> Fixed typo in HelloHybrid for ios

docs/api/navigators/Navigators.md, examples/ReduxExample/index.js
giving more info for typical use case when you want to invoke navigation from top-level component. 
More info and request to add documentation can be found [here](https://github.com/react-community/react-navigation/issues/71)
=> Docs: add info about calling nav from same level component

docs/api/navigators/TabNavigator.md, src/views/TabView/TabBarBottom.js
This allows styling of the label component for `TabBarBottom` (analog to how it is already possible for  `TabBarTop`)
=> Implement `labelStyle` for `TabBarBottom`

docs/guides/Screen-Navigation-Prop.md
Doc was unclear what `NavigationActions` returned, before it looked like you can dispatch a navigation action simply by calling `NavigationActions.navigation({routeName: 'here'})`.
Looking at `NavigationActions.reset` it looks like the actual `dispatch` line was just missing in `NavigationActions.navigation` and `NavigationActions.setParams` examples.
#157 -> reset action doc was fixed but missed the other actions
=> Clarify Navigation Prop dispatch method

docs/api/navigators/StackNavigator.md, src/TypeDefinition.js, src/views/Header.js
Changing the style of the individual title component required rolling your own title component for every screen.  This way developers can quickly add a single overriding style to their app, without having to define a new component for each case (ie still use the "string" version of the title option).
100% of current tests passing/flow results the same (122 errors).  No change to current examples.
=> Add titleStyle header option

src/views/Header.js, src/views/HeaderBackButton.js, src/views/HeaderTitle.js
This pull request implements a better back button title for a back button on iOS. 
It changes the way components are rendered. Instead of rendering all left, title and right components separately with position `absolute`, it renders them within another View. That makes it possible to use layout, flex, and built-in truncating when width of the container is reached.
In order to achieve that, we listen to `onLayout` to get the real width.
**Todo**
Test on Android. Should have no changes. Will do later today, for now, waiting for review.
**Test plan**
Run on iOS, go to any view, push a screen, observe the header:
or go back and see smaller title:
=> Better back button label

docs/api/navigators/TabNavigator.md
This example doesn't compile locally for a few reasons:
1. I don't have the same file structure, so I don't have the images being used in my AwesomeProject (tutorial example used everywhere)
2. The Buttons are expecting a string-typed title prop
The second one seems like a bug to me, so I'm proposing we fix it. The first one seems like it's part of the context of the example, so it makes sense to leave it.
testinprod
=> Replace usage of label with title prop for Buttons

src/createNavigationContainer.js
When your favorite navigation container is used with changing `screenProps`, each render results in the creation of a new `navigation` instance. Example:
```js
const MyNav = StackNavigator({...});
function App({changingProp}) {
return <MyNav screenProps={{changingProp}} />;
}
```
Now, when you're having routes that don't really use those `screenProps` but do pass on `navigation` to otherwise pure components, those components get unnecessarily re-rendered.
This fix caches the last-built `navigation` property on the container HOC, and only updates it when the actual state changes -- similarly to how `withCachedChildNavigation` works.
=> createNavigationContainer: cache previously used navigation

src/withCachedChildNavigation.js
Fixes #159. Any ideas on testing this welcome.
Also, I'm unsure if routes can change. If that is the case, we could add logic to clean out the cache of no-longer-used routes.
=> withCachedChildNavigation basically did not cache

docs/guides/Deep-Linking.md
This matches the rest of the definitions of the URI schema later on in the documentation and examples.
=> Fix typo in deep linking schema

docs/guides/Screen-Nav-Options.md, src/views/TabView/TabView.js
This implements the ability to hide the tabBar by setting visible = false
It can be turned on in the navigationOptions
```
static navigationOptions = {
tabBar: ({ state }) => ({
label: 'Messaging',
visible: false,
}),
};
```
or accessed through SetParams (when #132 or similar functionality is implemented). See #136 for discussion.
=> Add visible param to TabBar

src/views/Transitioner.js
In order to set dynamic header buttons/titles, we need often need to do something like:
```javascript
componentDidMount () {
const isDisabled = <someLogicUsingLocalState>;
const params = {
right: (
<Button
onPress={() =>!isDisabled ? this.onSave() : null}
>
<Text style={[styles.rightButtonTextStyle, isDisabled ? styles.disabledStyle : null]}>
Save
</Text>
</Button>
),
};
this.props.navigation.setParams(params);
}
// And our navigation options:
function getCurrentParams (state) {
if (state.routes) {
return getCurrentParams(state.routes[state.index]);
}
return state.params || {};
}
// ...some setup...
// main stack navigator navigationOptions
navigationOptions: {
header: ({state}) => {
// get the "deepest" current params.
const currentParams = getCurrentParams(state);
const left = …
```
=> Don't allow transitioner to run two transitions at once (Fixes #160)

src/routers/TabRouter.js, src/routers/__tests__/TabRouter-test.js
Following on from #126 setParams in TabNavigator was not working. I believe this is because it is not handled in the getStateForAction function in TabRouter.js
The following code works with my changes
```js
import React from 'react';
import {
AppRegistry,
Text,
View,
Button,
StyleSheet
} from 'react-native';
import { TabNavigator, TabView } from 'react-navigation';
import Ionicons from 'react-native-vector-icons/Ionicons';
import IconBadge from './IconBadge'
class Home extends React.Component {
static navigationOptions = {
tabBar: ({ state }) => ({
label: 'Home',
icon: ({ tintColor, focused }) =>
<IconBadge
MainElement={
<Ionicons
name={focused ? 'ios-home' : 'ios-home-outline'}
size={26}
style={{ color: tintColor }}
/>
}
badgeNumber={typeof state.params === 'undefined' ? 0 : …
```
=> Add SetParams handling in TabRouter.js

docs/api/navigators/StackNavigator.md, src/TypeDefinition.js, src/navigators/StackNavigator.js, src/views/CardStack.js
Currently onTransitionStart/End props are not exposed by CardStack or StackNavigator. This pull request adds them as props to CardStack and as options to StackNavigator.
=> Expose onTransitionStart/End props to StackNavigator

docs/api/navigators/TabNavigator.md, src/views/TabView/TabBarBottom.js
This PR adds the `showLabel` option to tabBarBottom for projects like mine that only want icons visible in the bottom tab bar.
It should be safe, since it is an exact copy/paste from `tabBarTop`. See https://github.com/react-community/react-navigation/blob/master/src/views/TabView/TabBarTop.js#L66
- All tests passed, though I don't know if any tests have been written to cover `TabBarBottom`
=> enable `showLabel` prop in `tabBarBottom`

src/views/Header.js, src/views/HeaderBackButton.js
There are few features/fixes included in this PR:
- Disable back button label as it's not read yet - it renders perfectly fine, but we haven't landed truncating yet, which is crucial for the production apps. I left it in master to iterate faster, but as @satya164 is planning to do the release, I have temporarily turned it off. I am also working on mimicking natural iOS animations as much as possible, hopefully this lands later this week.
- Fix layout issues on iOS. My changes introduced last week that were making an icon looking just like on a native app changed the size of container - the touchable area was no longer 44x44 as recommended by Apple, but 12x20 (size of an icon) + left margin of 10 points. This pull request fixes that by adjusting sizes.
- Add additional style for `icon with …
=> Fixes several back button issues

docs/api/navigators/DrawerNavigator.md, docs/api/navigators/StackNavigator.md, docs/api/navigators/TabNavigator.md, src/views/SceneView.js
This changes the behaviour of screenProps so that the props no longer get splatted.
Components will receive this as `this.props.screenProps`.
=> Pass through screenProps to nested navigators

docs/api/navigators/StackNavigator.md
When going through the example code on this page, I got an error and noticed that the docs used **label** instead of **title**. This pull is to fix this in the example code so it actually runs.
=> React Native Buttons use title, not label.

docs/guides/Contributors.md
Hello, there is an uncompleted sentence in the Contributors guide.
@skevy wrote that line, if you remember what you wanted to write, ill add it :) 
Otherwise, I just removed the floating words.
=> Remove uncompleted sentence in Contributors guide.

src/views/Header.js
Fixes #189
When we introduced style for header, it got included with `NavigationSceneRendererProps` causing some glitches for title/left/right components.
It is wise to remove it as we do not use it at all anywhere and each of the components (left/right/title) have its own custom style (e.g. `titleStyle`)
Test plan:
Set #189 repro and compare fixed header with the one posted in the issue.
=> Fix style prop for header

src/views/withNavigation.js
Fixes: Named import from module `../TypeDefinition` `ContextWithNavigation` is a type, but not a value. In order to import it, please use `import type`.
**Flow complains that we aren't using the import type syntax.**
**Flow requires import type syntax up until the current version (at least).**
Flowtype change - not tested as far as I can see.
=> [FLOW] Fix missing "type" in flow import.

src/views/TabView/TabBarBottom.js
See sample and use case [here](https://cl.ly/2h0O1M3o0i0k).
=> Add `showIcon` to `tabBarOptions` so that icons can be hidden on iOS

src/views/TabView/TabView.js
As the title says, in case we specify a custom TabBarComponent for a TabNavigator, `navigation` becomes available.
It is especially necessary if we have a TabNavigator nested in another navigator: a custom NavBar with a button to navigate outside of the tabs needs to `navigation.navigate(...)`
=> pass navigation prop to TabBarComponent

docs/api/navigators/StackNavigator.md, src/TypeDefinition.js, src/views/CardStack.js
Context for the problem I was facing #383. A related `gesturesEnabled` PR with some additional context in #292.
In StackNavigator, sometimes it's useful to prevent somebody from dismissing a route. My use case is a log-in screen that I display as a modal above the rest of my app.
Test plan: I hooked this into my own app, and verified that I was able to set gesturesEnabled via navigation options. flow/jest pass
=> Make it possible for a screen to set gesturesEnabled

src/views/Header.js
Fixes invalid style warning: #421
**Test plan**
Before Change: Open NavigationPlayground on iOS, open stack example, see warning.
After Change: No warning. Also verify no change on Android for stack example.
=> Fix null style warning in Header component

docs/guides/Redux-Integration.md
When the drawer opens / close, the result of AppNavigator.router.getStateForAction(action, state); is null. So the nav state in the store is null which causes errors. This solves that.
=> Updated the reducer

docs/api/navigators/Navigators.md, docs/guides/Custom-Navigators.md
Resolves https://github.com/react-community/react-navigation/issues/403
Moves the Navigation Containers and containerOptions sections out of this doc:
https://reactnavigation.org/docs/navigators/custom
And into this one: https://reactnavigation.org/docs/navigators/.
=> Move Navigation Containers and containerOptions into Navigators API docs

src/views/CardStack.js
This fixes #414 
The issue is that with with `headerMode: 'screen'`, header shadows are covered by the `Card`, esp. when you set a background color on a Card. Also, as described in #414, when you set position to be absolute, in order to render e.g. semi-transparent header above the scene, this is not possible.
By being defined as the last element, we can now make interactions that in #414 were not possible before. No major changes were done, just applied the same style we do for `headerMode: float`. Thanks to that, they should be easier to maintain as they are now rendered exactly the same.
=> Fix headerMode: `screen` position

src/views/Header.js
Fixes #432 
For some reason, `onLayoutIOS` was missing Platform check.
=> Fix left button in header on Android

src/views/CardStack.js
Hello,
This PR adds a nested View around the content in CardStack so that the content expands and puts the header bar at the top of the screen on Android.
This issue seems like it was introduced in PR #436. My understanding is that the header bar is put after the screen content to change the rendering order and the `column-reverse` flex direction is used to make sure actual placement wouldn't change.
This problem only occurs when SceneView (in CardStack.js) is tightly wrapping whatever it contains. For example:
```
render() {
return <Text>Hello, sailer</Text>;
}
```
will cause an issue whereas `TabNavigator` won't, for whatever reason.
Anyways it looks like this:
This issue is described in #432 and it was discovered that if the content is wrapped in an expanding View (with `style={{flex: …
=> Fix low header bar on Android

docs/guides/Redux-Integration.md
I think the navigation key for the redux store should be `nav` and not `navReducer`.
=> Fix redux documentation

docs/api/navigators/Navigators.md, docs/guides/Screen-Tracking.md, src/createNavigationContainer.js
Sometimes it is useful to know when `navigation` did change, so that we can use e.g. Google Analytics to track page change.
This improves over past example that was hacking `componentDidUpdate` prototype.
Test plan:
add `onNavigationStateChange` prop and console log args. Should be called every dispatch with prev/next state.
=> Add onNavigationStateChange

src/views/Header.js, src/views/Transitioner.js
When having a StackNavigator with a route `A` and active index 0, calling `reset` action with a route `B` (leaving the same index) produces a series of glitches that this PR fixes.
Real use-case is when e.g. having a `Login` route and after clicking `Login` button, you want to replace it.
In order to fix those issues, I decided to change the following:
1) Transitioner shouldn't perform any animations when we do `reset` on the same index. Animations that rely on `index` will produce inaccurate effects as the index never changes, but the route does. What I experienced was e.g. after replacing a route, the title of a previous route stayed on screen for the duration of the animation, because `progress` was animating, but `position` wasn't. I cannot think of a use-case where it would be …
=> Fix glitches in Header when calling `replace` 

src/views/Drawer/DrawerNavigatorItems.js, src/views/Drawer/DrawerSidebar.js
The PR adds `getScreenConfig` property to the Drawer`s content component. 
If one needs to implement custom drawer menu (in place of `DrawerNavigatorItems`), he may want to also customize navigation options. The PR makes it possible.
*It is a PR-in-discussion, which may be altered or declined* (the related issue is here #478)
=> Add getScreenConfig prop for DrawerNavigator contentComponent

src/views/TabView/TabBarBottom.js
Instead of `flexGrow`, `TabBarBottom` should use `flex` in order to match iOS HIG for UITabBar. Otherwise, if labels with different length are set, the layout of the tab bar isn't consistent with what iOS users expect (tab highlighted with red border):
After the change, this is how the tab bar looks:
Tests pass and both Android and iOS `NavigationPlayground` example looks OK.
=> Solves TabBarBottom item layout to match iOS UITabBar HIG

website/src/App.css, website/src/MDPage.js
[docs] Fixes #434 
How it looks:
With `:hover`
URL:
Tested on Safari.
=> [Docs] Link every heading automatically

src/views/TabView/TabBarBottom.js, src/views/TabView/TabBarTop.js
It could be useful to dynamically change (`focused`) tabBar label default styles for certain tab(s).
This pull request is aim to discuss how to implement it properly. 
Usage example: 
```js
navigationOptions: {
tabBar: {
icon: ({ focused }) => <TabItem focused={focused} name="whatshot" activeColor="red" />,
label: ({ focused, tintColor, defaultStyles }) => {
return (<Text style={[defaultStyles, { color: focused ? 'red' : defaultStyles.color }]}>Profile</Text>);
},
}
},
```
Current implementation provided but without `Animated.Text` color specification
=> Accept tabBar label to be a function

docs/guides/Redux-Integration.md, src/views/Header.js, src/views/HeaderBackButton.js
This pull request fixes all issues regarding Header that were already filled in by:
1) Reverting previous `absolute` layout - turns `flex` looks nice and was easier to implement, but caused too many issues and it was impossible to keep it going forward
2) `onLayout` is async and it causes flickering as reported in issues - this PR makes sure absence of `onLayout` causes no issues. It does so by not touching layout at all. As soon as width of title is known, we only manipulate back button. No other parts are touched. Right and title stay as they used to be.
3) on iOS, title offset is `70`, whereas on `Android` 40 (as it used to be). This is because on iOS, by default we want to render `< Back` when title is too long. This is to make sure we end up with a well truncated title. Having `40` …
=> Change <Header /> layout back to `absolute`

src/views/SceneView.js
This warning has been around for a bit:
It appears the docs have been updated for a while now.
@satya164 - straight forward removal.
=> screen props warning removed

docs/api/navigators/TabNavigator.md, docs/api/routers/StackRouter.md
Just making the formatting consistent between examples in the docs
=> Make TabNavigator code example formatting consistent

src/routers/StackRouter.js, src/routers/__tests__/StackRouter-test.js
Currently initialRouteParams option has no effect when using StackRouter.
=> Fix issue where initialRouteParams were not set

src/views/CardStack.js
We often, like all the time, configure the transition based on the `TransitionProps` so those params should pass to `transitionConfig` props,  just like the default `TransitionConfig`
=> Pass `transitionProps`, `prevTransitionProps` and `isModal` to custom `TransitionConfig`

docs/api/routers/RoutersAPI.md
Typo in docs: the right function name is `getComponentForRouteName`.
=> Fix typo in docs for getComponentForRouteName

docs/api/routers/Routers.md, docs/api/routers/RoutersAPI.md
Hi,
Some typos on docs (So I think).
The less obvious is on https://reactnavigation.org/docs/routers/ : 
The sample says that we can override methodes. But I think it is not true, at least on StackNavigator.
On StackNavigator, the router is a constant (https://github.com/react-community/react-navigation/blob/master/src/navigators/StackNavigator.js).
What worked for me is to use 
Object.assign(MyApp.router, { ...}) 
to keep the same instance but change properties.
Also, to override, we need keep a ref on previous methid because we can't call MyApp.router.getStateForAction(action, state) : I think it will result in an infinite loop.
=> correction of a few documentation typo

docs/guides/Contributors.md
This improves the contributors guide by discussing the contribution workflow. Can't PR by just cloning main repo so I describe forking it and keeping in sync with upstream
=> Adds documentation about forking and syncing repo

docs/api/navigators/DrawerNavigator.md
Adds some missing documentation about how to customise the `contentComponent` prop of the `DrawerNavigator` component, as well as clarifying what the `contentComponent` actually is.
Followup to #177
=> Update documentation regarding `DrawerNavigator` customisation

docs/api/navigators/DrawerNavigator.md, docs/api/navigators/TabNavigator.md
Two links in the documentation pointed to `coodoo/react-navigation` `react-community/react-navigation.
=> Docs: Update md links from coodoo's fork to react-community

src/views/Header.js
`ReactComponentWithPureRenderMixin` is useless in this file, and it has been removed from the core of latest `react`
build fails on master branch of `react-native` for this error @ericvicenti
=> remove ReactComponentWithPureRenderMixin

src/views/TabView/TabView.js
Accordin do the react-native-tab-view, `TabViewAnimated` is a pure component, and as such, will not be rerendered unless it's props change.
This prevents rerenders when `screenProps` on `TabNavigator` change, and as such, is a major limitation when using `TabNavigator`.
The proposed solution is to pass the `screenProps` to the `TabViewAnimated`, even if does not use this in any way.
Any change to the `screenProps` of `TabNavigator` will trigger a rerender in `TabViewAnimated`.
Allows using `screenProps` with `TabNavigator`
Prefer **small pull requests**. These are much easier to review and more likely to get …
=> Fix TabViewAnimated screenProps caveat

src/views/CardStack.js
`gesturesEnabled` property stopped working on master. This fixes this regression.
Closes #818
Regression caused by https://github.com/react-community/react-navigation/commit/11cab8eab62b6ca1c2a0445f30a9d0dc75458e2e
=> Fix gesturesEnabled regression

src/TypeDefinition.js, src/routers/StackRouter.js, src/routers/__tests__/StackRouter-test.js
**Motivation** 
There is no way to build a Login/Register flow without the ability to reset the router to the top-level nav state without hacky workarounds.
#691 #723 
By allowing a key to be passed along with a reset action, you can specify what level of state you want to reset to.
I added a test case that verifies the functionality.
I'm happy to add more test cases or documentation, if you find this PR useful.
=> Reset specific StackRouter with key

docs/guides/Guide-Intro.md
The text used `name` as param but the examples used `user` instead.
=> Fix wrong param name in the guides

docs/guides/Deep-Linking.md
To be on par with the android way of opening the URI.
=> add command to open URI in the iOS simulator

examples/README.md, examples/ReduxExample/yarn.lock, rn-cli.config.js
I'm happy to make more tweaks if needed, but this works for me now on both Android and iOS.
1. For some reason `yarn.lock` had resolved to a package registry that is unable to serve HTTPS; this doesn't work at all on the latest version of Yarn
2. Add the directory name to the `examples` array in `rn-cli.config.js` to fix `@providesModule naming collision` errors (likely fixes https://github.com/react-community/react-navigation/issues/75)
=> Fix the ReduxExample app

src/routers/StackRouter.js, src/routers/__tests__/StackRouter-test.js
This PR adds query string parsing capabilities. The items of the query string will be added to the `params` object of a navigation action. When there are same-named params in the query and the path, the params from the path will override the ones from the query.
**Motivation**
In my app I needed this capability, because I have a deep link `/redeem_key?key=<key>&name=<name>`. As with query params in the web, the ordering shouldn't be significant.
I added a test case that verifies the functionality. There are no UI changes and it shouldn't affect any platform-specific code.
I'm happy to add more test cases or documentation, if you find this PR useful.
=> Query string parsing capabilities for deep linking

src/routers/StackRouter.js, src/routers/__tests__/StackRouter-test.js
**motivation** 
setParams with nested routers doesn't work well with https://github.com/react-community/react-navigation/pull/789 so this PR fixes it.
Add tests
=> Fix setParams with nested routers

examples/NavigationPlayground/js/App.js, examples/NavigationPlayground/js/StacksInTabs.js, examples/NavigationPlayground/js/StacksOverTabs.js
`StacksOverTabs` is exactly the same as `StacksInTabs`, except that when navigating, the routes get pushed on top of the tabs instead of inside of them. This is a common paradigm.
Also fixes `StacksInTabs` so it navigates to `SettingsTab` instead of pushing a new `Settings` screen to the stack.
=> [Playgrond] Add StacksOverTabs example

examples/NavigationPlayground/js/App.js, examples/NavigationPlayground/js/TabsInDrawer.js
This example puts `SimpleTabs` and `StacksOverTabs` into a drawer layout with custom labels and icons. Shows how simple it is to nest the two like this :)
This is how my app works, and I needed to write this example anyway in order to test some integration logic with redux.
(should be merged after https://github.com/react-community/react-navigation/pull/928 since they're dependent)
=> [Playground] Add TabsInDrawer example

examples/ReduxExample/index.js, examples/ReduxExample/src/components/AuthButton.js, examples/ReduxExample/src/components/LoginScreen.js, examples/ReduxExample/src/components/LoginStatusMessage.js, examples/ReduxExample/src/components/MainScreen.js, examples/ReduxExample/src/components/ProfileScreen.js, examples/ReduxExample/src/navigators/AppNavigator.js, examples/ReduxExample/src/reducers/index.js
While learning how to use react-navigation with Redux, I attempted to follow the Redux Example. It was however too condensed and the declarations inlined to the point of being illegible.
The goal of this PR is to refactor the redux example into multiple folders/files, and trying to adhere to redux app conventions more for the sake of clarity.
=> refactored Redux Example

src/views/HeaderTitle.js
Without this trait, VoiceOver on IOS does not identify the title as a heading, which it is.
Test plan:
1. Launch an app with a title.
2. Turn on VoiceOver.
3. Observe that with this change, VO identifies the title as a heading.
4. Observe that with this change, VO identifies the title as a heading.
5. Launch almost any Apple app, including Find My Friends, Music, or even the Phone app, and notice that screen titles are also identified as headings in these apps.
=> Added the Header accessibility trait to the header title

docs/api/navigators/StackNavigator.md, src/views/Header.js, src/views/HeaderBackButton.js, src/views/TouchableItem.js
This resolves https://github.com/react-community/react-navigation/issues/925, adding the option to change the back button's ripple colour. For example:
All tests and flow checks are passing. Test plan:
- Don't set `pressColor` in `navigationOptions.header` on a `StackNavigator`. Everything is the same as before.
- Set `pressColor` to anything you want as above. Ripple colour has changed.
Do let me know if there's anything you'd prefer to be done differently :slightly_smiling_face:
=> Add pressColor to StackNavigator header options

examples/ReduxExample/index.js, examples/ReduxExample/package.json, examples/ReduxExample/src/components/LoginScreen.js, examples/ReduxExample/src/components/MainScreen.js, examples/ReduxExample/src/components/ProfileScreen.js, examples/ReduxExample/src/reducers/index.js, examples/ReduxExample/yarn.lock
The [awesome refactor](https://github.com/react-community/react-navigation/pull/819) that was done recently (thanks so much for that!) had a few import/export bugs preventing it from running that are fixed here.
I also disabled persistence to AsyncStorage; though it's a cool feature, it isn't necessary to demonstrate how to use react-navigation and may cause more confusion than it's worth. For example, if you change the name of a route and then refresh the app, everything will break because it can't find the old route that had been persisted, even though your code is perfectly fine.
cc @samijaber @ericvicenti
=> Fix the ReduxExample app (2)

src/routers/TabRouter.js, src/routers/__tests__/TabRouter-test.js
- Closes: #80 
- Closes: #134 
(for more info see [this comment](https://github.com/react-community/react-navigation/issues/80#issuecomment-292352817) I left in the issue)
=> Add support for passing params on navigate to tabs

docs/api/routers/StackRouter.md
Fixes a small typo in the `initialRouteName` property in StackRouter
=> Fix typo in StackRouter.md

src/views/CardStackTransitioner.js
Nit: we pass `style` instead of `cardStyle`.
Fixes #1026
=> Fix cardStack style

docs/api/navigators/StackNavigator.md, src/views/Header.js
After reviewing #1017, I've discovered other changes that have to be applied. I also decided to bring back documentation.
Changes:
- `headerLeft` on scene with index `0` works. Fixes #1015 
- `backButtonTitle` is taken from a proper scene
- `headerLeft` different than `undefined` will take prio over default impl. Fixes #1021
=> Fix regressions in Header

.babelrc, package.json, src/TypeDefinition.js, src/views/CardStack.js, src/views/CardStackTransitioner.js, src/views/Header.js, src/views/TabView/TabBarIcon.js, src/views/TabView/TabBarTop.js, website/package.json, website/scripts/build.js, website/yarn.lock, yarn.lock
This PR switches `babel-plugin-flow-prop-types` to our fork temporarily as the npm version is broken for higher order components.
We will switch back to `npm` when this gets merged: https://github.com/brigand/babel-plugin-flow-react-proptypes/pull/76
That unbreaks website build.
=> Upgrade `babel-plugin-flow-prop-types`

docs/api/navigators/StackNavigator.md
There was a duplicate in docs/api/navigators/StackNavigator.md where the headerBackTitle instructions was duplicate. I removed the first one after title.
=> removed reptiton of headerBackTitle text

src/views/CardStackTransitioner.js
`screenProps` were not being passed to `CardStack` and consequently not available for the navigationOptions function in components using `StackNavigator`.
To test, I modified the Playground app to use `screenProps` in the title of the profile screen:
```diff
diff --git a/examples/NavigationPlayground/js/App.js b/examples/NavigationPlayground/js/App.js
index c5cb31b..4c590e3 100644
--- a/examples/NavigationPlayground/js/App.js
+++ b/examples/NavigationPlayground/js/App.js
@@ -115,7 +115,7 @@ const AppNavigator = StackNavigator({
mode: Platform.OS === 'ios' ? 'modal' : 'card',
});
-export default () => <AppNavigator />;
+export default () => <AppNavigator screenProps={{ name: 'Ville' }} />;
const styles = StyleSheet.create({
item: {
diff --git …
```
=> Fix screenProps not being passed through to CardStack

docs/api/navigators/TabNavigator.md, src/TypeDefinition.js, src/views/TabView/TabView.js
This fixes #1024
tabBarLabel used to have the same possibilities as tabBarIcon. Unfortunately in the latest updates that was lost. This returns the feature to allow Labels to change with tab focus.
example image should be possible again
=> Allow tabBarLabel to be also a function again

docs/api/navigators/StackNavigator.md, src/TypeDefinition.js, src/views/Header.js
Fixes #1136.
Currently `truncatedTitle` is hard-coded to `"Back"` and there is no configuration option to override that default. Because apps can be translated to other languages than English, it's necessary to be able to replace the text with a localized string.
I tested the config by adding a translated  `headerTruncatedBackTitle` in the stack navigation example:
```diff
diff --git a/examples/NavigationPlayground/js/SimpleStack.js b/examples/NavigationPlayground/js/SimpleStack.js
index 3ab204f..d10648e 100644
--- a/examples/NavigationPlayground/js/SimpleStack.js
+++ b/examples/NavigationPlayground/js/SimpleStack.js
@@ -89,6 +89,10 @@ const SimpleStack = StackNavigator({
path: 'photos/:name',
screen: MyPhotosScreen,
},
+}, {
+  navigationOptions: {
+ …
```
=> Add a config to override the truncated back title

src/views/Header.js
Addresses https://github.com/react-community/react-navigation/pull/1137#discussion_r112804103.
Instead of the current screen, the truncated back button title needs to be looked up from the previous one, like we do for the back title.
Added the option to profile screen of the playground app to test:
```diff
diff --git a/examples/NavigationPlayground/js/SimpleStack.js b/examples/NavigationPlayground/js/SimpleStack.js
index 3ab204f..66ca498 100644
--- a/examples/NavigationPlayground/js/SimpleStack.js
+++ b/examples/NavigationPlayground/js/SimpleStack.js
@@ -66,6 +66,7 @@ MyProfileScreen.navigationOptions = props => {
const {params} = state;
return {
headerTitle: `${params.name}'s Profile!`,
+    headerTruncatedBackTitle: 'Tillbaka',
// Render a button on the right …
```
=> Get truncated back button title from the previous scene

docs/api/navigators/DrawerNavigator.md
This relates to #709, adding a remark about the consequences of nesting the `DrawerNavigation`  may help users in the future.
=> docs: add remark about nesting

docs/api/navigators/Navigators.md, src/createNavigationContainer.js
This PR moves logger to `onNavigationStateChange` as a default implementation. You can turn it off by passing your own function or a `null`.
Breaking: `onNavigationStateChange` cannot be set on a controlled component anymore. If you are passing `navigation` prop yourself to a Navigator, you can utilise `componentDidUpdate` of an outer component. This prop is now reserved for `top-level` navigators that are stateful and control their state internally.
=> Add an ability to disable built-in logger

docs/guides/Redux-Integration.md
Fixes #1180
We shouldn't rely on a non-default babel transform, which is `decorator`s
=> Update Redux guide

docs/api/routers/Routers.md
The existing examples are broken and do not work. We need to update property, not `router` reference.
Fixes #1038
=> Update router guide

docs/api/navigators/TabNavigator.md, package.json, src/views/TabView/TabView.js, yarn.lock
The breaking change is because `lazyLoad` is renamed to `lazy` to match the prop present in `TabViewAnimated`
Release notes - https://github.com/react-native-community/react-native-tab-view/releases
=> BREAKING: Update React Native TabView

src/views/TabView/TabView.js
Fixes #662 
Android doesn't support nested scrollviews/viewpagers. Since that what we use for TabView, nested tab navigators are broken on Android.
This PR changes the implementation to not use `ViewPagerAndroid` when swipe and animations are disabled to allow nesting tab navigators. When 2 tab navigators are nested, and either the parent/child navigator has swipe and animation disabled, it will work fine.
In future we can change the check to see if only swipe is disabled after I manage to port the library to use native animations.
Tested both on iOS and Android.
cc @grabbou
=> Switch pager when swipe and animations are disabled. Fixes #662

src/createNavigationContainer.js, src/views/CardStack.js, src/views/Drawer/DrawerScreen.js, src/views/SceneView.js, src/views/TabView/TabView.js
Fixes #1197 
Note: This was added in recent commit and caused some issues with the way components are re-rendered. It's removed as it was never actually documented and used.
If you stumble upon this PR / diff, please express your use-cases so we got better overview on how to implement that.
=> Remove navigationOptions from component props

docs/api/navigators/StackNavigator.md, src/views/CardStack.js
Fixes #902
Adding swipe down gesture back to modals.
Tested within our app on iOS and android.
Animations on android probably need some work but does the job. Card animation animates downwards.
=> Modal gestureEnabled

src/views/CardStack.js
test fails since #1231
`383:25  error    'options' is assigned a value but never used  no-unused-vars`
@grabbou
=> make test pass

src/views/HeaderStyleInterpolator.js
This temporarily fixes back button titles that overlap each other. Ultimate fix is to provide animation from title to back button title.
=> Avoid back button label overlap

docs/api/navigators/StackNavigator.md, src/TypeDefinition.js, src/views/Header.js, src/views/HeaderBackButton.js
I'm currently migrating an existing iOS app to React Native, where I use customized titles and back buttons.
The titles currently can be styled using `headerTitleStyle`, but for the back button there was no such option.
So this change adds a `headerBackTitleStyle` screen option, which makes it possible to set the style for the back button title ~, and when not set it inherits the `headerTitleStyle`~.
**TODO**
=> add headerBackTitleStyle screen option

examples/NavigationPlayground/js/ModalStack.js
`headerVisible` is no longer a valid option.
=> fix toggle header example

src/TypeDefinition.js
Before [this fix](https://github.com/facebook/react-native/commit/c7387fefc85fd15dceadfa291857099ed3e848b8) landed last month, Flow wasn't evaluating the types of any imports from react-native. This fix isn't in RN 0.44.0, but it is in master.
The type of the Easing function in TypeDefinition.js is mistyped, and this trips up Flow errors when using react-native master (with Flow 0.45.0, as specified in master's package.json). This pull request simply fixes the type.
I've tested this with RN 0.44.0/Flow 0.42.0 (current npm releases) as well, and it doesn't cause any new Flow errors there.
Test plan:
In a project using react-navigation and react-native:
```bash
npm install --save react-native@0.44.0 # install npm react-native
vim .flowconfig # set flow version 0.42.0
npm install --save-dev …
```
=> Fix type of Easing function to match type in react-native module

docs/api/navigators/StackNavigator.md
If you attempt to use something other than a string, it will throw an error in some situations. #1318 provides more details about the error. If it is expecting a certain type, the docs should clarify that.
=> clarify title option

src/views/TabView/TabBarBottom.js, src/views/TabView/TabBarTop.js
This expands on #1156 in that it now passes tintColor to tabBarLabel functions as per the documentation.
=> Pass tintColor to tabBarLabel within navigationOptions

src/TypeDefinition.js, src/views/Header.js
To allow composition of the Header component when using a custom header
component, styling is probably one of the options you want to have.
For example, I need to dynamicly change the height of the header based
on scroll position, and without this change I have to inherit from the
Header component and copy the render function, instead of composing the
Header component in my own component.
=> accept style prop on Header component

src/createNavigationContainer.js
when accepting both a protocol url and a normal url, it's hard to define a static prefix.
So for example, in the application I'm currently working on we use iOS applinks for deeplinking, but also want to use a protocol url (`myapp://...`) for in-app linking. Doing this using a static string prefix I also have to use do parsing of the path in `getActionForPathAndParams`, but when using a regex this extra parsing can be omitted.
**NB.** using a regex does already work, but it's nice to have it typed too.
=> allow uriPrefix to be a regular expression

src/routers/StackRouter.js
This Init{index} pattern guarantees that the same keys will always be re-used when doing a RESET.
This behaviour doesn’t match how the rest of the router works and causes bugs.
Namely if you are on `{ routeName: ‘Dashboard’, params: { user: ‘A’ } }` and use RESET to `{ routeName: ‘Dashboard’, params: { user: ‘B’ } }` when the user switches, it will act like a `setParams` action instead of a `RESET` action and the Dashboard will not be re-mounted.
=> Don’t use `Init#` keys for reset

examples/NavigationPlayground/js/StacksInTabs.js, examples/NavigationPlayground/js/StacksOverTabs.js, examples/ReduxExample/src/components/AuthButton.js
It was previously a bit unclear what was going on because of the wording used. Now all screens are called "screens", tabs are called "tabs", "Open" means push a screen on the stack, and "Go to tab" means change the tab without pushing on top. It's a small change that hopefully helps clear up some confusion and make it more intuitive.
Also adds the header back to the StacksOverTabs example so the scene titles are visible.
---
*Note to reviewers: I'll be traveling for the next couple weeks. Hopefully this can be merged without issue, but I'll try to respond to comments when possible (or on May 23 when I return). Branch is rebased and up to date, and owners have permission to push directly to this branch:*
```console
git remote add cooperka https://github.com/cribspot/react-navigation.git …
```
=> [Minor] Update Stacks examples for better clarity

src/views/HeaderBackButton.js
We are using Appium for end2end testing and need to be able to access the back button. An appropriate `testID` is the way to do this.
Here you can see the back button identified in Appium:
=> Add testID to HeaderBackButton

src/views/CardStack.js, src/views/TransitionConfigs.js
following #1036
`Animated.spring` with `bounciness = 0` is not the right way to mimic a decay animation, the animation doesn't finish immediately when the `Animated.Value` gets to the `toValue`, it will still bounce in a short time
I didn't measure the bouncing duration, but I can tell it's there, in my app, I get two screens with different `barStyle` of `StatusBar`, it's visually sensible that I have to wait for about 100ms until the `StatusBar` changes the barStyle. Although in #1036 I've skipped the `Transitioner` animation after swiped back, but the bouncing time is still there, after change `Animated.spring` to `Animated.timing`, the `StatusBar` changes the barStyle immediately after transition animation
I also changed the animation config in `src/views/TransitionConfigs.js` because …
=> stop using Animated.spring

circle.yml, examples/NavigationPlayground/package.json, examples/NavigationPlayground/yarn.lock, examples/ReduxExample/package.json, examples/ReduxExample/yarn.lock
If we yarn install in the example dirs and website in the "dependencies" stage, then we can cache their node_modules directories, making CI faster.
=> Update Circle.yml with more caching

docs/api/navigators/DrawerNavigator.md, src/views/Drawer/DrawerNavigatorItems.js, src/views/Drawer/DrawerSidebar.js, src/views/Drawer/DrawerView.js
Among other things, this allows sections and dividers to be implemented by providing multiple DrawerView.Items with partial versions of `navigation.state.routes`.
`getScreenOptions` is also exposed so contentComponent can make use of its own navigation properties.
Here's a screenshot of an app with a custom contentComponent using these changes to add its own divider/subheading handling.
=> Allow the routes outputted by DrawerView.Items to be overridden

docs/api/navigators/TabNavigator.md, src/views/TabView/TabBarBottom.js
Adds tabStyle property for TabNavigator under tabBarOptions. Would close issue #1472.
```jsx
tabBarOptions: {
activeTintColor: '#e91e63',
labelStyle: {
fontSize: 12,
},
tabStyle: {
width: 100
},
style: {
backgroundColor: 'blue',
},
}
```
=> Added tabStyle property

src/react-navigation.js
(from #1326)
I prefer to use the transitioners and other components directly over using the helper functions since I want more fine tuned control over them.
Previously, I was using the CardStack component by itself, but within the last few betas a lot of its functionality has been moved to CardStackTransitioner and it now doesn't have much useful behavior by default. Currently the only normal way to get an instance of the component is by creating an entire StackNavigator.
I keep my router declarations separate, so the main issue I have against just using a StackNavigator instance is that I can't use an existing router instance.
=> Expose CardStackTransitioner as export (closes #1326)

package.json, yarn.lock
This adds 2 changes:
https://github.com/react-native-community/react-native-tab-view/commit/13243a2c6e048c73b089de63da58b7320fdb8bf0
https://github.com/react-native-community/react-native-tab-view/commit/27429c9fcc7b50598732c38062b2ead270f93618
I'm so stupid that this didn't occur to me earlier. This should now make it possible to absolutely position the tabs properly.
cc @skevy
=> Upgrade React Native Tab View to v0.0.66

package.json, yarn.lock
`react-native-drawer-layout-polyfill@1.3.1` fixes a bug which failed to clear interactions meaning that functions invoked through `InteractionManager.runAfterInteractions` were never called.
For this reason it is currently not possible to do the "render inexpensive component until navigation is done"-trick in a `DrawerNavigator`.
See [react-native-drawer-layout#16](https://github.com/react-native-community/react-native-drawer-layout/issues/16)
Moved from issue #1626
=> Update drawer layout polyfill to 1.3.1

package.json, src/StateUtils.js, src/createNavigationContainer.js, src/routers/TabRouter.js, src/routers/createConfigGetter.js, src/routers/getScreenConfigDeprecated.js, src/routers/getScreenForRouteName.js, src/routers/validateRouteConfigMap.js, src/routers/validateScreenOptions.js, src/utils/invariant.js, src/utils/shallowEqual.js, src/views/PointerEventsContainer.js, src/views/ScenesReducer.js, src/views/Transitioner.js
fbjs is a big part of the dependencies of this project, as can be seen here:
```diff
├─┬ react-navigation@1.0.0-beta.10 invalid
│ ├── clamp@1.0.1 extraneous
+│ ├─┬ fbjs@0.8.12
+│ │ ├── core-js@1.2.7
+│ │ ├─┬ isomorphic-fetch@2.2.1
+│ │ │ ├── node-fetch@1.7.0 deduped
+│ │ │ └── whatwg-fetch@1.1.1 deduped
+│ │ ├── loose-envify@1.3.1 deduped
+│ │ ├── object-assign@4.1.1 deduped
+│ │ ├── promise@7.1.1 deduped
+│ │ ├── setimmediate@1.0.5
+│ │ └── ua-parser-js@0.7.12
│ ├── hoist-non-react-statics@1.2.0
│ ├── path-to-regexp@1.7.0 extraneous
│ ├── prop-types@15.5.10 deduped
│ ├── react-native-drawer-layout-polyfill@1.3.1 extraneous
│ └── react-native-tab-view@0.0.65 extraneous
```
It is required for only two small functions that can be easily incorporated into the source code of this project.
It …
=> Removed dependency on fbjs

src/views/HeaderBackButton.js
**Summary**
This fixes the slight blurring of the back icon in stack navigator on iOS due to a mismatch between absolute pixel sizes of the icon (and the `@2x`, `@3x`, etc) and the stylesheet width and height.
The alternative here would be to regenerate all the iOS icons at the correct resolution (20x12 @ 1x), but I believe @grabbou has the master file (7a20389e04a41de65e145a456c7dcacb787aad24).
**Test plan**
Before:
After:
=> Correct sizing of header back button image on iOS

src/views/TabView/TabView.js
To support for example filtering the tabs (like @satya164 suggested here: https://github.com/react-community/react-navigation/issues/717#issuecomment-287392565)  based on a property passed to a parent navigator, I need to have to access to the screenProps in the tab bar.
=> pass screenProps to TabBarComponent

src/views/Header.js
First PR related to [Improve performance for React Navigation](https://github.com/react-community/react-navigation/issues/1466)
Although the HeaderBackButton is a `PureComponent` - we are binding a new function on each re-render which still causes a rerender of HeaderBackButton
=> Reduce re-renders on header back button

src/views/Drawer/DrawerSidebar.js
Right now if same screen is opened from drawer multiple times, it'll push the screen to the stack every time. So navigating back will render the same screen over & over. This commit fixes that.
The issue was explained in a comment in here [https://github.com/react-community/react-navigation/issues/954#issuecomment-302872661](https://github.com/react-community/react-navigation/issues/954#issuecomment-302872661)
=> DrawerNav: don't push screen to stack if it's already focused

src/createNavigationContainer.js
previously when opening a deeplink without a path, it would result in an array of 2 empty strings, which is are falsy values, so the full url was passed on.
by checking if the value is actually `undefined` instead of falsy we have no more false positives
=> allow empty path to be matched

docs/guides/Guide-Nested.md
After having to look for a solution for nesting a navigator embedded in a component, found this issue that dealt with the same problem: https://github.com/react-community/react-navigation/issues/90.
Added the solution to the guide as a side note.
=> Add doc note for nesting wrapped navigator

scripts/compile-docs.js
macOS creates metadata files named `.DS_Store`. The script incorrect tries to read it with a `.md` extension.  By excluding all files that start with a dot we can prevent this.
Excerpt from the error:
```
Error: ENOENT: no such file or directory, open 'docs/.DS_Store.md'
at Object.fs.openSync (fs.js:557:18)
at Object.fs.readFileSync (fs.js:467:33)
```
=> ignore files starting with a dot

src/views/HeaderTitle.js
This PR replaces `Text` component by its animatable version `Animated.Text`.
Having an animatable component for the header title allows features like the change of header title opacity based on the scroll animation.
=> Use animatable text component for the header title

src/views/Header.js
**Motivation:**
If you have N screens in the stack (talking about StackNavigator), then back button on screen N will have a title of N - 1 screen. Although, there is a `navigationOptions.headerBackTitle` which is responsible for managing a back button title I've mentioned above. So this option doesn't really work well: currently, it takes `headerBackTitle` from the *previous* screen instead of a current one which doesn't make a lot of sense to me (and I assume is a bug). 
**Explanation:** 
Imagine you have a screen N, N->N1 & N->N2. On screen N1 I want to use a default behavior (show N title as a title of my back button), on screen N2 I want to remove back button's text. Thus, if I specify `headerBackTitle` on screen N (which is how it works at the moment), I won't be able to achieve this …
=> [BUGFIX] Use a proper source of headerBackTitle

src/views/Header.js
Reverts react-community/react-navigation#2007
Unfortunately not the behavior we want. Going to go with an updated proposal in a follow up PR.
=> Revert "[BUGFIX] Use a proper source of headerBackTitle"

docs/api/routers/StackRouter.md
Add missing ":" in `routeConfig` example.
=> Fix StackRouter docs typo

src/views/CardStack.js
Very small pr, the flow annotation was also defined in the NavigationTransitionProps section on line 62. https://github.com/react-community/react-navigation/pull/1993/files#diff-1bb911cc75b3e921fd5d4db86802c58cL62
=> Removed duplicate navigation flow annotation in CardStack

src/TypeDefinition.js
Fix #252 
In _TypeDefinition.js_, `NavigationParams` should use a `mixed` type instead of `string`, since you may have a param with an integer, or an array for example.
=> Fix flow type for NavigationParams

examples/NavigationPlayground/js/CustomTabs.js
The way as it was before was good, but when there are another Navigations, such as TabNavigation, inside this TabNavigation. The entire nested navigation won't get rendered.
I was sitting here for hours in the source code, but this finally made the move.
=> Fix ActiveScreen in custom navigation

yarn.lock
yarn.lock was mistakenly modified in #2527. This reverts all changes to it except for the intended one allowing tests to once again pass.
=> Revert changes to yarn.lock

src/navigators/DrawerNavigator.js, src/views/Drawer/DrawerView.js
By enabling `useNativeAnimations` the drawer navigator is significantly quicker.
Option is opt in so shouldn't affect any current users.
=> Expose useNativeAnimations for Drawer navigator

package.json
I’m interested in trying to tighten up the test suite and tooling to try and help support contribution and accessibility of the codebase.
This PR make a few really minor changes around the test suite and coverage collection. Namely it;
- excludes the runner setup file from coverage
- includes the actual library codebase in coverage to get a more realistic picture of coverage
I would love to get this merged as I’m interested in trying to work on some reliability and stability issues and IMO it’s critical for to have a test suite that is maintained.
Naturally this will result in a massive decrease in coverage, but at least that number is a real number and not a false indication of actual coverage.
1. Run `jest` without this diff and see the jest setup file included in coverage
2. Run `jest` …
=> Trivial: Ignore the jest setup file when calculating test coverage.

README.md
This PR adds a link to the README for https://github.com/react-navigation/react-navigation-links. This is a list of curated links that are helpful for learning about react-navigation.
If you can come up with a more meaningful section title than "Helpful Resources", please comment 😄
=> Add RNNavigation Links Repo to README

package.json, yarn.lock
This change comes thanks to @plasticine's great idea (https://github.com/react-community/react-navigation/pull/2581#issuecomment-329661371).
- Add husky and lint-staged to use pre-commit hook.
- Automate formatting JavaScript code using ESLint and Prettier before committing changes.
1. Break the format of some code files.
1. Check whether they are automatically re-formatted when trying committing them.
=> Employ pre-commit hook for formatting code.

.eslintrc
Replace 0, 1 and 2 with "off", "warn" and "error" because texts seem more readable than numbers.
I confirmed `npm run lint` didn't show any warning and error.
=> Refactor .eslintrc to be more readable.

src/utils/invariant.js, src/utils/shallowEqual.js
See #2658. These `@providesModule` ("Haste") declarations are not necessary since every file imports these modules using the full path. We're removing them because they declare the same modules as the fbjs packages do (the files are actually copied in from there), so Flow gets confused and doesn't know which to use.
=> Remove @providesModule declarations in src/utils to avoid Flow conflicts with fbjs package

examples/NavigationPlayground/app.json, examples/NavigationPlayground/package.json, examples/NavigationPlayground/yarn.lock, examples/ReduxExample/app.json, examples/ReduxExample/package.json, examples/ReduxExample/yarn.lock
Example apps now use rn 48 and expo 21. `yarn test` passes on both apps and running in simulator and device works.
=> Updates examples to react-native 0.48.4 and expo sdk 21.

package.json, src/TypeDefinition.js, src/views/Header/Header.js, src/views/__tests__/__snapshots__/withOrientation-test.js.snap, src/views/__tests__/withOrientation-test.js, src/views/withOrientation.js, yarn.lock
Replaces #2629.
While working on adding support for iPhoneX/iOS11 I saw incorrect behavior with the header. Currently, when a device goes to landscape mode the status bar is hidden (as expected) but the header component height stays the same. This can be seen in the following GIF.
Install `react-navigation` from `spencercarli/react-navigation#improve-status-bar-behavior2` into the NavigationPlayground example and spin your device around. You should see the following behavior.
=> Improve StatusBar/Header Behavior

docs/guides/Guide-Intro.md
Fixes #832 - the code in this page was wrong, that `export default` was causing errors.
I've also modified a few phrases here and there to help the comprehension.
=> Fixing Intro Guide

docs/api/navigators/DrawerNavigator.md
There's a typo in the docs -- when specifying drawerLockMode in screenProps, it should be "screenProps.drawerLockMode", not "screenProps.lockMode". 
Tested on iOS and Android.
=> Fix "drawerLockMode" typo in DrawerNavigator docs

src/navigators/DrawerNavigator.js, src/views/Drawer/DrawerSidebar.js, src/views/Drawer/DrawerView.js
**DrawerNavigator**
I added a property to **drawerConfig**, which is **drawerBackgroundColor**, because I needed to use the transparent background to make a shadow and I could not.
example:
`const drawerConfig = {
drawerBackgroundColor: 'transparent'
};`
=> Added property inside drawerConfig to backgroundColor

src/routers/StackRouter.js, src/routers/__tests__/StackRouter-test.js
This pull request solves issue #2251 by introducing a `nestedQueryString` variable that is either the original `queryString` or an empty string (when `queryString` is null), that gets passed as part of the path for retrieving the nested action in `StackRouter``s `getActionForPathAndParams`.
I modified `src/routers/__tests__/StackRouter-test.js` by adding an additional test case, starting on the line `test('Querystring params get passed to nested deep link', () => {`. It is mostly a combination of two existing tests:
1. The one with title `Correctly parses a path with arguments into an action chain` with uri value `'main/p/4/list/10259959195'`
2. The ones titled `Parses paths with a query` and `Parses paths with an empty query value` that make use of uris ending …
=> Fix Querystring params not set for nested URI (issue #2251)

src/views/TabView/TabBarBottom.js, src/views/__tests__/TabView-test.js, src/views/__tests__/__snapshots__/TabView-test.js.snap
I saw that the behavior of the tabbar has changed in iOS11 - it no longer stacks the icon and label on top of itself in landscape. 
Install `react-navigation` from `spencercarli/react-navigation#ios-11-tab-bar` into an app with tab bar. I don't think this should affect customizations much (if at all).
I can't get the NavigationPlayground example to detect it's in landscape (limitation of CRNA?) so you'll need to create a new app. You can use [this](https://github.com/react-community/react-navigation/blob/master/examples/NavigationPlayground/js/StacksInTabs.js) as a start point. Should be copy and paste as long as you have `react-native-vector-icons` installed.
=> [iOS 11] Handle landscape tabbar correctly.

examples/NavigationPlayground/js/App.js, src/navigators/DrawerNavigator.js
Previously: calculated based on device width regardless of orientation and did not recalculate when orientation changed. If an app was opened in landscape, the drawer would be too wide if the device was rotated to portrait.
Now: calculates based on minimum of device height/width, drawer width remains constant and is guaranteed to always fit screen regardless of orientation.
This is the expected behavior based on observing Google apps (e.g. Gmail). This is also better than recalculating on every orientation change, which would result in variable width drawers and awkward empty space when in landscape in most cases.
Also added support for rotating device in NavigationPlayground example app.
=> Fixes default drawerWidth to match Material UI patterns.

src/views/TabView/TabBarBottom.js
Fixes regression I caused in #2676. The tabbar will now work correctly on iOS 10, iOS 11, and Android.
Will resolve #2772.
cc @kelset @joncursi
=> Fix tabbar bottom issue on Android.

src/navigators/__tests__/.eslintrc, src/navigators/__tests__/DrawerNavigator-test.js, src/navigators/__tests__/StackNavigator-test.js, src/navigators/__tests__/TabNavigator-test.js, src/navigators/__tests__/__snapshots__/DrawerNavigator-test.js.snap, src/navigators/__tests__/__snapshots__/StackNavigator-test.js.snap, src/navigators/__tests__/__snapshots__/TabNavigator-test.js.snap
Add minimal unit tests for the DrawerNavigator, StackNavigator and TabNavigator.
This PR was motivated because I went to add unit tests in my own codebase to a class that inherited from StackNavigator and I wanted to see what StackNavigator's unit tests looked like. Turned out that there weren't any :-)
=> Add tests for navigators

src/TypeDefinition.js
Very small changing which remove unused imported vars in TypeDefinition.js.
=> Remove unused imported vars

docs/guides/Screen-Navigation-Prop.md
Reverts react-community/react-navigation#2809 (my bad, it wasn't broken in the first place)
=> Revert "fix broken link to the Navigation Actions guide"

src/routers/TabRouter.js
Bug explain:
There's unwanted redirection if action with type `Navigation/SET_PARAMS` is dispatched in stacks in tab navigator. It was critical bug for our app. 
Bug demonstration: https://expo.io/@sujameslin/react-navigation-bug-reproduce
Like you see the bug demo, it was supposed to be showing the first tab, but its showing 2nd tab after load.
Source code: https://github.com/sujameslin/react-navigation-bug-reproduce/blob/master/App.js#L55-L57
=> fix redirect bug in stacks in tab

src/views/TabView/TabView.js
This is a follow-up of the last two PRs (#2733 and #2385) that adresses [this problem](https://github.com/react-native-community/react-native-tab-view/issues/312).
This:
* fixes the `initialLayout` prop conflicts
* sets the default `initialLayout` in `defaultProps` rather than on every render (and doesn't mutate props)
* uses the window's width and height to avoid the one frame delay
=> Set initialLayout in defaultProps on Android

examples/NavigationPlayground/js/App.js, examples/NavigationPlayground/js/Banner.js, examples/NavigationPlayground/js/CustomTabs.js, examples/NavigationPlayground/js/CustomTransitioner.js, examples/NavigationPlayground/js/Drawer.js, examples/NavigationPlayground/js/ModalStack.js, examples/NavigationPlayground/js/SimpleStack.js, examples/NavigationPlayground/js/SimpleTabs.js, examples/NavigationPlayground/js/StacksInTabs.js, examples/NavigationPlayground/js/StacksOverTabs.js, examples/NavigationPlayground/js/TabsInDrawer.js, examples/NavigationPlayground/package.json, examples/NavigationPlayground/yarn.lock, src/navigators/__tests__/__snapshots__/DrawerNavigator-test.js.snap, src/navigators/__tests__/__snapshots__/StackNavigator-test.js.snap, src/navigators/__tests__/__snapshots__/TabNavigator-test.js.snap, src/react-navigation.js, src/views/Drawer/DrawerNavigatorItems.js, src/views/Header/Header.js, src/views/SafeAreaView.js, src/views/TabView/TabBarBottom.js, src/views/TabView/TabView.js, src/views/__tests__/__snapshots__/TabView-test.js.snap
This adds support for iPhone X to react-navigation via SafeAreaView. 
- Uses a JS approach that can be used in RN v0.49 and lower. 
- Includes `forceInset` prop, which is not available on the native version that will be released in RN v0.50. 
- Adds SafeAreaView to Header, Drawer, and Tab views. 
- Updates NavigationPlayground to provide testing and examples of SafeAreaView use.
This essentially mimics the native version by adding padding on the side of the view that touches a screen edge. Ideally the API introduced here will eventually be migrated into the native version of SafeAreaView where performance will be much better.
* Only available in RN v0.50, which will be released maybe a day or two before iPhone X is released.
* Inset is added as padding and cannot be customized as margin …
=> Add iPhone X SafeAreaView

docs/api/navigators/StackNavigator.md, docs/api/navigators/TabNavigator.md, src/TypeDefinition.js, src/navigators/__tests__/__snapshots__/StackNavigator-test.js.snap, src/navigators/__tests__/__snapshots__/TabNavigator-test.js.snap, src/views/Header/Header.js, src/views/TabView/TabBarBottom.js, src/views/__tests__/__snapshots__/TabView-test.js.snap
Fixes #2854 and preemptively fixes the issue about TabBar backgroundColor not working.
- adds `headerBackgroundColor` prop to navigationOptions
- adds `backgroundColor` prop to tabBarOptions
I could have just applied the style/headerStyle prop to the wrapping SafeAreaView, but this would cause unexpected behavior if padding was ever specified, since SafeAreaView overrides padding.
I also tried simply getting the backgroundStyle out of the style/headerStyle object, but those objects can also be an index: number from StyleSheet, and would fail in those cases.
=> Fix backgroundColor in Header and TabBar

docs/api/navigators/DrawerNavigator.md, src/views/Drawer/DrawerNavigatorItems.js
Fixes second part of issue #2854.
`itemsContainerForceInset` takes the same object as `forceInset` on SafeAreaView. It overrides the SafeAreaView container in DrawerItems.
=> Override `forceInset` on DrawerItems.

src/views/Header/HeaderStyleInterpolator.js
Fixes #2864. 
Difference should be calculated by two values it needs to fit between. It was previously calculated from largest and smallest numbers, not considering the middle number.
Tested on iOS and Android.
=> Fixes inputRange on headerStyleInterpolator

src/react-navigation.js
> Explain the **motivation** for making this change. What existing problem does the pull request solve?
Closes https://github.com/react-community/react-navigation/issues/912.
I exported all of the Flow definitions from src/TypeDefinitions.js, so that you can import the types without having to reach into the internals of the library.
**Before:**
```js
import {type NavigationState} from 'react-navigation/src/TypeDefinition';
```
**After:**
```js
import {type NavigationState} from 'react-navigation';
```
> Prefer **small pull requests**. These are much easier to review and more likely to get merged. Make sure the PR does only one thing, otherwise split it.
Well, it's one line, so… I don't think I can make it much smaller 😉
> Demonstrate the code is solid. Example: The exact commands you ran …
=> Export flow types

README.md
Remove extra `#` from Comparisons and Discussion to fix linking
=> [Docs] Fix Comparisons Link in Readme

README.md
The `good first issue` tag link was broken in the README, linking to a nonexistent `Type: Good First Task` label.
=> Fix 'good first issue' link in README

src/views/SafeAreaView.js
With the recent change to add SafeAreaView there was a change that broke projects using `react-navigation` inside `react-native-web`. The use of `DeviceInfo` and more specifically the property `isIPhoneX_deprecated` caused exceptions anytime `SafeAreaView` is used with `react-native-web`. This meant that `Header` couldn't be used without `SafeAreaView` being fixed.
Test that the functionality still works correctly in native by opening a `StackNavigator` with a header on both native (iOS or Android) and Web (via `react-native-web`)
=> SafeAreaView - Fix for Web usage

src/routers/StackRouter.js
As reported in #2953, deep linking with uri that contains query params does not work anymore on master. query params are not passed down the state params.
inputParams is by default equal to {} [as can be seen here](https://github.com/react-community/react-navigation/blob/d1c434b54c73b6ed17b1642acd6646fbca92c92e/src/createNavigationContainer.js#L87), therefore, queryParams returns always {} even if queryString is not empty.
Test plan:
tested by the author of #2953 as seen [here](https://github.com/react-community/react-navigation/issues/2953#issuecomment-344181884)
=> fix 2953 (Deep Linking - related)

docs/api/navigators/DrawerNavigator.md, src/navigators/DrawerNavigator.js, src/navigators/__tests__/__snapshots__/DrawerNavigator-test.js.snap, src/views/Drawer/DrawerNavigatorItems.js, src/views/Drawer/DrawerSidebar.js, src/views/Drawer/DrawerView.js
The SafeAreaView was breaking custom contentContainers in drawers. This fixes #2963.
=> Move SafeAreaView out of DrawerNavigatorItems to DrawerSidebar.

docs/guides/Navigation-Actions.md, src/NavigationActions.js, src/__tests__/NavigationActions-test.js
There's a [growing](https://github.com/redux-saga/redux-saga/issues/732) [trend](https://github.com/reactjs/redux/issues/628#issuecomment-135077511) of defining a custom `toString` to return the type of a given action creator function. This is a convenience that alleviates the need to import both an action creator and type constant.
This simple PR adds a custom `toString` to the action creator factory, and adds basic tests to avoid regressing this behavior in the future.
=> Add toString() with type for each NavigationAction

docs/api/navigators/DrawerNavigator.md, src/navigators/DrawerNavigator.js, src/navigators/__tests__/__snapshots__/DrawerNavigator-test.js.snap, src/views/Drawer/DrawerView.js
Current implementation is simplified / broken.
- The drawerWidth doesn't work for tablets, the drawer becomes massively large
- Header size changes (and thus drawer width changes) in landscape mode on iOS are not accounted for
- An incorrect 64px header size is used for iOS (this includes the status bar height that doesn't belong in the calculation)
Implement a default drawerWidth as a function that follows the Material Design spec closer:
- Screen width - header height
- Use the correct iOS app bar height in portrait and landscape mode
- Drawer max height of 280 on mobile and 320 on tablet
=> Fix default width of drawer

jest-setup.js, src/__tests__/NavigationContainer-test.js, src/createNavigationContainer.js
Mostly fixes #1206
I've added tests:
* To validate the dispatch => true/false return value behaviour is retained
* `dispatch` functions normally, updating the state by the next tick
* The change to `dispatch` works, allowing 2 calls to dispatch to work in the same tick without throwing away data
* react-test-runner applies setState synchronously instad of waiting for the next tick like React normally does so the test file makes sure to inject a batching strategy that applies setState when `jest.runOnlyPendingTimers();` is called
* The test also verifies that state has **not** been updated synchronously immediately after the dispatch call to ensure that  jest committing setState synchronously does not result in a falsely passing test
=> Make sure dispatch can be called multiple times per-tick

src/routers/validateRouteConfigMap.js
In React Fiber (React 16), strings are used for intrinsics like 'div' and 'View'. As a result, if you use a View as a screen in an academic experience, you get a red error screen. This PR prevents that from happening.
=> Allow strings Component types through as screens

docs/api/navigators/TabNavigator.md, src/views/TabView/TabBarBottom.js, src/views/TabView/TabBarTop.js, src/views/TabView/TabView.js
Goals:
- pass the previous scene to the `tabBarOnPress` callback, together with its current arguments
Why?
- Implementing some custom logic (ie: reset the child navigator of the scene we are leaving) was not possible in other ways
Please see issue #2787
Being it an argument (which always exists) passed to a callback, the only tests I can deliver are the type checks and the current tests themselves.
=> Add previous scene to tabBarOnPress - fix #2787

docs/api/navigators/TabNavigator.md, examples/NavigationPlayground/js/App.js, examples/NavigationPlayground/js/TabAnimations.js, src/navigators/TabNavigator.js, src/views/TabView/TabView.js
**Motivation**
This is in response to https://github.com/react-community/react-navigation/issues/2202 .
This change is needed to allow the `configureTransition` option for `TabViewAnimated` to be passed through. This opens up the opportunity to customize the animation when switching between tabs. 
NOTE: I'm not sure why [this clause](https://github.com/react-community/react-navigation/compare/master...davidtrogers:master#diff-6f52f52094e1001dd754981e92d9f933L167) is needed but I left it in place so as to not cause a regression. If `renderPager` isn't passed in to `TabViewAnimated` then it will default to [`TabViewPagerScroll`](https://github.com/react-native-community/react-native-tab-view#tabviewpagerscroll-) (iOS) or [`TabViewPagerAndroid`](https://github.com/react-native-community/react …
=> Allow transition configuration between tabs

src/views/TabView/TabBarBottom.js
After doing some more thorough testing I came to the conclusion that using `KeyboardAvoidingView` should handle the issue described in #618 and this reverts PR #1764 (TabBarBottom should hide itself when Keyboard is activated) which was addressing the issue, but seems to cause more harm than good according to some comments in https://github.com/react-community/react-navigation/pull/1764.
The `KeyboardAvoidingView` can be used like this: https://snack.expo.io/B1udZbp0b
=>  revert #1764

docs/guides/Guide-Intro.md
#Browse the official example app, which will `demonstrates` various patterns with React Navigation. 
demonstrates should be `demonstrate`
=> Typo On "Getting Started 3."

src/TypeDefinition.js, src/createNavigationContainer.js
Adding types for these fixes the errors we're seeing when using `TabNavigator` and `StackNavigator`. We should finally be able to close #2933 now.
=> Add NavigationContainer and NavigationContainerProps types

examples/ReduxExample/app.json
This small PR fixes "React Native version mismatch" error in ReduxExample.
=> Set sdkVersion to 23.0.0

src/routers/TabRouter.js, src/routers/__tests__/TabRouter-test.js
**Motivation**
As described in [#875](https://github.com/react-community/react-navigation/issues/875) TabRouters seem to incorrectly pass down the inner action when delegating to the current tab (If delegating the action to other tabs the original action is always passed)
**Test plan**
I've added a test case to demonstrate a minimal case of the issue I was having and the change fixes this.
=> Only delegate inner action to current tab if the outer action matches

src/routers/TabRouter.js, src/routers/__tests__/TabRouter-test.js
`TabRouter.getStateForAction` has some code at the start to initialize an empty nav state before handling any action. This initialization is achieved by passing `INIT` actions to all child routes. However, the code strangely also passes these child routes the params that were given to the action. The initialization should be separate from the processing of the action.
=> Don't use params from unrelated action when initializing nav state

examples/NavigationPlayground/README.md, examples/README.md, examples/ReduxExample/README.md
The Contributors Guide link for instructions on running example apps was referring to an old md file.
=> Update Contributors Guide link

docs/api/navigators/StackNavigator.md, src/TypeDefinition.js, src/views/CardStack/CardStack.js
Enables configuration of the back gesture direction. This is useful if the app uses custom right-to-left navigation transitions with the `transitionConfig.sreenInterpolator` configuration parameter. Discussion around this topic can be found in issue #2393.
**Test plan**
Configuring the repository `ReduxExample` app with the following right-to-left transition configuration
```javascript
export const AppNavigator = StackNavigator({
Login: { screen: LoginScreen },
Main: { screen: MainScreen },
Profile: { screen: ProfileScreen },
}, {
navigationOptions: () => ({
gestureDirection: 'inverted',
}),
transitionConfig: () => ({
screenInterpolator: sceneProps => {
const { layout, position, scene } = sceneProps;
const { index } = scene;
const width = layout.initWidth;
return {
transform: [{ …
```
=> Enable configuration of gesture direction

docs/api/navigators/TabNavigator.md, examples/NavigationPlayground/yarn.lock, package.json, src/navigators/TabNavigator.js, src/views/TabView/TabView.js, src/views/__tests__/__snapshots__/TabView-test.js.snap, yarn.lock
With this update, the `lazy` option has been removed, so it's a breaking change.
- It didn't work great with more than 2 tabs
- It's not very performant to listen to all events during the gestures since we're trying to move away towards native gestures.
- It basically triggered a re-render of the whole tab view mid-gesture, which could cause jank
I understand that it's still desirable to lazily load tabs, so I think it's time we implement [`focus` events](https://github.com/react-community/react-navigation/issues/51) so that this can be implemented in userland. The approach I'd go with is this:
- Implement a placeholder component for each tab screen based on a `loaded` state
- When a tab screen is focused, toggle the `loaded` state and replace placeholder component with actual content
=> Upgrade react-native-tab-view

src/createNavigationContainer.js
Fixes issue https://github.com/react-navigation/react-navigation/issues/2599, where an ejected expo app would mount the initial route twice.
The root cause turns out to be as follows:
1. On mount, the navigation container [checks for the initial URL with `Linking.getInitialURL()`](https://github.com/react-navigation/react-navigation/blob/master/src/createNavigationContainer.js#L161-L163)
2. An ejected expo app returns a path-less URI, e.g. `expb91fecbd0fc74b86ab71881fc10189e8://`.
3. This [edge case was not handled in `NavigationContainer#_urlToPathAndParams`](https://github.com/react-navigation/react-navigation/blob/master/src/createNavigationContainer.js#L85-L88) that mistakenly interpreted the url to be a schema-less route name. 
4. The route name [gets passed to …
=> If URL is just a scheme:// component without a path, default to root "/" URL

src/views/Drawer/DrawerView.js
Drawer does not toggle as per [this](https://github.com/react-community/react-navigation/issues/2760) issue. `this._drawer.state.drawerShown` seems to be available only on iOS?
Works on both iOS and Android (Issue didn't exist in iOS in the first place)
=> Fix drawer toggle

src/utils/ReactNativeFeatures.js, src/views/CardStack/TransitionConfigs.js
In RN >= 0.50, I added a new spring implementation that mimics Apple's spring algorithm from CASpringAnimation (commit here: https://github.com/facebook/react-native/commit/26133beda9034d374afb95b3a653353e25c40c84). This PR makes TransitionConfig use this new spring implementation with the exact values that UINavigationController uses for it's animation.
For RN < .50, we'll continue using the old bezier curve.
=> Use stiffness/damping/mass for card stack transition on React Native >= 50

src/views/Header/Header.js
Back button in simple playground will close the stack example rather than popping within the stack.
This avoids the problem by telling goBack the key to go back FROM
=> Simple fix to back button behavior

src/navigators/DrawerNavigator.js, src/navigators/NavigatorTypes.js, src/navigators/StackNavigator.js, src/navigators/TabNavigator.js, src/navigators/createNavigator.js
It has some legacy of being potentially necessary to support hybrid case in some situations, but it's no longer used and we don't need it.
Run tests, run playground app
=> Remove NavigatorTypes

examples/NavigationPlayground/js/SimpleTabs.js, examples/ReduxExample/app.json, examples/ReduxExample/package.json, examples/ReduxExample/src/navigators/AppNavigator.js, examples/ReduxExample/src/reducers/index.js, examples/ReduxExample/yarn.lock, src/__tests__/getChildEventSubscriber-test.js, src/getChildEventSubscriber.js
This fixes the redux example after we added the event system. (fixes #3355)
Now redux apps must fire the top-level 'action' event for any callers of `navigation.addListener`, and this example demonstrates how that may be accomplished
=> Add events support to redux example

src/views/TouchableItem.js
Just a minor polishment: TouchableItem.js defines
```
static defaultProps = {
borderless: false,
pressColor: 'rgba(0, 0, 0, .32)',
};
```
so using eg. `this.props.borderless || false` can be just `this.props.borderless`
Tried it out with my app, works as before.
=> rely on defaultProps in TouchableItem

src/TypeDefinition.js, src/routers/TabRouter.js, src/routers/__tests__/TabRouter-test.js
Allow the passing in of `initialRouteParams` into `TabRouter`'s config since `StackRouter` already has that feature. The request was filed [here](https://github.com/react-navigation/react-navigation/issues/1790).
First PR, please let me know if I've missed something!
=> allow initialRouteParams for TabRouters

examples/NavigationPlayground/js/SimpleStack.js, examples/NavigationPlayground/js/SimpleTabs.js, src/TypeDefinition.js
dca37627a243b191fda5856aa6ce9eb1ee4957cf broke the types, but it wasn't noticed because Flow wasn't in the CI. This fixes the types; separate PR coming to add Flow to the CI.
=> Fix NavigationEvent types

examples/NavigationPlayground/package.json
In order to make sure that contributors don't making breaking changes to our Flow types without corresponding updates to the libdefs, we should make sure these breaking changes get caught by CI. Right now our libdefs are any-typed, but I'll put up a PR later that will refine the libdef (located at `flow-typed/npm/react-navigation_vx.x.x.js`).
=> Add NavigationPlayground Flow test to CI

src/NavigationActions.js, src/addNavigationHelpers.js, src/routers/KeyGenerator.js, src/routers/StackRouter.js, src/routers/__tests__/StackRouter-test.js
The navigation action will now always behave idempotently when called with a key. When pushing, it will push a route with that key. If the route already exists, it will navigate to that route and set the params.
This is a commonly requested feature, and will address the needs of #2334 #135 #1313, #2400, #2578
=> Idempotent navigate with key for StackRouter

package.json, src/routers/StackRouter.js, src/routers/__tests__/StackRouter-test.js
There are a ton of issues relating to reset, because there is no way to match the key of the state that you are setting. This change makes that possible.
We should also probably add a way to do this from the navigation helpers so that you can do `props.navigation.reset({key, ...`
=> StackRouter Reset Action should match state key

src/NavigationActions.js, src/addNavigationHelpers.js, src/navigators/__tests__/__snapshots__/StackNavigator-test.js.snap, src/routers/StackRouter.js, src/routers/__tests__/StackRouter-test.js, src/views/__tests__/__snapshots__/TabView-test.js.snap
A commonly requested feature for the StackRouter, which often forces people to use the reset action.
This supports an "immediate" param, which may not work until the transitioner handles immediate transitions.
This adds `popToTop` to the navigation helpers, which are technically available even when there is no stack router in use. Eventually I think we should move away from "addNavigationHelpers" to address this problem
=> StackRouter PopToTop Action

src/NavigationActions.js, src/addNavigationHelpers.js, src/navigators/__tests__/__snapshots__/StackNavigator-test.js.snap, src/routers/StackRouter.js, src/routers/__tests__/StackRouter-test.js, src/views/__tests__/__snapshots__/TabView-test.js.snap
New action behaves like "navigate" on a stack, but does not accept a key because it always pushes
=> New StackRouter Push Action

.babelrc, .gitignore, examples/NavigationPlayground/.flowconfig, package.json
The build scripts were removed in cbd1fee8a440887ca1a4b7cde93ac04f376f7327, but some of the stuff they were using (namely, Babel configurations) were left in place. This PR removes them.
=> Clean up old build process and Babel config

src/NavigationActions.js, src/views/CardStack/CardStack.js
As reported in #3345, the events do not fire properly when swiping back. This causes the completed back swipe to cause `immediate` transition, and the events are correct.
=> Fix events issue when swiping back

src/views/Transitioner.js
This fixes a CardStack gesture regression, as noted in https://github.com/react-navigation/react-navigation/issues/700#issuecomment-362943948
This breaking code was added during the events implementation, but I think we should be able to manage this circumstance from the parent context. In any case, the events bugs that *might* result from this change will be far less insidious than the cardstack transitioner issue that we experience now.
=> Fix Transitioner race condition

src/NavigationActions.js, src/navigators/StackNavigator.js, src/routers/StackRouter.js
The completion action would previously change the isTransitioning of any state, but this will ensure that the completing navigator only marks its own state as isTransitioning:false. Now, even when transition completion happens immediately on the parent, the child focus event still waits for the child isTransitioning to go false.
=> Key for completion action, to prevent eager didFocus

src/views/Header/Header.js
Resolves #2795.
Due to the changes made post-iOS 11, when any iOS 11 device is in the landscape orientation, the header is shrunk to 32pts height.  Unfortunately, this incorrectly applies to tablets as well.  This simply looks at the layout height and only shrinks if it is landscape and the vertically small (similar to how Apple's Size Classes determine whether the header should be shorter).  On tablets with lots of vertical space, even in landscape, the header is not made smaller.
Before:
After:
Notice the extra space around the right tab bar button in the 44pt version.
Notes:
* This only affects iOS (per the pre-existing platform check).
* This method is similar to how I fixed #2794 in #3041.
* The use of Dimension is platform-detection, and is only used on the initial frame before the …
=> Fix #2795 - Not reducing header height in landscape on iPad

examples/NavigationPlayground/js/SimpleStack.js, flow/react-navigation.js, src/NavigationActions.js, src/addNavigationHelpers.js, src/navigators/__tests__/__snapshots__/StackNavigator-test.js.snap, src/routers/StackRouter.js, src/routers/__tests__/StackRouter-test.js, src/views/__tests__/__snapshots__/TabView-test.js.snap
The long awaited action to replace a route in StackNavigator!
Has a nearly identical API to navigate, except the key is mandatory. Currently the behavior will keep the same key intact, and simply allow changing of the routeName, params, and child router action.
Alternatively, we could decide that replacement means the key changes. In that case, the action would need to be able to specify the new key, in addition to the key of the route being replaced. Would this be named "replaceKey"?
=> StackNavigator Replace Action

src/NavigationActions.js, src/routers/StackRouter.js, src/routers/__tests__/StackRouter-test.js
Replace should actually provide new keys on the replaced route, use ‘newKey’ on the action if you want to define the new route key
=> Fix StackRouter Replace Key Behavior

examples/NavigationPlayground/js/SimpleStack.js, src/routers/StackRouter.js
Previously the state was getting squashed, in this case it would destroy the routeName of the state, which was a route for the parent navigator, who could no longer render properly.
=> Fix issue with StackRouter popToTop

examples/NavigationPlayground/js/SimpleStack.js, src/routers/StackRouter.js, src/routers/__tests__/StackRouter-test.js
`pop` and `popToTop` are local to the current navigator. You can use `goBack` to do a `pop` that bubbles up.
Run tests, try it in the playground example.
=> Prevent pop and popToTop from bubbling up to parent stack

src/NavigationActions.js, src/__tests__/NavigationContainer-test.js, src/routers/StackRouter.js, src/routers/__tests__/StackRouter-test.js
The most straightforward fix for two issues is to block all navigation actions while mid-transition of a stack navigator. This will fix:
The double-navigate on double tap issue, because the first navigation will start the transition and the second action will be ignored.
Will fix the buggy header experience that you can see when going back and forward to a different route quickly. This happens because the next navigate action happens before the completion action. After the fix, the navigate action will be ignored, the user will tap again, and will see a good transition
=> StackRouter block actions while transitioning

src/routers/TabRouter.js, src/routers/__tests__/Routers-test.js
Resolves https://github.com/react-navigation/react-navigation/issues/3471
Run tests, try to reproduce the issue in the tabs in stacks example in NavigationPlayground.
https://github.com/react-navigation/rfcs/issues/12
=> Make TabRouter handle COMPLETE_TRANSITION in a child router without switching active index

src/views/withNavigation.js
This will allow for refs with onRef (fixes #3461)
Also avoids `hoist-non-react-statics` in favor of explicitly hoisting router and navigationOptions
=> Support for withNavigation HOC onRef

src/routers/StackRouter.js, src/routers/__tests__/StackRouter-test.js
example:
```js
StackNavigator({
search: {
screen: SearchScreen,
path: 'search/:keyword'
}
})
```
When you pass encoded URI like `app://search/2018%2F02%2F07` for deep link, it passes raw value `params: { keyword: '2018%2F02%2F07' }`  to `SearchScreen`. 
It's not consistent with the behavior when calling `.navigate('search', { keyword: '2018/02/07' })` from JavaScript. 
Also, it has trouble when you use multi-byte language characters such as Japanese.
(ex:  https://ja.wikipedia.org/wiki/%E3%82%A6%E3%82%A3%E3%82%AD%E3%83%9A%E3%83%87%E3%82%A3%E3%82%A2 )
I think it would be better to pass decoded params to screen.
=> [BREAKING] Decode URI encoded string of deep link

examples/NavigationPlayground/js/App.js, flow/react-navigation.js, src/routers/__tests__/createConfigGetter-test.js, src/routers/__tests__/validateRouteConfigMap-test.js, src/routers/getScreenForRouteName.js, src/routers/validateRouteConfigMap.js
When getting started, and often until deep linking is required, people use the following style of route config:
```js
const MyStack = StackNavigator({
ScreenA: { screen: MyScreen },
ScreenB: { screen: MyOtherScreen },
ScreenC: { screen: MyNestedNavigator },
});
```
This PR doesn't change that (it's still valid), but it also makes the following valid:
```js
const MyStack = StackNavigator({
ScreenA: MyScreen,
ScreenB: MyOtherScreen,
ScreenC: MyNestedNavigator,
});
```
Run tests, try playground.
I don't know how to update the type interface for this &mdash; I get a bunch of errors with the following:
```
declare export type NavigationScreenRouteConfig =
| NavigationComponent
| {
screen: NavigationComponent,
}
| {
getScreen: () => NavigationComponent,
};
```
cc @Ashoat @ericvicenti
=> Make Router({ RouteName: Component }) a valid way to configure a router

flow/react-navigation.js, package.json
My first thought was to do it through `eslint`, which already runs on `precommit`. However, `eslint` has a custom parser, and the only way to get it to process flow-typed files is with `babel-eslint`, but `babel-plugin-transform-flow-strip-types` can't handle the libdef-specific syntax `declare export type`.
Since we can't get `eslint` to run Prettier for us, I just set up `lint-staged` to call it on the libdef file separately. I'm don't feel too strongly about running Prettier on the libdef, so if this approach is too messy/brittle let me know and we can scuttle it.
=> Run Prettier on Flow libdef on precommit

src/PlatformHelpers.native.js, src/PlatformHelpers.web.js, src/createNavigationContainer.js
The Linking component is now supported by react-native-web. It also provider BackHandler as a dummy components, so there's no need to supply dummy replacements ourselves.
So this fixes the warning, and React Navigation on react-native-web should now be able to pick up the initialUrl too.
=> Remove Linking/BackHandler from PlatformHelpers.

src/__tests__/addNavigationHelpers-test.js, src/addNavigationHelpers.js, src/navigators/__tests__/__snapshots__/StackNavigator-test.js.snap, src/views/__tests__/__snapshots__/TabView-test.js.snap
Handling `navigation.state.params.name` when `params` doesn't exist results in an error. 
Initially, I was going to create an empty object.
After reading #2046, I went with the suggestion of creating a `getParam` helper instead.
- Set a parameter
- Get the parameter
- Get an undefined parameter
=> Add getParam navigation helper

examples/NavigationPlayground/js/App.js, examples/NavigationPlayground/js/TabsWithNavigationFocus.js, flow/react-navigation.js, src/react-navigation.js, src/react-navigation.web.js, src/views/withIsFocused.js, src/views/withNavigationFocus.js
As discussed in other issues, we should be able to know easily which screen has the focus.
This HOC idea has been mentioned here by @satya164 and @ericvicenti 
- https://github.com/react-navigation/react-navigation/issues/51#issuecomment-276003658
- https://github.com/react-navigation/react-navigation/issues/51#issuecomment-278761705
- https://github.com/react-navigation/react-navigation/pull/3345#issuecomment-360260067
Here is a basic implementation using the new lifecycle hooks to provide this feature
=> add withNavigationFocus HOC

src/createNavigationContainer.js
Back button handlers added in children of the NavigationContainer would register before the NavigationContainer's global handler. This resulted in the need for an awkward workaround to get a handler to fire before the global handler from a navigation view: https://github.com/nodevember/nodevember-2017-mobile/blob/07d92947a1295bf1ea3365d9e09690c923c5f4dd/src/Navigation.js#L190-L193
I tested it in the Nodevember app linked to above.
=> Move the back button handler subscription to the NavigationContainer constructor

package.json, src/PlatformHelpers.native.js, src/PlatformHelpers.web.js, src/views/Header/Header.js
https://github.com/react-navigation/react-navigation/pull/3526 introduced use of MaskedViewIOS component. I created a stub in PlatformHelpers.web.js for it, and inverted a Platform test in the code.
No UI changes, code passes tests.
=> Fix react-native-web support for #3526

src/views/Transitioner.js
I have been investigating `<Header />` component performance once again today with `render` cycles in particular. I have observed that during `push` phase, a typical Header in NavigationPlayground re-renders 3 times on iOS and 2 times on Android.
The first time is obvious on both platforms since that's when we add a new scene to an array. Second on iOS was also self-explanatory - we measure title width and other layout parameters in order to provide a better animation. 
What got me thinking was the last render cycle that didn't have a clear origin. After digging around I've found it is caused by a `scenes` array changing when transition finishes. What is surprising, it's just the reference to the object that changes, the content (items inside) stay the same.
I have found out that this is …
=> Improve `Header` performance a bit

examples/NavigationPlayground/.flowconfig, examples/NavigationPlayground/js/App.js, examples/NavigationPlayground/js/SimpleStack.js, examples/NavigationPlayground/js/StackWithTranslucentHeader.js, examples/NavigationPlayground/package.json, examples/NavigationPlayground/yarn.lock, flow/react-navigation.js, src/navigators/__tests__/__snapshots__/StackNavigator-test.js.snap, src/views/Header/Header.js
- The Header implementation has some artifacts that aren't useful anymore.
- `headerStyle` accepted style properties that could break it (https://github.com/react-navigation/react-navigation/issues/3457). These style properties are no longer applied and a warning is shown in dev mode.
- Title, left, and right components of header have `flexDirection: row` now, so you can use `alignSelf` to adjust the vertical positioning easily. (this also resolves https://github.com/react-navigation/react-navigation/issues/3457 -- you can add `alignSelf: 'flex-end'` to each of the header components styles).
- It is sometimes useful to have a transparent header, so you can render any background you want. I expect this will often be a BlurView. So I added `headerTransparent?: boolean` and …
=> Several improvements to StackNavigation Header

flow/react-navigation.js, src/NavigationActions.js, src/createNavigationContainer.js, src/routers/__tests__/StackRouter-test.js, src/routers/__tests__/TabRouter-test.js
About a year ago, https://github.com/react-community/react-navigation/pull/120 was merged, renaming the old navigation actions to new ones, eg. `Init` renamed to `'Navigation/INIT'`. Along with that change, `mapDeprecatedActionAndWarn` was introduced so that things wouldn't break for people using the old navigation actions. The warning informed users that 
> The action type '${oldType}' has been renamed to '${newType}'.`, '${oldType}' will continue to work while in beta but will be removed, in the first major release.
So I figured it's a good time to remove the `mapDeprecatedActionAndWarn` from the code base. Given the warning and the amount of time it was there, I do not think it will affect library users. It also makes the code slightly more straightforward, which is always a good …
=> remove support for deprecated navigation actions

src/NavigationActions.js, src/routers/StackRouter.js, src/routers/__tests__/StackRouter-test.js, src/views/TabView/TabBarBottom.js, src/views/TabView/TabBarTop.js
The expected behavior for tab bars is that when you have a stack within them and tab the icon for the active tab, then it should pop that stack to the top. This adds that behavior, partially solving https://github.com/react-navigation/react-navigation/issues/3588. The next step is to scroll a scrollview to top if the user taps again after popping to top.
Try out navigation playground Stacks in Tabs.
- ~I don't think this is actually a shippable solution in its current form due to the following edge case: if there are no stacks within the TabNavigator, but the TabNavigator is nested within another StackNavigator, then the pop to top action would be handled by the parent. I think we need to change `popToTop` to optionally accept a key.~ &mdash; I updated popToTop to accept a key and …
=> Pop to top on TabNavigator when tapping already focused tab icon

src/routers/StackRouter.js
https://github.com/react-navigation/react-navigation/issues/3279
If you pass nested action within reset actions it has no effect.
| software         | version
| ---------------- | -------
| react-navigation | 1.1.2
| react-native     | 0.52
Bug examples:
snack: https://snack.expo.io/H11t9nRvz
repo: https://github.com/serhiipalash/react-navigation-bug-3279-example
Bug screenshots:
when you press "Reset with nested action"
you see new stack like there was no nested action
Expected behaviour:
If I pass nested action within reset actions it should trigger changes in child router.
Fix:
Go to `fix-3279` branch in bug example repo to test this fix
https://github.com/serhiipalash/react-navigation-bug-3279-example/tree/fix-3279
=> Fix bug #3279 “Action within RESET doesn't trigger”

flow/react-navigation.js
The `init` action creator doesn't not required `payload` parameter.
https://github.com/react-navigation/react-navigation/blob/2bb91a6740e2f1ade012906dc03c972ba6375cc3/src/NavigationActions.js#L24
Notice the `default` value
=> fix typespec of `init` action creator

CONTRIBUTING.md, README.md, yarn.lock
I've found that there is no `CONTRIBUTING.md` file, which is the first thing I look for when I want to contribute to the new codebase (GitHub spoiled me)
This PR moves the "How can I help?" copy from `README.md` to `CONTRIBUTING.md`. I also link to it from the readme in that very section.
=> Move contributing guide to CONTRIBUTING.md

examples/NavigationPlayground/js/App.js, examples/NavigationPlayground/js/SwitchWithStacks.js, flow/react-navigation.js, src/navigators/SwitchNavigator.js, src/navigators/__tests__/SwitchNavigator-test.js, src/navigators/__tests__/__snapshots__/StackNavigator-test.js.snap, src/navigators/__tests__/__snapshots__/SwitchNavigator-test.js.snap, src/react-navigation.js, src/routers/SwitchRouter.js, src/routers/__tests__/SwitchRouter-test.js, src/views/SwitchView/SwitchView.js
Authentication flows are kind of difficult to implement currently, and given that 1) they're something that just about every app has and 2) they're usually built early on in the process, we need to make auth flows super easy to implement. This PR introduces SwitchNavigator, which allows you to easily jump from one screen to another, and it unmounts the previous screen and resets its route, and has no "back" behavior by default. This is all done just by calling `navigate`. I've added an example for how to do this to the NavigationPlayground.
This PR is intended to solve the problem immediately for 1.x users. I will open another PR with this rebased against master (now home to changes that won't land until 2.0) and with further more radical changes including making TabRouter and …
=> Add SwitchNavigator

src/getChildEventSubscriber.js, src/views/CardStack/CardStack.js, src/views/Drawer/DrawerView.js, src/withCachedChildNavigation.js
I tracked down the memory leak reported in https://github.com/react-navigation/react-navigation/issues/3636 using Chrome memory tab and found that it was a result of creating new subscribers anytime a `StackNavigator` state changes. ~This PR only fixes it in `StackNavigator`, it is likely also a problem with other navigators but I don't want to invest too much time into those because I've already fixed it for all of them on master (for the upcoming 2.0 release, see: https://github.com/react-navigation/react-navigation/pull/3648). It would be nice for someone to follow up a PR to apply these same changes to other navigators.~ I believe this also applies to other navigators and made the appropriate changes here. This PR does not clean up upstream subscribers when a navigator unmounts, …
=> Cache child event subscriptions (1.x branch)

examples/NavigationPlayground/js/App.js, examples/NavigationPlayground/js/TabsWithNavigationFocus.js, src/views/CardStack/CardStack.js, src/views/Drawer/DrawerView.js, src/views/__tests__/__snapshots__/TabView-test.js.snap, src/views/withNavigationFocus.js, src/withCachedChildNavigation.js
`withNavigationFocus` didn't initialize with the correct state, it always assumed not focused. This PR adds a helper to get the focused state and uses that to properly initialize the state in `withNavigationFocus`. More discussion in https://github.com/react-navigation/react-navigation/pull/3512
In a follow-up PR I'll port this to master (the 2.0-track branch), which should be a good amount less code thanks to only adding navigation helpers in one place.
Run playground example. Tests pass.
=> Add isFocused helper to navigation and fix withNavigationFocus (1.x branch)

flow/react-navigation.js
Should be nullable, since it is initially called as `null` in `src/createNavigationContainer.js` (and in `react-navigation-redux-helpers`, where it is causing a Flow error).
=> Fix NavigationEventPayload.lastState type

flow/react-navigation.js
https://github.com/react-navigation/react-navigation/blob/c6301abaed51ef7ac2aa370ed18d66e39ca9e15d/src/NavigationActions.js#L21 doesn't required `params`
=> Fix typespec of back action creator

src/__tests__/getChildEventSubscriber-test.js, src/getChildEventSubscriber.js, src/navigators/createNavigator.js, src/routers/createConfigGetter.js, src/views/Drawer/DrawerView.js
Caching: https://github.com/react-navigation/react-navigation/issues/3636
Cleanup: https://github.com/react-navigation/react-navigation/issues/3354
I haven't added explicit test coverage for this yet but I should before we merge it.
=> Cache event subscribers and clean up after unmounting

examples/ReduxExample/package.json, examples/ReduxExample/src/navigators/AppNavigator.js
I.e. call react-navigation-redux-helpers's initializeListeners() when mounting app
per https://github.com/react-navigation/react-navigation-redux-helpers/issues/7
=> Update ReduxExample so that the first nav click works with nested TabNavigators

flow/react-navigation.js
Fixed the navigation props type to be a tad more specific since it leaving it as just NavigationState created a seemingly-impossible-to-resolve situation with type parameters.
=> More specific injected Navigation props in Flow definition

flow/react-navigation.js
`children` prop should be optional.
See https://github.com/flowtype/flow-typed/commit/4ec24a5b93eb832b5879b239900174029d92d13b#commitcomment-27932697
=> Flow type: SafeAreaView doesn't require children

flow/react-navigation.js
As seen here: react-navigation/react-navigation#360, we need to be able to pass null to turn off logging.
This PR mirrors https://github.com/flowtype/flow-typed/pull/1912, which will be overridden when this repo is merged into flow-typed.
=> Allow passing null to onNavigationStateChange prop

flow/react-navigation.js
1. Remove `NavigationComponent` from `NavigationScreenRouteConfig`. The only context `NavigationScreenRouteConfig` is used in is as an intersection with an object, and as such the only relevant portions of `NavigationScreenRouteConfig` are the object parts.
2. Add static `HEIGHT` variable to `Header` type.
3. In `NavigationContainerProps`, make `onNavigationStateChange` property value nullable.
PS: if in the future you guys would prefer that I separate these sort of PRs into their constituent parts, let me know.
=> [Flow] Some updates, mostly from flow-typed

package.json, src/views/ResourceSavingSceneView.js, src/views/TabView/TabView.js, yarn.lock
@aksonov pointed out that `addListener` expands the API surface area for the view API. This changes tabs to use a focused prop instead of `addListener`.
Tests, playground app.
=> Swap addListener out for isFocused prop on ResourceSavingSceneView

src/navigators/StackNavigator.js
The `initialRouteKey` stack config option was introduced in 1.5.0 in the `StackRouter`. However, it is not being passed into `StackRouter` from `StackNavigator`.
=> Pass initialRouteKey into StackRouter (#3540)

src/withCachedChildNavigation.js
- when in a tab container, isFocused is a function on first render an boolean afterwards
- closes #3709
---
I think this is the culprit. I made a pr to make it simpler to fix. If you think the issue should be fix in another way, just close this! 3709 is still valid :)
=> Fix isFocused from withNavigationFocus is a function

src/routers/StackRouter.js, src/routers/__tests__/StackRouter-test.js
Described in this pending RFC: https://github.com/react-navigation/rfcs/pull/25
It's worth noting that it's unclear to me whether this is intuitive / desirable for the case of `pop` and `popToTop`. There is a clear case for `push`, however, and in order to be consistent I changed the others. We might want to make `pop` accept a key for a router that it is scoped to optionally, but this is another issue.
I updated tests accordingly, and you can try it in NavigationPlayground in Simple Stack.
=> Make push, pop, and popToTop bubble like navigate

examples/NavigationPlayground/js/SimpleStack.js, flow/react-navigation.js, src/__tests__/addNavigationHelpers-test.js, src/addNavigationHelpers.js, src/navigators/createNavigator.js
Sometimes you want to be able to dismiss a nested stack, for example if you have a root stack that goes from your main app to a modal stack, you might want to go back to the main app when you're n screens deep in the modal stack. People came up with a pretty good solution for this in a previous discussion on the issues here: https://github.com/react-navigation/react-navigation/issues/686#issuecomment-292225313 - I just adapted this to `addNavigationHelpers`.
As for `navigation.carefullyGetParent`, we dicussed it on https://github.com/react-navigation/rfcs/issues/27.
Run tests, try it in playground.
=> Add dismiss helper, made possible by also adding carefullyGetParent

src/views/__tests__/TabView-test.js
**Summary**
I've noticed there's a leak in the test suite (process hanging) caused by not mocked timer in TabViewPagerScroll used by default on iOS. 
FYI, the leak was detected by running `jest --detectLeaks` flag.
Tests are green.
=> Fix memory leak in TabView-test.js

examples/NavigationPlayground/js/App.js, examples/NavigationPlayground/js/CustomTabNavigator.js
This is a simple example of how full navigators can be extended, and custom views can be rendered alongside them.
=> Add example for extending the Tab navigator

src/routers/StackRouter.js, src/routers/SwitchRouter.js, src/routers/__tests__/SwitchRouter-test.js, src/routers/__tests__/TabRouter-test.js
Adds a test for path matching on switch router. This use case is blocking some experimentation on web..
=> Fix path matching for SwitchRouter and empty paths

src/routers/StackRouter.js, src/routers/__tests__/StackRouter-test.js
This new behavior indicates that the action has been handled, but the state has not changed.
=> StackRouter to return null on idempotent navigation

examples/NavigationPlayground/package.json, examples/NavigationPlayground/yarn.lock
We were pretty far behind in react-native-script versions for the playground, so I updated them.
Test Plan:
Run `yarn`.
=> Update react-native-scripts in NavigationPlayground

examples/NavigationPlayground/js/StackWithHeaderPreset.js, src/navigators/__tests__/__snapshots__/StackNavigator-test.js.snap, src/views/Header/Header.js, src/views/Header/HeaderStyleInterpolator.js, src/views/StackView/StackViewLayout.js
This addresses #2732 (which also happens to be the top issue on canny.io).
Transitioning between screens with and without headers when `headerMode` is set to "screen" works just fine, but the current experience when `headerMode` is set to "float" is very broken. The goal of this PR is to replicate the behavior of UIKit on iOS: when a screen without a header is pushed, the header on the previous screen is pushed off the screen to the left, and the individual components of the header do not animate. When a screen with a header is pushed _after_ a screen without one, we slide the new header on the screen from right to left, in sync with the push animation, again while avoiding animating the individual header components.
I also updated the UIKit transition example in Navigation Playground to …
=> Smoothly transition header visibility in Stack

src/views/withNavigation.js
The navigation prop should also pass through, and be prioritized over context because it is more explicit
This also fixes an incorrect warning/invariant
=> withNavigation improvement

flow/react-navigation.js
according to implementation, this is legit:
```
navigation.navigate({
routeName: "EditAccount",
params: { account },
key: "editaccount"
})
```
however, the flowtype don't allow that.
=> Update Flowtype to support navigation.navigate({})

src/routers/SwitchRouter.js, src/routers/__tests__/SwitchRouter-test.js
Fixes #3788. This is a patch from [2.x](https://github.com/react-navigation/react-navigation/commit/bdda6fa5be2cbdef2a1f4f5b3a65fa4518003c27#diff-ae1aa3891dfecf6877acb9deb37db793) (not sure if we should just cherry-pick that commit instead?)
=> Add check for undefined prevState in SwitchRouter

examples/NavigationPlayground/js/App.js
Aside from Transitioner, this is the only reference to cWM in the repo.
The transitioner willMount is removed here: https://github.com/react-navigation/react-navigation/pull/3901/files
=> no more component will mount

src/views/StackView/StackView.js
There is an excess of dispatched events coming from this, because "onTransitionEnd" will happen even after immediate transitions.
This ensures that the completion action is only dispatched when it is explicitly needed
=> Avoid unnecessary navigation completion dispatches

src/views/Header/Header.js
This fix is super simple thanks to the new createNavigator scene descriptors concept. We want this button to call "go back from this scene", not "go back from this navigator". This should continue to ensure the back action is idempotent when pressing this button twice quickly.
=> Fix glaring header back button bug

src/createNavigationContainer.js
This fixes an issue where the container unnecessarily renders twice on startup when persistence is not used.
=> container initialization fix

src/navigators/__tests__/__snapshots__/StackNavigator-test.js.snap, src/views/Header/Header.js, src/views/StackView/StackViewLayout.js
The current technique we use to measure the header doesn't work properly because it is async and will cause the screen to jump. The main problem is that there's no way to know the height of the header synchronously for custom headers. For the default one we know the height already so it is pretty easy (although someone could use headerStyles to change the height and would break this).
This is mostly just to discuss the best way to fix this, I don't think using Header.HEIGHT is fine since it breaks custom header height but can be a good temporary patch for now.
I can see 2 possible solutions:
1. Try to read style props to figure out the height (might not be 100% reliable).
2. Add a navigationOption to customize the header height.
Tested that this fixes the flicker …
=> Use Header.HEIGHT instead of measuring to avoid flicker

src/views/Header/HeaderStyleInterpolator.js
This fixes a broken transition between 2 screens with no header.
https://user-images.githubusercontent.com/2677334/38449859-e9efc2d0-39e2-11e8-81cf-e5832e9effe9.gif
If we detect that we are transitioning between 2 screens with no header just make sure it is hidden, this avoids adding complexity to the already complex interpolation we use.
Tested that the fix works in the app where I noticed the bug.
=> Fix transition between 2 screens with no header

src/routers/__tests__/Routers-test.js, src/routers/__tests__/StackRouter-test.js, src/routers/__tests__/TabRouter-test.js
Motivation: https://github.com/react-navigation/react-navigation/issues/3785
- Changed mixed (i.e. nested + different-type) router tests in `TabRouter-test.js` and `StackRouter-test.js` to use same-type child routers, with some additional trivial edits for compatibility
- Moved original copies of the mixed router tests to `Routers-test.js` (necessary? 🤔)
- Moved misplaced `pop` action test in `TabRouter-test.js` to `StackRouter-test.js`
Haven't touched `SwitchRouter-test.js` yet because that entire test suite relies on mixed Switch-Stack routers and I'm not 100% certain if moving the code around like this is of any help, hence I'm making this PR first just to be sure!
=> Shift tests to isolate routers

src/views/Header/Header.js
Fixes issue where goBack is not a function in the modular uikit header back button. Use child navigation prop which has the goBack helper correctly scoped to this scene. Pressing the back button will dispatch an action to dismiss this scene/route
=> Fix header ModularLeftComponent to goBack from child navigation

src/views/StackView/StackViewLayout.js
My previous PR did not account for iPhone X and orientation changes, this fixes it.
One main issue that remains is translucent status bar on android, the library as a whole doesn't support it well anyway at the moment so I just left a TODO. 
Been using this patch for a while and tested it on iPhone X, normal iPhone and Android with orientation changes.
=> Fix header hardcoded height to accound for iPhone X and orientation changes

src/react-navigation.js
https://github.com/react-navigation/react-navigation/issues/3962
In v1.5.2 TabNavigator is a function
```
const TabNavigator = (routeConfigs, config = {}) => {
...
}
```
and default export from main file of `react-navigation-deprecated-tab-navigator` is not a function
https://github.com/react-navigation/react-navigation-deprecated-tab-navigator/blob/master/src/index.js#L6-L11
Current code leads to error `undefined is not a function`
```
get TabNavigator() {
...
return require('react-navigation-deprecated-tab-navigator').default;
},
```
This pull request fixes it.
=> Fix TabNavigator export ( Issue #3962 )

examples/NavigationPlayground/js/App.js, examples/NavigationPlayground/js/KeyboardHandlingExample.js, src/navigators/createKeyboardAwareNavigator.js, src/navigators/createNavigator.js, src/navigators/createStackNavigator.js, src/react-navigation.js, src/views/StackView/StackView.js, src/views/StackView/StackViewLayout.js
One thing that has always annoyed me in React Navigation is the handling of the keyboard. When a keyboard is visible on screen and a navigation action occurs (either by tapping a button or using a gesture), the keyboard tends to stay on screen until the transition completes. This feels janky and broken. On native iOS, for instance, the keyboard hides immediately when the navigation starts, and if the transition is cancelled (say, when the user releases the gesture), the keyboard reappears.
This PR introduces a "KeyboardAwareNavigator" higher order component that is enabled on the StackNavigator, unless a `disableKeyboardHandling` prop is passed into the StackNavigator's configuration.
@brentvatne @ericvicenti please let me know if you'd like a different API for this (aka whether or not …
=> Make StackNavigator keyboard aware

src/react-navigation.js
Looks like there's a typo in the deprecation notice for `TabNavigator` and `createTabNavigator`:
```diff
- createMaterialTopNavigator
+ createMaterialTopTabNavigator
```
For reference, `createMaterialTopTabNavigator is defined [here](https://github.com/react-navigation/react-navigation/blob/0890896824c507528e553f43ce421a2b6e934d46/src/react-navigation.js#L63).
=> Typo in deprecation notice

examples/NavigationPlayground/js/App.js, examples/NavigationPlayground/js/InactiveStack.js, src/StateUtils.js, src/__tests__/NavigationStateUtils-test.js, src/navigators/__tests__/__snapshots__/TabNavigator-test.js.snap, src/routers/StackRouter.js, src/routers/__tests__/StackRouter-test.js
Fixes https://github.com/react-navigation/react-navigation/issues/4063 and makes "less pushy" behavior consistent in this case with stack routers. It's unclear to me how useful this is in practice, but I was happy to implement it because it produces a consistent mental model, so we should have some good reasons to deviate if we do.
Run test, try example in playground
=> Give inactive routes in stack opportunity to handle action

examples/NavigationPlayground/js/SimpleStack.js, flow/react-navigation.js
Fixed issues:
- The typedef for [`getParam`](https://reactnavigation.org/docs/navigation-prop.html#getparam-get-a-specific-param-value-with-a-fallback) is missing.
- The return type for `withNavigation` is incorrect per the [flow documentation](https://flow.org/en/docs/react/hoc/#toc-injecting-props-with-a-higher-order-component) for injecting props with an HOC. The injected prop should be removed from the returned component's prop types. I'm not sure why this doesn't seem to cause an issue in the example app, but flow insisted I need a `navigation` prop in my own app until I fixed this.
- `React$*` is apparently considered private, and seems to cause some issues that `React.*` does not (https://github.com/flowtype/flow-typed/issues/1302, …
=> Fix missing/incorrect flow types

flow/react-navigation.js
Apparently `flow-typed` [silently converts imported libs to `any`](https://github.com/flowtype/flow-typed/blob/master/CONTRIBUTING.md#dont-import-types-from-other-libdefs). This fooled me into thinking I solved one of the typing issues i had with `withNavigation` when I converted `React$*` to `React.*`. I figured out the real issue (missing an `| void` in the return type for `withNavigation`), and converted back to `React$*`.
=> go back to React$, and fix real error

src/routers/__tests__/StackRouter-test.js, src/routers/__tests__/TabRouter-test.js
Adding these tests because reports from this issue make me nervous:
https://github.com/react-navigation/react-navigation/issues/1274
Everything is passing though, so I think the issue has been fixed in recent releases.
=> Add tests to confirm setParam behavior

src/StateUtils.js, yarn.lock
Creating a new array and iterating over all the routes is inefficient compared to findIndex, which does not create a new array and exits as soon as it finds a match. Since the indexOf method is used extensively this should provide a minor performance improvement.
=> StateUtils: Use Array.prototype.findIndex instead of map => indexOf

src/views/__tests__/Transitioner-test.js
This is a test which should ensure that #2856 is no longer an issue. It is taken from the original PR, with small modifications. I have verified that the test fails with 1.0.0-beta15 which was the release the PR was probably made for (it was made at the time of beta 15 release). It passes on the current master so the issue should not longer be present.
cc @brentvatne
=> add a test so that #2856 can be closed

src/routers/StackRouter.js, src/routers/__tests__/Routers-test.js
Fixes https://github.com/react-navigation/react-navigation/issues/4111
When you navigate with a specific route name and a custom action, we want to run the *child* action, rather than the top level action
=> Fix issue with nested navigation actions in stack

src/views/Drawer/DrawerSidebar.js
Broken in v2 for top-level drawer navigators, because there is no helper here
=> Fix drawer navigation dispatch

src/getChildEventSubscriber.js, src/navigators/createNavigator.js
Events were getting unsubscribed too early, so that the inner willBlur event was getting skipped when trying to “dismiss” a deep navigation stack.
This changes the un-subscription logic to happen within the event emitter itself, which should be a bit more maintainable. It will wait for a didBlur event on a route that is not in the stack, and then it will unsubscribe from the upstream events.
=> Fix event unsubscription logic

src/views/Drawer/DrawerSidebar.js
“reset” is not a NavigationAction anymore.
The correct fix, for v3, to this is to navigate to the first screen inside the stack. With the less-pushy navigate behavior in v2, this will result in the first route getting selected if you specify it by routeName.
=> Fix drawer stack reset-to-top behavior

src/routers/StackRouter.js
PR #3393 introduced a regression: in some cases a value of `isTransitioning` property of navigation state is lost.
In that PR there's a comment:
> // Return state with new index. Change isTransitioning only if index has changed
However, if index hasn't changed, `isTransitioning` becomes `undefined`. This PR makes `isTransitioning` to be indeed unchanged if index hasn't changed.
**Test plan**
You can check [this snack](https://snack.expo.io/@angly/istransitioning-issue) for demonstration. `stateAfterSecondNavigation` should have saved `isTransitioning` value from the previous state, which was `true`, but it became `undefined` (and because of that Expo's logging just don't print it at all). With this PR, it will preserve a value of `isTransitioning`.
=> Fix regression causing setting undefined value to isTransitioning

src/views/StackView/StackView.js
The completion action should always fire when the current navigation state isTransitioning.
There were some problems surrounding this with persisted states and isTransitioning.
=> Fix CompletionAction trigger

src/views/Header/Header.js, src/views/StackView/StackViewLayout.js
**Motivation**
Swipe back doesn't work in RTL mode by default and even when you set navigationOptions.gestureDirection to 'inverted' value to facilitate it functionality remains broken: one is able to swipe back but stack card responds to user's gesture in a jerky near-edge movement.
I've tested the new code in the app we develop (however I'm not at liberty to share screenshots / video due to NDA).
Steps to reproduce original issue are given at https://github.com/react-navigation/react-navigation/issues/4118.
P.S. I also fixed the default back button's mask in RTL mode.
Thanks guys!
=> Fix for broken swipe back gesture in RTL mode

examples/NavigationPlayground/js/SimpleStack.js, flow/react-navigation.js, src/navigators/__tests__/__snapshots__/TabNavigator-test.js.snap, src/views/__tests__/__snapshots__/TabView-test.js.snap
These changes were merged to master already, but they also belong in 1.x
Fixed issues:
- The typedef for [`getParam`](https://reactnavigation.org/docs/navigation-prop.html#getparam-get-a-specific-param-value-with-a-fallback) is missing.
- The return type for `withNavigation` is incorrect per the [flow documentation](https://flow.org/en/docs/react/hoc/#toc-injecting-props-with-a-higher-order-component) for injecting props with an HOC. The injected prop should be removed from the returned component's prop types. I'm not sure why this doesn't seem to cause an issue in the example app, but flow insisted I need a `navigation` prop in my own app until I fixed this.
=> [help wanted] Fix missing/incorrect flow types for 1.x branch

flow/react-navigation.js
"any" cripples the typechecker, so it's best to avoid. Two instances were introduced in #3392, but I don't think the intention was to keep it there.
=> [flow] Fixes for v2 libdef

flow/react-navigation.js
This fixes the Flow type to conform with the new API for `react-navigation@2.0`.
=> [flow] Fix tabBarOnPress type for react-navigation@2.0

examples/NavigationPlayground/js/SimpleStack.js, examples/NavigationPlayground/js/StackWithHeaderPreset.js, examples/NavigationPlayground/js/StackWithTranslucentHeader.js, examples/NavigationPlayground/package.json, examples/NavigationPlayground/yarn.lock, flow/react-navigation.js
This will force all Flow users to do runtime assertions if they want to use these action creators. Open to any better solutions.
=> [flow] Make StackRouter action creators optional and add DrawerRouter ones

examples/ReduxExample/src/navigators/AppNavigator.js, examples/ReduxExample/src/utils/redux.js
Using two new utils:
1. `createNavigationPropConstructor`, which is now preferred over `createReduxBoundAddListener`.
2. `initializeListeners`, which is necessary to trigger the event listeners with the initial state.
=> [examples] Update ReduxExample

README.md
OLD (link is broken and code coverage is coverage before renaming)
[![codecov](https://codecov.io/gh/react-community/react-navigation/branch/master/graph/badge.svg)](https://codecov.io/gh/react-community/react-navigation)
NEW:
[![codecov](https://codecov.io/gh/react-navigation/react-navigation/branch/master/graph/badge.svg)](https://codecov.io/gh/react-navigation/react-navigation)
=> Fix Codecov link -> react-community vs react-navigation

README.md
Displaying a badge is helpful for users but also contributors (for example to know why my upstream-rebased PR is not passing tests that seems unrelated to my PR)
The final result is:
[![npm version](https://badge.fury.io/js/react-navigation.svg)](https://badge.fury.io/js/react-navigation) [![codecov](https://codecov.io/gh/react-community/react-navigation/branch/master/graph/badge.svg)](https://codecov.io/gh/react-community/react-navigation) [![CircleCI badge](https://circleci.com/gh/react-navigation/react-navigation/tree/master.svg?style=shield)](https://circleci.com/gh/react-navigation/react-navigation/tree/master) [![PRs Welcome](https://img.shields.io/badge/PRs-welcome-brightgreen.svg)](https://reactnavigation.org/docs/contributing.html)
=> Add CircleCI Badge to README

src/views/StackView/StackViewLayout.js
Hello, this is a follow-up of this [commit comment](https://github.com/react-navigation/react-navigation/pull/4017#pullrequestreview-119239864): I noticed that on the web the header margin for the StackNavigator was off of several pixels. This is because the [condition](https://github.com/react-navigation/react-navigation/blob/master/src/views/StackView/StackViewLayout.js#L521) to target the platform is inversed compared to the condition for the app bar height [here](https://github.com/react-navigation/react-navigation/blob/master/src/views/Header/Header.js#L27). This may be worth refactoring in a separate PR (although there's no mention of the iPhone X on the latter file), let me know :)
* [Before](https://user-images.githubusercontent.com/82368/39893204-5387d78e- …
=> [Web] Fix header height margin

src/createNavigationContainer.js
Errors are getting stuck inside the `createNavigationContainer`, so implementing `componentDidCatch` above any Navigator isn't working. This fixes according to this issue #4250
=> fix(create-nav-container): pass up error on catch

src/views/Drawer/DrawerView.js
While migrating from v1 to v2, I lost the `navigationOptions through tree` feature and had to implement an alternative way to enable/disable the `DrawerLockMode` on `DrawerNavigator` .
> In previous version of React Navigation, the library used to dig through your component tree to find navigationOptions. This is no longer the case, and only navigationOptions on screen components of a particular navigator will apply to that navigator. You can read more about this in the Navigation options resolution guide.
[react-navigation v2 documentation](https://reactnavigation.org/docs/en/common-mistakes.html)
Looking at the code, seams like `DrawerLockMode` from `DrawerScreen options` is **read, initialised, but never used**. Might be a simple mistake, but this allow to be more flexible and I think …
=> Apply DrawerLockMode from DrawerScreen options to DrawerLayout component

src/navigators/createStackNavigator.js
**Motivation**
This PR fixes #4360. When creating stack navigator, `getCustomActionCreators` method is not passed to `StackRouter`, so custom action creators are not included in navigation props.
I've tested on iOS and Android. You can run following code snippet. 
```
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { createStackNavigator, NavigationActions } from 'react-navigation';
class HomeScreen extends React.Component {
static navigationOptions = { tabBarLabel: 'Home!' };
render() {
console.log('Home', this.props.navigation);
return (
<View style={styles.container}>
<Text>HomeScreen</Text>
<Text onPress={() => this.props.navigation.goDetail()}>Go to Detail</Text>
</View>
);
}
}
class DetailScreen extends …
```
=> Pass getCustomActionCreators to StackRouter

src/routers/DrawerRouter.js, src/routers/__tests__/Routers-test.js
The drawer-closing logic was too aggressive. This change makes sure that the drawer will close when any navigation happens, but not when params of child routes change
Fixes https://github.com/react-navigation/react-navigation/issues/4342
=> Improve DrawerRouter logic to close drawer

.eslintrc, examples/NavigationPlayground/js/SimpleStack.js, src/views/Transitioner.js
The transitioner should not always perform an animation on state change. Instead, we should check if the navigation state is requesting a transition with isTransitioning. If not, we follow a similar codepath to transitioning, without any animation. This will still call the transition hooks in the props, so its unlikely to break things.
fixes #4178
=> Transitioner: Fix instantaneous transitions

src/routers/StackRouter.js, src/routers/__tests__/StackRouter-test.js
When navigating back in the stack, there was a condition where `isTransitioning` should have been set. This resulted in a broken transition, as reported in https://github.com/react-navigation/react-navigation/issues/4367
=> Fix stack router state change without isTransitioning change

src/navigators/createNavigator.js
- https://github.com/react-navigation/react-navigation/issues/4412
- https://github.com/react-navigation/react-navigation/issues/4289
- Try NavigationPlayground to verify that there are no regressions.
- Replace App.js in NavigationPlayground with this example: [tabs example](https://gist.github.com/brentvatne/f85975f8ac86c21648390204e0bed2f3). Notice that when you switch tabs it doesn't re-render other tabs unnecessarily. You can replace this with a stack navigator and notice that only the new screen being pushed is rendered.
=> Cache descriptors in createNavigator

src/views/StackView/StackViewLayout.js
**Motivation**
Fix a bug that would occur when trying to swipe to go back. The `index` variable was not defined in the `onPanResponderTerminate` function.
See screenshot below:
=> Fix swipe to go back by providing the index

examples/ReduxExample/src/navigators/AppNavigator.js
Use createStackNavigator instead of [deprecated StackNavigator](https://github.com/react-navigation/react-navigation/blob/5467f0e22d0cdcd3c7c64d7280ddc13eec6f3b28/src/react-navigation.js#L21) to create navigator component.
Solves issue https://github.com/react-navigation/react-navigation/issues/4134 for [v2](https://github.com/react-navigation/react-navigation/blob/5467f0e22d0cdcd3c7c64d7280ddc13eec6f3b28/package.json#L3).
=> Update deprecated StackNavigator usage in Redux example

README.md
Use the same casing (camel case) as in the README's title for the License section.
=> Use consistent naming in README

flow/react-navigation.js
Current types give an error. Check this [Flow-annotated code snippet](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBcwAlAUwEMBjQgGjAG8wAFAV3zIGE5c4A7Mn2IBfMFHw8wAcg7VCUgNzpCATxxkwAOQoA3DAHMKhDPwDKVDoO58oBgDwB5HMf4BnAHxgAvKjBgAPmBOLnyuvgFgABSRDOF+fny6BkYmfABcWkmGIeaWfMwSOHbaetmpJHCshGTutHHxrhZkggVwOK4ZDMJ18fGJpSn8wakdQc4jPfHCAJTensNu00qoqupgAKI6goQAKmoaPn6BUggYMDAAYnBUrK5S4ccAJhiPVzd3D9Kn5wBCMOz3I7SZ6PP4Az5SOSpRTKfaZAYhTbbZgUFTwCiPbyMcKrMgZJFCPbqSZQ-gZErJEIAQRoqUmrkIRjx8MpqVMjOqkxgFAZ7KZGQA-BSymYOWQ6sJlriWSK+ATCJwKOcAEbUADWWMi4RwqPRj3JWUGcq2QhRaLgGNQsy8nh0cBeUrhwqN8tMrGVjXwGHG-CxsT8HCwcC2GUi1tt9seEsda2dIRR+AoWFcfvCAG01WQVBkGV6+PoALoZLAYAAeZCjqElsNjhpCcbINJCfv8OP2GSkcdSwE0VIAagBJADiVJ26ykkwkVTI2iwzNzGHzkx1ieTAoNCNSCaTrjq4WAwDAOwAFhpSXwwIQ4GB8KwL4vXC8NIRT2BXO6ALRT6r4cLn9cykaDZNnS6B+J …
=> [flow] Fix NavigationScreenComponent's navigationOptions

src/__tests__/getNavigation-test.js, src/createNavigationContainer.js, src/getChildNavigation.js, src/getChildRouter.js, src/getNavigation.js, src/navigators/createNavigator.js, src/routers/StackRouter.js, src/routers/SwitchRouter.js
This fixes our descriptor caching issue, and unblocks explicit nested navigation options.
As a side effect, the following APIs are introduced to the navigation prop:
- navigation.getChildNavigation(routeKey) , which is useful for explicitly getting children config info
- navigation.router, access to the static router
And routers have a new way to statically expose children behavior. This is particularly important for getChildNavigation to access custom action creators on the child router.
- router.childRouters[routeName] , an optional way to access the children routers directly. If childRouters are not provided in a router, we will fall back on getComponentForRouteName(routeName).router, which is the previous external API for this (although it may be slower because it will require the …
=> Refactor, move child navigation to navigation prop

src/navigators/createStackNavigator.js, src/views/StackView/StackView.js, src/views/StackView/StackViewLayout.js, src/views/__tests__/Transitioner-test.js
When use `createStackNavigator`, old version React will warning, look image below  
**In debugger**  
**In Simulator**  
It's uncomfortable.
Look at this comment  
https://github.com/react-navigation/react-navigation/issues/2019#issuecomment-347547140  
Because the import writing is
```javascript
import * as React from 'react'
```
In this writing, babel will traverse all property in package(react etc.), so the getter in react will be call, and then, the deprecated warning will be executed.  
search the keywords in **react-navigation** project.
Only four files contains this writing, and these four files is created 3 months ago.   
So I think it's a personal writing, but this writing cause the warnings.
=> Change 'React' import writing, Prevent warnings in old version React

src/views/StackView/StackView.js
Fix bug https://github.com/react-navigation/react-navigation/issues/4458
=> Extract correct property for onTransitionEnd

src/__tests__/getNavigation-test.js, src/getChildNavigation.js
Issues like https://github.com/react-navigation/react-navigation/issues/4440 where you expected to be able to access the same action creators from the `navigation` prop in `navigationOptions` but cannot are unintuitive and likely to cause confusion for most people at some point.
In #4440 we have a stack navigator with a drawer navigator inside of it, and we set
navigationOptions with drawer.navigationOptions. There are three navigation objects
to think about:
(1) inside stack view
(2) child routes of stack view (drawer view is one)
(3) child routes of drawer view
We want the navigation prop in (2) to have access to the action creators for the drawer router.
So we want the child navigation prop where the child is a navigator to include the action creators
from the router.
In (1) the stack …
=> Make the actions available on the navigator navigation prop the same as its children

examples/NavigationPlayground/yarn.lock, examples/ReduxExample/app.json, examples/ReduxExample/package.json, examples/ReduxExample/src/navigators/AppNavigator.js, examples/ReduxExample/yarn.lock, src/react-navigation.js
This unblocks the fixing of react-navigation-redux-helpers to unbreak redux support in 2.3
https://github.com/react-navigation/react-navigation-redux-helpers/pull/37
All redux users will need to change their code to reflect the changes made here to `ReduxExample/AppNavigator`
=> Export getNavigation as public API, test redux

flow/react-navigation.js, src/react-navigation.js, src/react-navigation.web.js
`react-navigation-redux-helpers` no longer needs `getNavigationActionCreators` to be exported, and it's best not to export things we don't want to support the import of.
Since support is already broken for anybody using a version of `react-navigation-redux-helpers` that calls `getNavigationActionCreators` in master, this PR should not break anybody's setup. It'll just replace a fatal error with another one.
=> Revert "Export getNavigationActionCreators (#4258)"

src/routers/StackRouter.js, src/routers/__tests__/StackRouter-test.js
This bug wasnt apparent until we fixed the transitioner to fully respect isTransitioning. The router did not handle this properly until now.
Enhanced a test to verify this in the future
=> Fix isTransitioning on nested navigate

src/createNavigationContainer.js
Creating a new error makes the stack unreadable in sentry, because the stack is stringified when the error is cast to string to create a new one.
Is there another reason to do that ?
Alternative possible solution would be to add a method to be able to handle the error ourselves ?
=>  createNavigationContainer: rethrow the error instead of creating a new one

CHANGELOG.md, src/StateUtils.js, src/routers/StackRouter.js
This fixes https://github.com/react-navigation/react-navigation/issues/4185. It seems like it was an oversight to only try to, uh, bubble down actions to the child router of the active screen in the stack.
I ran the example from https://github.com/react-navigation/react-navigation/issues/4185 against this and it fixed the issue.
=> Delegate to child routers for more than just the top screen in the stack

src/PlatformHelpers.native.js, src/PlatformHelpers.web.js, src/createNavigationContainer.js, src/views/Header/Header.js
This hack had previously been required for old versions of react native and react-native-web
Now it just causes troubles because new versions of react-native-web do not export `BackAndroid` at all
=> Clean up PlatformHelpers

src/getChildNavigation.js
Provide protection against calling isFocused on the navigation prop of a route that is no longer in the navigation state
Fixes https://github.com/react-navigation/react-navigation/issues/4610
=> Avoid crash when calling isFocused on old route

src/routers/StackRouter.js, src/routers/__tests__/StackRouter-test.js
Stack router had some aggressive logic for deferring to inactive child routers. The child router behavior should come after all of the appropriate stack actions, with the exception of the active child router.
This was causing issues such as https://github.com/react-navigation/react-navigation/issues/4623 , where inactive tab navigators would handle the back action, and cause the stack to attempt to  pop back to it.
=> Fix stack router child router delegation priority

flow/react-navigation.js
React Native 0.56 introduces Flow 0.75, which makes it impossible to refine `NavigationRoute` based on the presence of `index` or `routes` properties.
This PR turns `NavigationStateRoute` and `NavigationLeafRoute` into exact types, which addresses this issue.
=> [flow] Make NavigationRoute types exact

CHANGELOG.md, src/views/Header/Header.js
As explained in issue #4695, setting `headerTransparent` still leaves a borderBottom of width 0.5 and color of `#A7A7AA`. This PR aims to fix that issue.
Before: 
After:
=> Set borderBottom to transparent and of size 0 if headerTransparent is true

src/routers/StackRouter.js, src/routers/SwitchRouter.js, src/routers/__tests__/PathHandling-test.js, src/routers/__tests__/StackRouter-test.js, src/routers/pathUtils.js
This fixes issues with deep linking and fully tests the differences between `path: ''` and `path: null`. Now we have a clear behavior to document. Empty string matches empty paths, and null path will let the child router handle paths at the same level
Also it makes sure that params are not duplicated between path and query when they are serialized with getPathAndParamsForState
=> Improve empty path and param handling

src/navigators/createNavigator.js, src/views/ScenesReducer.js
There is no need to keep a descriptor around in memory after the route no longer exists.
=> Cleanup unused descriptors 

CHANGELOG.md, examples/NavigationPlayground/js/SimpleStack.js, src/views/Header/Header.js, src/views/Header/HeaderBackButton.js, src/views/Header/HeaderTitle.js, src/views/StackView/StackViewLayout.js
https://github.com/react-navigation/react-navigation/issues/4092
- `headerLayoutPreset: 'center' | 'left'` to provide an easy solution for [questions like this](https://github.com/react-navigation/react-navigation/issues/4615).
- `headerBackTitleEnabled` - this configuration option for stack navigator allows you to force back button titles to either be rendered or not (if you disagree with defaults for your platform and layout preset).
- Also fixes https://github.com/react-navigation/react-navigation/issues/3955
=> Add headerLayoutPreset option to stack

CHANGELOG.md, src/views/StackView/StackViewLayout.js
The header transition preset check in `StackViewLayout` contains a typo, checking for `uitkit` instead of `uikit`.
=> Fix typo in header transition preset check (uitkit -> uikit)

CHANGELOG.md, src/react-navigation.js, src/views/StackView/StackViewTransitionConfigs.js
Export `StackViewTransitionConfigs` is very handy for custom `transitionConfig` in navigator options to reuse the default ones.
Done
Export `StackViewTransitionConfigs` to allow you to extend default config in custom transition configs.
[CHANGELOG.md](https://github.com/react-navigation/react-navigation/blob/master/CHANGELOG.md#unreleased)
=> Export StackViewTransitionConfigs

src/routers/__tests__/PathHandling-test.js, src/routers/pathUtils.js
Fixes the deeplink bug where, if you specified `null` in the routerOptions `paths`, the logic would actually fall back to the `path` specified on the route. This was happening because the logic was `option1 || option2`, and the value we wanted to define with option1 was falsey.
This was especially confusing for me at first because the fallback option is likely to be undefined, and then the path would be set as the default of the `routeName`.
By the way, this is related to https://github.com/react-navigation/react-navigation/pull/4671 and https://github.com/react-navigation/react-navigation/pull/1811, where it became possible to pass `null` as the path for the child router to handle the whole path. Thanks so much for this deeplinking work! It was hard to find, though, so what is the best …
=> Fixes bug where `null` doesn't work in routerOptions `paths` object for deeplinking

package.json
This backports https://github.com/react-navigation/react-navigation/pull/4810 to the 1.x branch.
=> Backport react-native-safe-area-view bump

CHANGELOG.md, package.json, yarn.lock
Because `create-react-context` updated its license from MIT (read: Open
Source) to a more-restrictive, non-Open Source license without
appropriately bumping its major version in violation of semver, the
`create-react-context` version within `react-navigation` necessarily
needs to have its version pinned to a version of `create-react-context`
before the license change.
v0.2.2 is the most recent version of `create-react-context` that still
retains an Open Source license.
Note: Another solution to this would be to require `react` `16.3.x` or
higher, which includes the official `React.createContext` API without
need to rely on a third-party library.
Closes #4934
=> Pin create-react-context at v0.2.2

flow/react-navigation.js
As specified in the [official docs](https://reactnavigation.org/docs/en/stack-navigator.html#stacknavigatorconfig), `StackNavigatorConfig` allows one to optionally set `headerLayoutPreset` to either `left` or `center`, but the current flow libdef doesn't reflect that so `const stack = createStackNavigator({}, { headerLayoutPreset: "center" });` raises a flow error.
`const stack = createStackNavigator({}, { headerLayoutPreset: "center" });` should no longer raise error.
=> [flow] Fix missing headerLayoutPreset option in StackNavigatorConfig

flow/react-navigation.js
There are types that I'm expecting to be available (based on docs and source code) but aren't present, so I get flow errors in my code.
``` js
import React from 'react';
import { createStackNavigator } from 'react-navigation';
import type { NavigationAction, NavigationState } from 'react-navigation';
const StackNavigator = createStackNavigator({ /* ... */ }, {
headerLayoutPreset: 'center',    // <---- Flow Error
headerBackTitleVisible: false    // <---- Flow Error
});
function handleNavigationStateChange(
prevState: NavigationState,
currentState: NavigationState,
action: NavigationAction
) {
switch (action.type) {
case 'Navigation/DRAWER_OPENED':    // <---- Flow Error
// do something...
break;
case …
```
=> Add missing types

CHANGELOG.md, package.json
React Native 0.57 now adds a yellowbox warning due to this package, bumping to solve
=> Bump Safe-Area-View to remove circular dependency.

CHANGELOG.md, flow/react-navigation.js
The typings do not include `dangerouslyGetParent()` on the navigation prop. One thing I'm not sure about is the asterisk.
this reminds me this function is not properly documented (will do)
flow does not complain locally
done - Add an entry under the "Unreleased" heading in [CHANGELOG.md](https://github.com/react-navigation/react-navigation/blob/master/CHANGELOG.md#unreleased) which explains your change.
=> add dangerouslyGetParent() to flow typings

src/navigators/DrawerNavigator.js, src/navigators/StackNavigator.js, src/navigators/SwitchNavigator.js, src/navigators/TabNavigator.js
Fix https://github.com/aksonov/react-native-router-flux/issues/3124
Release builds fails without these changes
No more errors
Simple letter put from uppercase to lowercase
Not required I guess
=> Fix issue undefined is not an object evaluating r.default

src/routers/StackRouter.js, src/routers/SwitchRouter.js, src/routers/__tests__/PathHandling-test.js, src/routers/pathUtils.js
Since `react-navigation@2.7.0`, the router lost a bit of the magic and to be able to deep link to a nested path we have to append each `routeName` we navigate through or make it explicit that paths are allowed to flow through with a `null` path, because routeName is used as default path.
So, I add `disableRouteNamePaths` to the router configs which is affecting the behavior here:
https://github.com/react-navigation/react-navigation/blob/73c76f1e4bbb015581eaae79a22e0076615ef392/src/routers/pathUtils.js#L86-L89
I find it more flexible than:
```javascript
const tabs = {
ScreenA: screenGenerator('Screen A'),
ScreenB: StackNavigator,
};
const TabNavigator = createTabNavigator(tabs, {
paths: Object.keys(tabs).reduce((paths, path) => ({ ...paths, [path]: null }), {}),
});
```
I've added tests …
=> Add disableRouteNamePaths option to router configs

flow/react-navigation.js
Two of these are recent property additions, and the other is a recent change to the signature for the `transitionConfig` function.
=> [flow] Update StackViewConfig to match recent changes

.release-it.json, package.json, yarn.lock
Currently doing a new release is a tedious task. You need to:
- Increment the version manually
- Create a git tag
- Update changelog
- Publish a new release on GitHub with the changelog
- Publish to npm
This PR aims to add `release-it`, which will automate all of it. You just have to run `yarn release` and it'll automatically do all of the above things.
I've used `conventional-changelog-cli` to create the changelog from the commit history. It assumes that we use the angular convention for the commits, for example:
- `fix: fixes some bug`
- `feat: adds some new feature`
- `chore: some setup stuff`
- `test: adds some tests`
- `breaking: introduces a breaking change`
Following this convention will allow the tool …
=> chore: use release-it for automated release

flow/react-navigation.js
As of 2.18 we seem to be okay returning `null` here.
=> [flow] Fix type of getCurrentNavigation

flow/react-navigation.js
Fix Flow error:
```js
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ flow-typed/npm/react-navigation_v2.x.x.js:539:16
ParamName [1] is incompatible with string [2].
[2]  72│     [key: string]: mixed,
:
536│       eventName: string,
537│       callback: NavigationEventCallback
538│     ) => NavigationEventSubscription,
[1] 539│     getParam: <ParamName>(
540│       paramName: ParamName,
541│       fallback?: $ElementType<
542│         $PropertyType<
```
Before this change, you should get the error above when passing `NavigationStateRoute` to `NavigationScreenProp`. This PR should fix that.
```js
type Props = {
navigation: NavigationScreenProp<NavigationStateRoute>,
};
```
This PR was …
=> [flow-typed] - Fix error "ParamName [1] is incompatible with string [2]."

flow/react-navigation.js
1. `navigationOptions` in `RouteConfig`s is now `defaultNavigationOptions`
2. `create*Navigator` no longer return a container, they return a navigator
3. Introducing `createAppContainer`
Let me know if I missed anything!
Closes #4722 by including https://github.com/flow-typed/flow-typed/pull/2522
=> [flow] Update libdef for 3.0

CHANGELOG.md, NavigationTestUtils.js
For App-test.js on expo.
I updated react-navigation to v3, and want to test navigation, but error was occured.  
So replace it.
Demonstrate the code is solid. Example: the exact commands you ran and their output, screenshots / videos if the pull request changes UI.
Lint-Staged handled
=> ./src/createNavigationContainer -> @react-navigation/native/src/createAppContainer on NavigationTestUtils.js

CHANGELOG.md, package.json, src/routers/__tests__/validateRouteConfigMap-test.js, src/routers/getScreenForRouteName.js, src/routers/validateRouteConfigMap.js, yarn.lock
Until 3.x is not release as stable, it is good to support components with forwardRef in createStackNavigator.
this is based on this commit https://github.com/react-navigation/react-navigation-core/commit/e4857b6c24ffa8c657887250954490ce1d3fe925
I've added a test using React.forwardRef when validating route configs.
Lint-Staged handled
=> feat(ref): use react-is to enable forwardRef on 2.x, fix #5193

examples/NavigationPlayground/package.json
Solves https://github.com/react-navigation/react-navigation/issues/5293
=> Fix for NavigationPlayground red box (duplicate native module)

CHANGELOG.md, flow/react-navigation.js
Currently if you wrap a component that uses `defaultProps` with `withNavigation` or `withNavigationFocus` the `defaultProps` will become non-optional.
This PR updates the flow definition for these higher order components to use [`React.ElementConfig`](https://flow.org/en/docs/react/types/#toc-react-elementconfig) which correctly preserves the optionality of `defaultProps`.
These changes aren't required on flow >= 0.89, but most people aren't running the latest version because React Native usually lags behind by a few versions.
Here's a [before/after example](https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgF1AFSgCGAzqAEoCmxAxvpNrGqAOTY32sDcykArgDt6KWINDwUuABYA5YgDcUAc2K5RggGKxa-UrKrwAPAAUmGUgC5QAbwC+AGlABhZlkFVBuACoBPDFTW1HS4ACSumGKePv5UpuakAHyJABSIoC5uUV7WEe7RfgGIAJRBnGF52TEBRqEAIiiQkEbB …
=> Update flow definition for withNavigation and withNavigationFocus to support defaultProps

flow/react-navigation.js
Fix minor typo: `transtion` => `transition`.
=> Fix typo "transtion" => "transition"

examples/NavigationPlayground/js/CustomTabUI.js
While browsing the examples, especially around the custom tab bar options, one obvious typo seems to have sneaked itself into the code. This pull-request fixes that wrong spelling.
No test-plan, it's some already existing example.
Did that, nothing bad was found.
No changelog required
=> fixed typo in Custom Tab UI example

CHANGELOG.md, package.json
Based on the changelog of the version 3.4.0, TS definitions are now included in the project but the definition file is missing from release package. 
Releasing a new version.
Nothing changed.
Done
=> Fix missing ts def

typescript/react-navigation.d.ts
`NavigationContext` is exported but not part of the exported types. 
n/a
Look around. Match the style of the rest of the codebase. Run `yarn format` before committing.
Add an entry under the "Unreleased" heading in [CHANGELOG.md](https://github.com/react-navigation/react-navigation/blob/master/CHANGELOG.md#unreleased) which explains your change.
=> fix: export NavigationContext in types

CHANGELOG.md, flow/react-navigation.js, typescript/react-navigation.d.ts
Type definitions for `TabBarBottom` should be `BottomTabBar`.
https://github.com/react-navigation/react-navigation/issues/5701
updated: ✅
=> Issue-5701: TabBarBottom -> BottomTabBar in type definitions

CHANGELOG.md, typescript/react-navigation.d.ts
The props used in `tabBarIcon` and `tabBarLabel` are not exported, this PR fixes it.
=> [TypeScript] export TabBarIconProps and TabBarLabelProps

CHANGELOG.md, typescript/react-navigation.d.ts
The props used in `drawerIcon` and `drawerLabel` are not exported, this PR fixes it.
=> [TypeScript] Export DrawerIconProps and DrawerLabelProps

CHANGELOG.md, typescript/react-navigation.d.ts
The `screenProps` prop doesn't have a clear type (sometimes it's typed with `object`, other times with `any` and others with ` { [key: string]: any }` ).
This PR creates and exports a custom `ScreenProps` type for better consistency.
=> [TypeScript] Add ScreenProps type and export it

examples/NavigationPlayground/app/SwitchWithStacks.tsx
with:
await AsyncStorage.clear();
I'm getting this in ios:
unhandled promise rejection failed to delete storage directory
found this:
https://stackoverflow.com/questions/46736268/react-native-asyncstorage-clear-is-failing-on-ios
switched to use this instead:
await AsyncStorage.getAllKeys().then(AsyncStorage.multiRemove)
but that causes unhandled promise rejection in android.
this is working:
Platform.OS === 'ios' ? await AsyncStorage.getAllKeys().then(AsyncStorage.multiRemove) : await AsyncStorage.clear()
In: "Switch between routes" item in example app
Example does not sign out:
unhandled promise rejection failed to delete storage directory
I tested the app in both android and ios
I am happy to reformat per any …
=> unhandled promise rejection failed to delete storage directory

CHANGELOG.md, typescript/react-navigation.d.ts
The type used in `initialLayout` is not exported, this PR fixes it.
=> [TypeScript] Export InitialLayout type

flow/react-navigation.js
This PR adds a missing props type in flow
The missing prop is `getButtonComponent`
=> Adding missing getButtonComponent props to flow

flow/react-navigation.js
1. Add `isTransitioning` property to `NavigationState` so custom navigators can inspect it.
2. Make `StackNavigatorConfig` a `$Shape`, which is correct since none of the properties are required.
3. Add the `descriptor` property to `NavigationScene` and export `NavigationDescriptor`.
=> [flow] Support custom navigators using Transitioner

flow/react-navigation.js
1. `TabBarTop` is `MaterialTopTabBar` now
2. `MaterialTopTabBar` does not have a `getButtonComponent` prop (accidentally added in #5648)
3. `BottomTabBar`'s `getButtonComponent` prop is a `React.Component`, not a `React.Node`
=> [flow] Fix TabBar types

CHANGELOG.md, typescript/react-navigation.d.ts
`NavigationTabRouterConfigBase` as a type  made no sense for `navigationOtions` updated it  appropriately for the two tabNavigators.
=> Improved Type Definition for Navigator navigationOptions.

CHANGELOG.md, typescript/react-navigation.d.ts
`enableURLHandling` was missing from the Typescript definitions. Added it in with a short description
Fixes https://github.com/react-navigation/react-navigation/issues/5793
=> [Typescript] Add type for 'enableURLHandling'

flow/react-navigation.js
Changes:
1. We can now type React components with static members as `React.ComponentType` (instead of requiring the `StatelessFunctionalComponent`) hack.
2. We can now type-parameterize React components on all of their props, instead of just the ones we care about. Not sure why this wasn't previously. Note: this is a breaking change, in the sense that people's parameterization of `NavigationScreenComponent`, `NavigationNavigator`, and `NavigationContainer` may need to change.
3. The order of object-type-spread in the `getParam` definition has been switched. It was giving errors with the old order.
4. Avoid recursive type inference `NavigationScreenProp`. This was yielding an "*** Recursion limit exceeded ***" error, which was rather difficult to debug. We can just use a `NavigationState` …
=> [flow] Update for Flow 0.92

CHANGELOG.md, typescript/react-navigation.d.ts
Remove `createTabNavigator` out of ts definition in v3 since it is removed in the source
=> chore: remove createTabNavigator out of ts definition

CHANGELOG.md, typescript/react-navigation.d.ts
Noticed that some definitions were missing when using `drawerType`: https://reactnavigation.org/docs/en/drawer-navigator.html#drawernavigatorconfig
First PR here, let me know if I need to change anything :)
=> Add missing type definitions for DrawerNavigatorConfig

flow/react-navigation.js
In my last PR I flipped the order of these around to fix an error, but turns out that was just crippling the type. The correct solution here, to guarantee that the `$PropertyType` won't error if its type parameter don't have the property, is to use an unsealed object type.
Some additional context in discussion on #5806.
=> [flow] Fix NavigationScreenProp.getParam type

typescript/react-navigation.d.ts
I just noticed that `NavigationInjectedProps` is defined the same way twice so I think we can remove one of them.
Didn't know if this warranted an entry in the changelog but let me know if it does and I'll gladly add it!
=> Removes duplicate NavigationInjectedProps export

CHANGELOG.md, typescript/react-navigation.d.ts
The export of type `TabBarTop` does not match the actual export of `MaterialTopTabBar`.
This fixes the issue where <TabBarTop {...props} /> would fail as it wasn't being exported.
(It is basically #5800 for typescript)
=> [Typescript] `TabBarTop` is `MaterialTopTabBar` now

CHANGELOG.md, typescript/react-navigation.d.ts
In react-navigation-tabs, I can see in the flow typings there using `getLabelText` instead of the ts def showing `getLabel`
=> correct getLabel to getLabelText

CHANGELOG.md, typescript/react-navigation.d.ts
`safeAreaInset` is [documented](https://reactnavigation.org/docs/en/bottom-tab-navigator.html#bottomtabnavigatorconfig), but missing from the typescript definition.
Add an entry under the "Unreleased" heading in [CHANGELOG.md](https://github.com/react-navigation/react-navigation/blob/master/CHANGELOG.md#unreleased) which explains your change.
=> Add safeAreaInset type to BottomTabBarProps

CHANGELOG.md, typescript/react-navigation.d.ts
I removed some old export such as `StackNavigator`, `TabNavigator`, `SwitchNavigator`. Also, this typedef updates will help me to fulfill this issue: https://github.com/react-navigation/animated-switch/issues/4 since I will need the typedefs for `SceneView` and `SwitchRouter`
Tried to export those newly added in my own personal project to see if it is compatible
=> remove old exports and add export for SceneView and SwitchRouter

CHANGELOG.md, flow/react-navigation.js
Fixes #5917
Both `cardShadowEnabled` and `cardOverlayEnabled` are supported in `StackNavigatorConfig`. This updates the type defs in the react-navigation repo to match. Note that the typescript defs already contain these fields.
Import new typedefs into flow project and specify `cardShadowEnabled` in stack navigator options. Run flow, ensure there are no errors.
=> Add cardShadowEnabled and cardOverlayEnabled to NavigationStackViewConfig flow type

typescript/react-navigation.d.ts
Stop TypeScript compiler errors for usage of `reset` which is described at:
<https://reactnavigation.org/docs/en/navigation-prop.html#reset>
I've been using this in a real world project and it stopped the tsc errors when adding this change.
=> fix: add reset to navigation screen prop TypeScript def

flow/react-navigation.js, typescript/react-navigation.d.ts
- Typing is wrong. https://github.com/react-navigation/core/blob/master/src/routers/StackActions.js#L13 doesn't require an options arg as it just spread the args, https://github.com/react-navigation/core/blob/94c6ffa4e477e43533ed388e770e5144179cc83b/src/routers/StackRouter.js#L400-L418 doesn't try to access any properties of objects that may be undefined, and the example at https://reactnavigation.org/docs/en/stack-actions.html#poptotop shows it with no args.
- Added `key` to flow type to make it consistent with TS
None. This is trivial. I'm not sure if a CI test/lint would cover this.
Should be good.
>Add an entry under the "Unreleased" heading in [CHANGELOG.md](https://github.com/react-navigation/react-navigation/blob/master/CHANGELOG.md#unreleased) which explains your change.
I don't …
=> fix: update StackActions.popToTop type to make options arg optional

CHANGELOG.md, typescript/react-navigation.d.ts
- `NavigationScreenProp<NavigationRoute>` is the type of `navigation` property which contains `state` and such. This is not applicable to `navigationOptions` at all.
- To be used for `static navigationOptions` in a `NavigationScreenComponent`.
```javascript
static navigationOptions = ({navigationOptions, navigation}) => {} // navigationOptions from the function argument is wrongly typed. It currently contains the same type as navigation prop.
```
Typings change.
Should be good.
- Fix `navigationOptions` type from `NavigationScreenProp<NavigationRoute>` to `NavigationScreenConfig<Options>`.
Add an entry under the "Unreleased" heading in …
=> fix: fix navigationOptions type in NavigationScreenConfig<Options>

CHANGELOG.md, typescript/react-navigation.d.ts
Stop TypeScript compiler errors for usage of `headerTitleContainerStyle` which is described at:
https://reactnavigation.org/docs/en/headers.html
I've been using this in a real world project and it stopped the tsc errors when adding this change.
=> fix: add headerTitleContainerStyle to NavigationStackScreenOptions type

CHANGELOG.md, flow/react-navigation.js, typescript/react-navigation.d.ts
Using method isFirstRouteInParent in typescript or flow.
=> fix: add missing isFirstRouteInParent type in typescript and flow

CHANGELOG.md, flow/react-navigation.js, typescript/react-navigation.d.ts
Using `backTitleVisible` and `disabled` props in `HeaderBackButton` component both in typescript and flow.
=> fix: add missing backTitleVisible for typescript, disabled and backTitleVisible for flow definitions in type HeaderBackButtonProps

typescript/react-navigation.d.ts
Without this the following code wont compile:
```typescript
navigation.dispatch(SwitchActions.jumpTo({ routeName: 'MyCoolRoute' }))
```
=> Add NavigationSwitchAction to NavigationAction typescript

typescript/react-navigation.d.ts
Unless I'm declaring the type of my Props wrong (I'm still new to Typescript), this change is required to prevent issues where no errors are thrown when accessing any properties on the "params" field in the NavigationState.
```ts
function MyScene(props: {
navigation: NavigationScreenProp<NavigationState, { userId: number }>
}) {
// Should warn about params being possibly undefined.
const { userId } = props.navigation.state.params;
// ...
}
```
=> Typescript: Mark "params" in NavigationState as possibly undefined

CHANGELOG.md, flow/react-navigation.js
These two types are missing entirely from the flow definition, while they're incomplete they at least prevent flow from complaining that they're not defined at all.
I decided against copying the `ScrollView` types from `react-native` as they're really quite complex and likely to fall out-of-sync with the implementation in `react-native`. So instead I'd recommend overriding the types when  consuming using something like:
```js
import {ScrollView as NativeScrollView} from 'react-native';
import {ScrollView as NavigationScrollView} from 'react-navigation';
const ScrollView: React.ComponentType<typeof NativeScrollView>) = NavigationScrollView;
```
=> Export NavigationContext and ScrollView in flow types

src/deprecations.js
fixes a typo from `react-navigation-drawe` -> `react-navigation-drawer`
N/A
N/A
=> fix(deprecations) typo in package name

README.md
Now that there is no longer a `CHANGELOG.md` file, this should address concerns of users who come to the Github repository looking for release notes.
=> Add Changelog information to README

example/README.md
I was trying to learn how to contribute to React Navigation and the docs at [https://reactnavigation.org/docs/en/contributing.html](https://reactnavigation.org/docs/en/contributing.html) referred to an example app with a README.md file giving instructions on how to run it. I later found out that this file was removed in d8130dd0d4bf3eb905f7aa67cd7f3b2f67ef6871. Could not find any reason why this was removed, so perhaps it was overlooked.
I definitely think it is essential, even if the commands are basic, to show exactly how to get the example app up and running.
I plan on updating the website docs if this PR is accepted.
Commands in file were run and still work
=> docs: add the readme back into example

typescript/react-navigation.d.ts
As mentioned in https://reactnavigation.org/docs/en/switch-actions.html
the param which's name is `key` of `SwitchActions.jumpTo()`  should be optional
There is something wrong with the type of NavigationJumpToActionPayload
Demonstrate the code is solid. Example: the exact commands you ran and their output, screenshots / videos if the pull request changes UI.
Look around. Match the style of the rest of the codebase. Run `yarn format` before committing.
Add an entry under the "Unreleased" heading in …
=> fix: fix the type of NavigationJumpToActionPayload

typescript/react-navigation.d.ts
As mentioned in https://reactnavigation.org/docs/en/navigation-actions.html#setparams 
the param which's name is key of NavigationActions.setParams() should be required
There is something wrong with the type of NavigationSetParamsActionPayload
Demonstrate the code is solid. Example: the exact commands you ran and their output, screenshots / videos if the pull request changes UI.
Look around. Match the style of the rest of the codebase. Run `yarn format` before committing.
Thanks.
=> fix: make params required in NavigationSetParamsActionPayload

typescript/react-navigation.d.ts
As mentioned in https://reactnavigation.org/docs/en/switch-actions.html#jumpto.
I removed the params of SwitchActions.jumpTo().
There is something wrong with the type of SwitchActions.jumpTo().
=> fix: remove params in NavigationJumpToAction

typescript/react-navigation.d.ts
We can type navigation params in component by writing something like this in component props declaration : 
``` ts
export interface SomeNavigationParams {
foo: string;
bar: number;
}
export interface Props {
navigation: NavigationScreenProp<any, SomeNavigationParams>;
}
``` 
But when we are navigating to this screen, we only call navigate method without any type checking.
``` ts
// Next line doesn't trigger ts error
this.props.navigation.navigate('MyRouteName', { foo: "foo", bar: "bar"})
``` 
By making navigate a generic method, we can type those params correctly
``` ts
import { SomeNavigationParams } from '@Screens/....../SomeScreen.types.ts'
......
// Next line triggers an error
this.props.navigation.navigate<SomeNavigationParams>('MyRouteName', { foo: "foo", bar: "bar"});
......
``` …
=> feat: allow navigation params to be typed in navigate method

typescript/react-navigation.d.ts
This code is actually throwing a type error because of a wrong type declaration with the action expecting to be only a `NavigationNavigateAction` while in reality any action can be dispatched not only the `navigate`.
```jsx
StackActions.replace({
routeName: 'MyRoute1',
// this action is throwing a type error
action: StackActions.push({
routeName: 'MyRoute2',
}),
}),
```
It's just a simple type fix, I edited it in the GitHub UI, I didn't run any test locally
=> fix: wrong type in react-navigation.d.ts

typescript/react-navigation.d.ts
This change allows for the following to be written:
```tsx
const TreatmentPlanDrawerItem = createStackNavigator(
{
Screen: {
screen: Screen,
// t is of type i18next.TFunction via the type casting below.
navigationOptions: ({ screenProps }) => ({
title: screenProps.t('title'),
})
},
} as NavigationRouteConfigMap<
NavigationStackOptions,
NavigationStackProp<NavigationRoute, any>,
{ t: i18next.TFunction }
>
);
```
Demonstrate the code is solid. Example: the exact commands you ran and their output, screenshots / videos if the pull request changes UI.
Make sure you test on both platforms if your change affects both …
=> feat: make `ScreenProps` parametrizable in TypeScript

packages/bottom-tabs/src/views/BottomTabBar.tsx
Issues #6740, #6799
**Summary**: when `keybordHidesTabBar` is true, the TabBar should **start visible**. (Assume keyboard is not shown initially)
Looks like a run-of-the-mill refactor typo introduced in commit 38a38b021a3764d3977e83fe6c2d2be115e03e56 during a refactor to `FunctionComponent` for `v5.0.0-alpha.26`.
Before: `Animated.Value(1)` - https://github.com/react-navigation/react-navigation/commit/38a38b021a3764d3977e83fe6c2d2be115e03e56#diff-01c572697c6280aebeef0ce66da6ac66L47
After: `Animated.Value(0)` - https://github.com/react-navigation/react-navigation/commit/38a38b021a3764d3977e83fe6c2d2be115e03e56#diff-01c572697c6280aebeef0ce66da6ac66R48
The rest of the initial state data stayed the same, and it doesn't look like any changes were made to the animated value's meaning (0 -> …
=> Fix `keyboardHidesTabBar` initialization typo

packages/core/src/StaticContainer.tsx, packages/core/src/__tests__/StaticContainer.test.tsx
- Memo check compared elements of `prevProps` to `nextProps` but failed to take new props into account.
- Fixed the logic and added a new test.
- Memoize a component and add a new prop. Memo returns previous result instead of re-rendering the component.
PS: I couldn't find a PR template, please let me know if I missed it. I'll update my description as per the template.
=> fix: static container memo check

packages/bottom-tabs/src/navigators/createBottomTabNavigator.tsx, packages/compat/src/createCompatNavigatorFactory.tsx, packages/compat/src/createSwitchNavigator.tsx, packages/core/src/SceneView.tsx, packages/core/src/Screen.tsx, packages/core/src/__tests__/useEventEmitter.test.tsx, packages/core/src/createNavigatorFactory.tsx, packages/core/src/types.tsx, packages/core/src/useDescriptors.tsx, packages/core/src/useEventEmitter.tsx, packages/core/src/useNavigationBuilder.tsx, packages/drawer/src/navigators/createDrawerNavigator.tsx, packages/material-bottom-tabs/src/navigators/createMaterialBottomTabNavigator.tsx, packages/material-top-tabs/src/navigators/createMaterialTopTabNavigator.tsx, packages/stack/src/navigators/createStackNavigator.tsx
This adds ability to listen to events from the component where the navigator is defined, even if the screen is not rendered.
```js
<Tabs.Screen
name="Chat"
component={Chat}
options={{ title: 'Chat' }}
listeners={{
tabPress: e => console.log('Tab press', e.target),
}}
/>
```
Closes #6756
=> feat: add ability add listeners with listeners prop

jest/setup.js
I ran a spellchecker over the code, this was the only spelling error I was able to find :)
=> fix typo: correcting spelling 'Supress' > 'Suppress'

example/src/Screens/LinkComponent.tsx, example/src/index.tsx, packages/native/src/Link.tsx, packages/native/src/index.tsx
Basic `Link` component which only supports React Native for now.
Usage:
```js
<Link to="Article" params={{ author: "Babel Fish" }}>
Go to article
</Link>
```
Custom component:
```js
<Link to="Article" params={{ author: "Babel Fish" }}>
{props => (
<Button {...props} mode="contained">
Go to article
</Button>
)}
</Link>
```
I'm not happy with the API for custom component right now. Ideally I'd want something like this:
```js
<Link
as={Button}
mode="contained"
to="Article"
params={{ author: "Babel Fish" }}
>
Go to article
</Link>
```
But it seems challenging to properly type-check this.
=> feat: add basic Link component in React Native

packages/stack/src/views/Header/HeaderTitle.tsx
the previously used fort weight of 500 would effectively be converted to `fontWeight: bold`. Because of https://github.com/facebook/react-native/pull/25341 that does not happen as of 0.61 - fontWeight 500 for roboto actually is the same as 400 in latest RN. Because of that the title font doesn't look right (to me at least 😄 ) - it certainly looks different than before.
this fixes the title appearance to look as customary (it's thicker than now, but not as thick as it used to be).
images: old behavior, master, my branch
<span>
</span>
=> fix: fix android header title font weight

packages/stack/src/views/Stack/Card.tsx
This will fix https://github.com/react-navigation/react-navigation/issues/6782
The problem here is that when we scroll back really fast, even though velocity is negative, `Math.abs(translation + velocity * gestureVelocityImpact)` will end up bigger than `distance / 2`.
I removed the `Math.abs`, I think it's not necessary. When `translation + velocity * gestureVelocityImpact` is negative, it's also < `distance / 2` and we should just close the screen.
=> fix: fix back gesture cancellation

packages/stack/src/types.tsx, packages/stack/src/views/Stack/Card.tsx, packages/stack/src/views/Stack/CardContainer.tsx, packages/stack/src/views/Stack/CardStack.tsx
I find it sometimes useful to define overlay renderer on my own. Eg. I needed to replace the background with BlurView and with this API I find it quite easy
=> feat: add an option to change use a custom card overlay

packages/stack/src/views/Stack/Card.tsx
Allow you to close Stack that has inverted gesture config using correct closing bool calculation.
=> fix: fix closing stack using inverted gesture.

packages/stack/src/views/Stack/Card.tsx
In this commit https://github.com/react-navigation/react-navigation/commit/f24d3a3461ee8a566c25ce7d13f31035b4be2691 we modified the `velocity` in inverted gesture, but since we also use this value in the closing animation, the change in that commit also introduced a new bug:
This PR fixes the issue by keeping the original velocity value.
=> fix: use the correct velocity value in closing animation

packages/stack/src/views/Stack/Card.tsx
This `pointerEvents='none'` was present in the View before the introduction of overlayRender.
Without it, all interactions are blocked for 1-2 seconds after closing the screen.
It can be found in diff here: https://github.com/react-navigation/react-navigation/pull/7809/files
=> fix: add pointerEvents=box-none to overlay View

packages/drawer/src/types.tsx, packages/drawer/src/views/Drawer.tsx, packages/drawer/src/views/DrawerView.tsx
Commit to fix this issue https://github.com/react-navigation/react-navigation/issues/6475#issuecomment-587539763
I added separate prop `closeDrawerOnTap` which is `true` by default to close drawer by tap even when `enableGesture` is `false`.
=> feat: add swipeEnabled option to disable swipe gesture in drawer

packages/stack/src/views/Stack/Card.tsx
https://github.com/react-navigation/react-navigation/issues/7897
=> fix: finish stack animation on CANCELLED event

packages/core/src/__tests__/getPathFromState.test.tsx, packages/core/src/getPathFromState.tsx
Added resolving pattern when there is no path specified for a route.
Added stripping `undefined` query params.
=> fix: handle no path property and undefined query params

packages/bottom-tabs/src/types.tsx
This PR fixes a typo in activeBackgroundColor's [description](https://github.com/react-navigation/react-navigation/blob/master/packages/bottom-tabs/src/types.tsx#L141) that was mentioned here #7827
=> docs: fixes typo

packages/compat/src/helpers.tsx
resolves #7956 
Not sure if this is the best fix, but I think this should resolve the problem. Maybe the better way is to give `{}` to `StackActions.pop` instead of `n`. But I'm not sure if people are already putting objects into `pop` (which they shouldn't, I guess).
=> fix: use 1 as default in compat pop action

packages/core/src/__tests__/index.test.tsx, packages/core/src/useNavigationBuilder.tsx
By default, params passed to nested navigators is used to initialize the navigator if it's not rendered already. The `initial` option would let the user control this behaviour. By specifying `initial: false`, it'll be possible to acheive the old behaviour of rendering the initial route of the stack before navigating to the new screen.
Example:
```js
navigation.navigate('Account', {
screen: 'Settings',
initial: false,
});
```
=> fix: add initial option for navigating to nested navigators

packages/stack/src/TransitionConfigs/CardStyleInterpolators.tsx
Because of the translateY moving the screen out to the bottom of view by 10 pt, these 10pt are hidden under the screen, or steal this size from the safe area. To avoid cutting elements, the size of the screen could be decreased by the `topOffset` using padding on the bottom. Fixes #7856
=> fix: ios presentation modal cuts the topOffset on the bottom

packages/drawer/src/views/Overlay.tsx
Moved `WebkitTapHighlightColor` out of `StyleSheet.create()`. We may want to remove this in favor of the global style (which is in the react-native-web reset). But that would assume this package is being used with `react-native-web`, which is probably fine.
=> fix: webkit style error in overlay

packages/stack/package.json
Fix peer warning with versions less than 1.0.0
=> fix: stack peer warnings

example/src/Screens/LinkComponent.tsx, example/src/index.tsx, packages/core/src/__tests__/index.test.tsx, packages/core/src/useNavigationBuilder.tsx, packages/native/src/Link.tsx, packages/native/src/LinkingContext.tsx, packages/native/src/NavigationContainer.tsx, packages/native/src/NavigationNativeContainer.tsx, packages/native/src/index.tsx, packages/native/src/types.tsx, packages/native/src/useLinkTo.tsx, packages/native/src/useLinking.native.tsx, packages/native/src/useLinking.tsx, packages/native/src/useThenable.tsx
The `Link` component can be used to navigate to URLs. On web, it'll use an `a` tag for proper accessibility. On React Native, it'll use a `Text`.
Example:
```js
<Link to="/feed/hot">Go to 🔥</Link>
```
Sometimes we might want more complex styling and more control over the behaviour, or navigate to a URL programmatically. The `useLinkTo` hook can be used for that.
Example:
```js
function LinkButton({ to, ...rest }) {
const linkTo = useLinkTo();
return (
<Button
{...rest}
href={to}
onPress={(e) => {
e.preventDefault();
linkTo(to);
}}
/>
);
}
```
=> feat: add Link component as useLinkTo hook for navigating to links

example/src/Screens/BottomTabs.tsx, packages/bottom-tabs/src/types.tsx, packages/bottom-tabs/src/views/BottomTabBar.tsx, packages/bottom-tabs/src/views/BottomTabItem.tsx, packages/core/src/types.tsx, packages/core/src/useNavigationCache.tsx, packages/core/src/useNavigationHelpers.tsx, packages/drawer/src/views/DrawerItem.tsx, packages/drawer/src/views/DrawerItemList.tsx, packages/native/src/Link.tsx, packages/native/src/LinkingContext.tsx, packages/native/src/NavigationContainer.tsx, packages/native/src/index.tsx, packages/native/src/useLinkBuilder.tsx, packages/native/src/useLinkTo.tsx
We need to be able to create links from a navigate action to have accessible links in the built-in components such as drawer and tabs.
=> feat: add `useLinkBuilder` hook to build links

packages/core/src/__tests__/getStateFromPath.test.tsx, packages/core/src/getStateFromPath.tsx
Changed the matching to rely on the equality of all of the segments of the pattern rather than on the regex.
Added choosing the more exhaustive configs first.
=> fix: matching paths

packages/core/src/utils/docsUrl.ts, packages/react-navigation/src/utils/docsUrl.js
This PRs fixes the docs URLs shown on some warns to guide us to the right path on docs, following it you should get stuck here:
With this PR, we can reach the URL for the v4 documentation, since v5 is out.
=> [v4.x] fix: change old docUrl to new docUrl due v5

packages/drawer/src/views/Drawer.tsx, packages/drawer/src/views/ResourceSavingScene.tsx, packages/stack/src/views/Stack/Card.tsx, packages/stack/src/views/Stack/CardContainer.tsx, packages/stack/src/views/Stack/CardSheet.tsx, packages/stack/src/views/Stack/CardStack.tsx, packages/stack/src/views/Stack/StackView.tsx
This commit adds a check to detect if the screen content fills the available body, and if yes, then it adjusts the styles so that scrolling triggers a scroll on the body which hides the address bar in browser.
Tested on Safari in iOS and Chrome on Android.
This behavior can be overridden by the user by specifying `cardStyle: { flex: 1 }`, which will keep both the header and the address bar always visible.
=> fix: make sure the address bar hides when scrolling on web

packages/native/src/useLinking.tsx, packages/native/src/useThenable.tsx
Before this change, the typings for `getInitialState` got very... _interesting_ 😁 
```ts
export default function useLinking(ref: React.RefObject<NavigationContainerRef>, { enabled, config, getStateFromPath, getPathFromState, }: LinkingOptions): {
getInitialState: () => {
then: (callback: (state: (Partial<Pick<NavigationState, "index" | "history">> & {
stale?: true | undefined;
type?: string | undefined;
routes: (Pick<import("@react-navigation/core").Route<string>, "name" | "params"> & {
key?: string | undefined;
state?: import("@react-navigation/core").InitialState | undefined;
})[];
} & {
state?: (Partial<Pick<NavigationState, "index" | "history">> & {
stale?: true | undefined;
type?: string | undefined;
routes: (Pick<import("@react-navigation/core").Route<string>, "name" | "params"> & { …
```
=> fix: return a promise-like from getInitialState

packages/stack/src/TransitionConfigs/TransitionSpecs.tsx
When using the stack navigator on iOS, it takes a (too) long time before the  `didFocus` and stack `onTransitionEnd` lifecycle events are triggered. The visual animation is typically completed well within 500 msec, but it takes around 1000 msec before the previously mentioned events are emitted. This causes problems with for instance `react-navigation-shared-element`, which relies on these events to fire in a timely manner(https://github.com/IjzerenHein/react-navigation-shared-element/issues/24)
This PR updates the resting threshold so that the underlying spring settles faster. No visual differences or differences in smoothness were witnessed during testing.
Time to settle `didFocus`: **941**
Time to settle `stack.onTransitionEnd`: **924**
```
15:59:55.743 [ListViewStack]startTransition, …
```
=> fix: fix ios transitionspec settle time

packages/core/src/__tests__/getPathFromState.test.tsx, packages/core/src/__tests__/getStateFromPath.test.tsx, packages/core/src/getPathFromState.tsx, packages/core/src/getStateFromPath.tsx
Currently, when we define `path` patterns in the linking config, they ignore the parent screen's `path` when parsing, for example, say we have this config:
```js
{
Home: {
path: 'home',
screens: {
Profile: 'u/:id',
},
},
}
```
If we parse the URL `/home`, we'll get this state:
```js
{
routes: [{ name: 'Home' }],
}
```
If we parse the URL `/home/u/cal`, we'll get this state:
```js
{
routes: [
{
name: 'Home',
state: {
routes: [
{
name: 'Home',
state: {
routes: [
{
name: 'Profile',
params: { id: 'cal' },
},
],
},
},
],
},
},
],
}
```
Note how we have 2 `Home` screens nested inside each other. This is not something people usually expect and it seems to trip up a lot of people. Something like following will be more intuitive:
```js
{
routes: [
{
name: 'Home',
state: {
routes: [
{
name: …
```
=> feat: merge path patterns for nested screens

packages/core/src/useNavigationBuilder.tsx
The current code can lead to an infinite render loop if a custom navigator implemented as a hook calls `setState` directly in its body.
This owes to a rather quirky edge case of how hooks work. The [recommended pattern](https://reactjs.org/docs/hooks-faq.html#how-do-i-implement-getderivedstatefromprops) for implementing derived data for a transitioner component implemented as a hook is to call `setState` directly within the body. When you do this, React will immediately rerender the component, *without calling any effects*.
This means that if a custom navigator calls `setState` within its body, `previousStateRef` will not get updated between the subsequent renders. This forces a new call to `router.getRehydratedState` every time, delivering a new state object. The custom navigator sees …
=> refactor: memoize initializedState in useNavigationBuilder

packages/bottom-tabs/package.json, packages/compat/package.json, packages/core/package.json, packages/drawer/package.json, packages/material-bottom-tabs/package.json, packages/material-top-tabs/package.json, packages/native/package.json, packages/routers/package.json, packages/stack/package.json
The tests are being bundled and shipped in prod, this adds a bit of unneeded weight to npm installs. Now they won't be included.
```
@react-navigation/core
- before: 274 files - pkg: 211.0 kB - unpkg: 1 MB
- after: 238 files - pkg: 192.1 kB - unpkg: 827.3 kB
```
Opened a similar PR upstream as well https://github.com/react-native-community/bob/pull/50
=> chore: ignore __tests__ in prod builds

example/ios/Podfile.lock, example/package.json, packages/bottom-tabs/package.json, packages/drawer/package.json, packages/stack/package.json, yarn.lock
I made sure 1.0 is backwards compatible with react-navigation, which means using rn-safe-area-context@1+ with older versions of react-navigation will still work.
=> feat: update react-native-safe-area-context to 1.0.0

packages/stack/src/views/Header/HeaderSegment.tsx
When you're using the following options on `Stack`, the touch event goes to the behind of the Header and we can't really solve this problem in given `headerBackground` component level.
```
options={{
headerTransparent: true,
headerBackground: 
```
=> fix: allow HeaderBackground's subViews to be touchable

packages/bottom-tabs/src/views/BottomTabBar.tsx, packages/bottom-tabs/src/views/BottomTabView.tsx
Some designs call for custom keyboard inputs, or other bottom-aligned views meant overlap over the keyboard. Right now the best option on Android for this case is to set `tabBarVisible`. However changes to `tabBarVisible` doesn't get animated currently, which makes the custom-keyboard-open experience a bit more jarring than the native-keyboard-open one.
I basically cribbed the `Animated.Value` we were using for `keyboardHidesTabBar` and made it depend on both. Note that the offset height depends on which of the two uses cases we're dealing with, which is explained in the code.
I played around with the `BottomTabs` example, setting certain screens to `tabBarVisible: true` and making sure it animated.
=> feat: animate changes to tabBarVisible in BottomTabBar

packages/stack/src/views/Header/HeaderSegment.tsx
Reverts react-navigation/react-navigation#8314
=> Revert "fix: allow HeaderBackground's subViews to be touchable"

packages/native/src/ServerContainer.tsx, packages/native/src/ServerContext.tsx, packages/native/src/__tests__/ServerContainer.test.tsx, packages/native/src/index.tsx, packages/native/src/useLinking.tsx
When doing SSR, the app needs to be aware of request URL to render correct navigation state.
The `ServerContainer` component lets us pass the `location` object to use for SSR.
The shape of the `location` object matches the `location` object in the browser.
Usage:
```js
ReactDOM.renderToString(
<ServerContainer location={{ pathname: req.path, search: req.search }}>
<App />
</ServerContainer>
);
```
Updated example: https://github.com/react-navigation/react-navigation/pull/8298
=> feat: add a `ServerContainer` component for SSR

packages/core/src/CurrentRenderContext.tsx, packages/core/src/index.tsx, packages/core/src/useCurrentRender.tsx, packages/core/src/useNavigationBuilder.tsx, packages/native/package.json, packages/native/src/ServerContainer.tsx, packages/native/src/ServerContext.tsx, packages/native/src/__tests__/ServerContainer.test.tsx, packages/native/src/types.tsx, yarn.lock
User can pass a `ref` to the container to get current options, like they can with `NavigationContainer`:
```js
const ref = React.createRef();
const html = renderToString(
<ServerContainer ref={ref}>
<App />
</ServerContainer>
);
ref.current.getCurrentOptions(); // Options for screen
```
=> feat: add ref to get current options in `ServerContainer`

packages/bottom-tabs/src/views/BottomTabItem.tsx
The check `typeof label === 'string'` is already done in the previous line and returned, so this line is  unnecessary.
=> refactor: remove unnecessary check for type of bottom tab bar label

example/src/Screens/NotFound.tsx, example/src/index.tsx, packages/core/src/__tests__/getStateFromPath.test.tsx, packages/core/src/getStateFromPath.tsx
Currently, if we don't have matching routes for a path, we'll reuse the path name for the route name. This doesn't produce an error, and renders the initial route in the navigator. However, the user doesn't have a way of handling this with the default configuration.
This PR adds support for a wildcard pattern ('*'). The wildcard pattern will be matched after all other patterns were matched and will always match unmatched screens. This allows the user to implement a 404 screen.
Example:
```js
{
Home: '',
Profile: 'user/:id',
404: '*',
}
```
This config will return the `404` route for paths which didn't match `Home` or `Profile`, e.g. - `/test`
=> feat: add wildcard patterns for paths

packages/core/src/isArrayEqual.tsx, packages/core/src/useNavigationBuilder.tsx, packages/core/src/useOnGetState.tsx, packages/native/package.json, packages/native/src/__mocks__/window.tsx, packages/native/src/__tests__/NavigationContainer.test.tsx, packages/native/src/useLinking.tsx, yarn.lock
The PR reworks history integration to better integrate with browser's history stack and supports nested navigation more reliably:
- On each navigation, save the navigation in memory and use it to reset the state when user presses back/forward
- Improve heuristic to determine if we should do a push, replace or back
This closes #8230, closes #8284 and closes #8344
=> refactor: rework history stack integration

packages/drawer/src/views/Drawer.tsx, packages/drawer/src/views/DrawerView.tsx
Fix a minor typo from `drawerPostion` to `drawerPosition` :)
Fix https://github.com/react-navigation/react-navigation/issues/8358
=> fix: typo on drawerPosition default props

example/src/Screens/StackHeaderCustomization.tsx, packages/stack/src/views/Stack/CardContainer.tsx, packages/stack/src/views/Stack/CardStack.tsx
Right now `headerMode: float` renders an absolutely-positioned header. To offset the content appropriately, it then measures the height of the header and compensates with a margin. This approach unfortunately doesn't work well for animations.
Before             |  After
:-------------------------:|:-------------------------:
When rendering the header absolutely we want to render it above (after, in sibling order) the content. But when rendering it relatively we want to render it first (before, in sibling order).
The margin compensation code is no longer necessary so I removed it.
I used the `StackHeaderCustomization` example to make sure transitions between `headerTransparent` and `!headerTransparent` looked good. I added a custom (taller) header to test if height transitions looked good, …
=> fix: relatively position float Header if !headerTransparent

packages/stack/src/views/GestureHandler.native.tsx
In the current implementation the ref is unused, resulting in a constant `current: {null}` on the context.
=> fix: pass gestureRef to PanGestureHandlerNative

example/src/Screens/BottomTabs.tsx, packages/core/src/__tests__/getFocusedRouteNameFromRoute.test.tsx, packages/core/src/getFocusedRouteNameFromRoute.tsx, packages/core/src/index.tsx
Currently, to access the focused child screen, we need to do something like this:
```js
const routeName = route.state
? route.state.routes[route.state.index].name
: route.params?.screen || 'Feed';
```
However, it doesn't handle some cases, such as when `route.state` is partial. This helper will make it easier:
```js
const routeName = getFocusedRouteNameFromRoute(route) ?? 'Feed';
```
=> feat: add helper to get focused route name from nested state

packages/bottom-tabs/src/types.tsx, packages/bottom-tabs/src/views/BottomTabBar.tsx, packages/bottom-tabs/src/views/BottomTabItem.tsx
Currently, if I make the bottom bar higher it'll expand the icon height and keep the label at the bottom and there's [no way to customize that](https://github.com/gfpacheco/react-navigation/blob/master/packages/bottom-tabs/src/views/BottomTabItem.tsx#L233) aside from replacing the whole tabBar component because BottomTabItem doesn't take an `iconStyle` prop.
This PR addresses that by creating a `iconStyle` option. That way I can set `flex: 0` and have both icon and label vertically centered in my tall bar.
Other options like adding bottom margin or negative top to the labels don't seem right to me.
Please let me know if that's something you'd want on your library or if I need to make any changes.
=> feat: add iconStyle prop to bottom tab bar options

packages/stack/src/views/Stack/Card.tsx
Added `collapsable={false}` to the dummy View in order for the Android to render screens properly. This issue is most probably similar to https://github.com/react-navigation/react-navigation/commit/9c06a92d092af150d653c3a2f7fdccd28090bb14 but fixes it on Android since the View seems to be removed from a native view hierarchy due to not drawing anything. To see the bug go to https://github.com/software-mansion/react-native-screens/issues/544.
=> fix: fix screen disappearing on Android

example/src/Screens/PreventRemove.tsx, example/src/index.tsx, packages/core/src/NavigationBuilderContext.tsx, packages/core/src/__tests__/useOnAction.test.tsx, packages/core/src/types.tsx, packages/core/src/useKeyedChildListeners.tsx, packages/core/src/useNavigationBuilder.tsx, packages/core/src/useOnAction.tsx, packages/core/src/useOnGetState.tsx, packages/core/src/useOnPreventRemove.tsx, packages/stack/src/views/Stack/Card.tsx
A lot of times, we want to prompt before leaving a screen if we have unsaved changes. Currently, we need to handle multiple cases to prevent this:
- Disable swipe gestures
- Override the back button in header
- Override the hardware back button on Android
This PR adds a new event which is emitted before a screen gets removed, and the developer has a chance to ask the user before closing the screen.
Example:
```js
React.useEffect(
() =>
navigation.addListener('beforeRemove', (e) => {
if (!hasUnsavedChanges) {
return;
}
e.preventDefault();
Alert.alert(
'Discard changes?',
'You have unsaved changes. Are you sure to discard them and leave the screen?',
[
{ text: "Don't leave", style: 'cancel', onPress: () => {} },
{
text: 'Discard',
style: 'destructive',
onPress: () => …
```
=> feat: add a `beforeRemove` event

packages/stack/src/types.tsx, packages/stack/src/views/Header/HeaderBackButton.tsx
Currently, if you use HeaderBackButton with the react-native-screens, there is an extra margin added that is not needed. This can be solved via the style overrides
=> feat: allow style overrides for HeaderBackButton

packages/stack/src/types.tsx, packages/stack/src/views/Stack/CardContainer.tsx, packages/stack/src/views/Stack/CardStack.tsx, packages/stack/src/views/Stack/StackView.tsx
Allows you to subscribe to gesture navigation events, we have a custom keyboard that we want to hide and show when gesture is being used to navigate (same as native keyboard)
This PR has been reopened after https://github.com/react-navigation/react-navigation/pull/7800 was closed (`master` renamed to `main`)
=> feat: emit gesture navigation events from stack view

packages/bottom-tabs/src/types.tsx, packages/bottom-tabs/src/views/BottomTabItem.tsx
In the process of upgrading from v4, I noticed a regression. 
In the past, the function form of `tabBarLabel` did get an `orientation: 'landscape' | 'portrait'`, this is no longer the case.
However, when using a custom Text rendering, we need to apply a margin to the text in horizontal mode.
Since the orientation/horizontal state is decided based on internal heuristics, It is a huge pain with a high bug potential when reimplementing that detection myself.
=> fix: pass label position flag to label rendering in BottomTabBar

packages/bottom-tabs/src/views/BottomTabItem.tsx, packages/drawer/src/views/DrawerItem.tsx
React Native 0.62 removes the deprecated `accessibilityStates` property and replaces it with an `accessibilityState` object instead. This PR adds the new property where needed, but leaves the old one in place for backwards compatibility. Without the change, the selected tab in BottomTabNavigator isn't announced properly in VoiceOver.
=> fix: add accessibilityState property

packages/bottom-tabs/src/types.tsx, packages/bottom-tabs/src/views/BottomTabBar.tsx
Adds ability for a user to specify how long the animation takes when changing the `tabBarVisible` option on a bottom tab navigator.
=> feat: user can specify how long tab hide animation should take

packages/bottom-tabs/src/index.tsx
Exposed `BottomTabBarButtonProps` type is needed when providing a custom component to `tabBarButton` property.
=> feat: expose `BottomTabBarButtonProps` type

packages/core/src/__tests__/NavigationStateUtils.test.js
From the current implementation of `NavigationStateUtils.pop`, a new
test case was added to document the behavior when popping when the index
is at the first route and there are multiple routes.
Question: what is the reason why the top route does not get removed in that specific case? I'm not that familiar with react-navigation, but my basic intuition would probably have told me that popping in that situation would have removed the top-most route.
Thanks in advance for your feedback :)
=> test: add test case for StateUtils.pop

packages/native/src/createKeyboardAwareNavigator.js
currentlyFocusedField => currentlyFocusedInput
Fixes #8457 for 4.x because `createKeyboardAwareNavigator.js` is not inside the `main` branch.
Fixed in main here: https://github.com/react-navigation/react-navigation/commit/35d6b9e3a4a28a59b3b11a67acbf7753d41705ae
=> fix: don't use deprecated currentlyFocusedField

packages/core/src/routers/__tests__/Routers.test.js
These tests document the behavior of using set params action for the
different routers. Even if the action is named `SET_PARAMS`, it merges
the params with the previous one: this behavior matches the `setState`
method used in React's components.
=> test: document set params action for routers

.github/workflows/expo-preview.yml
This enables a new interface with Metro, [outlined in this tweet](https://twitter.com/expo/status/1293613036482121728). It's still in a sort-of beta and that's why it's opt-in. We would love to see how this improves bundling on the React Navigation example app, and/or if you encounter anything special.
Feel free to close this as well if you don't want to do this right now!
=> chore: enable faster bundling on preview builds

packages/stack/src/views/Header/HeaderTitle.tsx
We use `cypress-axe` to ensure accessibility compliance for the web version of our app (WCAG level A and AA) and it showed that the `HeaderTitle` is not compliant.
The rule that fails is `aria-required-attr` and it complains about the `h1` missing the `aria-level` attribute:
https://dequeuniversity.com/rules/axe/3.4/aria-required-attr?application=axeAPI
The solution is documented in `react-native-web`:
https://github.com/necolas/react-native-web/blob/master/packages/docs/src/guides/accessibility.stories.mdx#accessibilityrole-string
If you're interested, I could also add basic accessibility tests on `react-navigation` for the web using `cypress` and `cypress-axe`.
=> fix: add aria-level to HeaderTitle

packages/drawer/src/views/DrawerItem.tsx
In the [DrawerItem](https://github.com/react-navigation/react-navigation/blob/main/packages/drawer/src/views/DrawerItem.tsx), It's not possible to provide style for the [label wrapper](https://github.com/react-navigation/react-navigation/blob/main/packages/drawer/src/views/DrawerItem.tsx#L167), only for the label, so the label wrapper must at least be `flex: 1` in order to be more flexible for custom components, like in the pictures below.
In the below examples, providing `flex: 1` inside the custom component view is not enough, because the wrapper does not grow. This PR will fix it.
An alternative would be creating a new prop `labelStyleWrapper`, but I don't see any motivation for doing so, as this PR would fix it.
=> fix: add flex: 1 to DrawerItem style

packages/bottom-tabs/README.md, packages/compat/README.md, packages/compat/package.json, packages/drawer/README.md, packages/drawer/package.json, packages/drawer/src/views/DrawerView.tsx, packages/material-bottom-tabs/README.md, packages/material-bottom-tabs/package.json, packages/material-top-tabs/README.md, packages/material-top-tabs/package.json, packages/native/README.md, packages/routers/README.md, packages/routers/package.json, packages/stack/README.md, packages/stack/package.json
After the docs website migration to the Docusaurus V2 the URL format have changed. Using the old URLs format results in redirect, which can be avoided by updating the docs website links. This PR updates all outdated URLs that I was able to find.
Additionally I have updated the Material Design website link which was changed too.
=> chore: update docs website URLs to avoid the redirect

packages/core/src/__tests__/NavigationStateUtils.test.js
This change makes the tests in NavigationStateUtils more specific by splitting tests with multiple assertions.
I also grouped the tests into describe blocks by the function they test. Let me know if that's something you want or not, I can revert it if needed.
This is my first contribution, but I plan to make more of these which would mostly consists on improving tests.
=> test: move assertions into their own tests

packages/core/src/getStateFromPath.tsx
What just randomly reading, but I think there's a typo
```
['ab', 'aba'].sort((a, b) => {
if (a.startsWith(b)) {
return -1;
}
if (b.startsWith(a)) {
return 1;
}
});
(2) ["aba", "ab"]
['ab', 'a'].sort((a, b) => {
if (a.startsWith(b)) {
return -1;
}
if (b.startsWith(a)) {
return 1;
}
});
(2) ["ab", "a"]
```
=> fix: typo in logic of getStateFromPath

packages/bottom-tabs/src/utils/useWindowDimensions.tsx, packages/drawer/src/utils/useWindowDimensions.tsx
This PR fixes the `useWindowDimensions` hook by making sure that the event listener is properly removed.
=> fix: cleanly removing event listeners in useWindowDimensions

packages/core/src/routers/SwitchRouter.js
`undefined` should be left to the javascript compiler.
Originally, I opened this PR because I thought there was an inconsistency between the stack and switch routers, in the way they handle params. Turns out it's all fine, but I found this case where `undefined` is assigned to a variable and I thought I could submit a small refactor for it.
=> refactor: remove undefined assignment in switch router

packages/core/src/StateUtils.js, packages/core/src/__tests__/NavigationStateUtils.test.js
I think this improves the error message a little, let me know if you have a better suggestion :)
=> refactor: improve error message of StateUtils.jumpTo

packages/bottom-tabs/src/views/BottomTabBar.tsx
This adds a compact height mode for iOS devices that are in a compact vertical class (phones in landscape). This is similar to the size change that happens to the header when in landscape mode. Finding a size reference was challenging since most apps lock phones to portrait, but [this answer](https://stackoverflow.com/a/25550871) on Stack Overflow states that it should be 32 pts.
I asked yesterday in the Discord chat if there would be interest in this and some other enhancements here, but no on replied, so I thought I would go ahead and open this to at least start a discussion.
=> feat: add compact size for bottom tabs

packages/core/src/routers/__tests__/SwitchRouter.test.js
Found this case were the key gets set to `{ key: null }` instead of just being `null`. Should I just call `back()` at this point? Because I don't think there is a difference between a `null` vs `undefined` key
=> test: fix usage of routerTestHelper back action

packages/routers/src/StackRouter.tsx, packages/routers/src/__tests__/StackRouter.test.tsx
Currently, stack router adds a duplicate route when pushing a new route with a key that already exists. This is a buggy behaviour since keys need to be unique in the stack.
This commit fixes the behaviour to bring the existing route with the same key to focus (and merge new params if any) instead of adding a duplicate route.
=> fix: handle pushing a route with duplicate key

packages/material-bottom-tabs/src/views/MaterialBottomTabView.tsx
Make react-native-vector-icons optional #8821 
Referenced from https://github.com/callstack/react-native-paper/blob/4b26429c49053eaa4c3e0fae208639e01093fa87/src/components/MaterialCommunityIcon.tsx#L14
https://callstack.github.io/react-native-paper/getting-started.html
> To get smaller bundle size by excluding modules you don't use, you can use our optional babel plugin. The plugin automatically rewrites the import statements so that only the modules you use are imported instead of the whole library. Add react-native-paper/babel to the plugins section in your babel.config.js for production environment. It should look like this:
> ```
> module.exports = {
>   presets: ['module:metro-react-native-babel-preset'],
>   env: {
>     production: {
>       plugins: ['react-native-paper/babel'],
> …
```
=> feat: make react-native-vector-icons optional

packages/core/src/BaseNavigationContainer.tsx, packages/core/src/__tests__/BaseNavigationContainer.test.tsx, packages/core/src/types.tsx
Often developers miss these console messages: this allows missed routes to be emitted to whatever event logger users prefer.
=> feat: add an unhandled action listener

packages/native/package.json, packages/native/src/types.tsx, packages/native/src/useLinking.native.tsx
https://github.com/react-navigation/react-navigation/issues/8941
Prefixes should be more flexible for situations like wild card subdomain. On android and IOS we can define wild cards by * but react-navigation does not work, In this PR I added support for RegExp Prefixes.
For Example
```js
{
prefixes: [
/^[^.s]+.example.com/g
],
}
```
I tested this work well.
=> feat: support wildcard string prefixes

example/src/Screens/BottomTabs.tsx, packages/bottom-tabs/src/navigators/createBottomTabNavigator.tsx, packages/bottom-tabs/src/types.tsx, packages/bottom-tabs/src/views/BottomTabView.tsx
This feature adds the sceneContainerStyle prop to the bottom-tabs navigator, to allow setting styles on the container's view. It's already implemented in the material-top-tabs and drawer navigators, I've simply ported it into the bottom-tabs navigator.
It also fixes this issue:
https://github.com/react-navigation/react-navigation/issues/8076
=> feat: add sceneContainerStyle prop to bottom-tabs navigator

packages/bottom-tabs/src/navigators/createBottomTabNavigator.tsx, packages/bottom-tabs/src/types.tsx, packages/bottom-tabs/src/views/BottomTabView.tsx, packages/compat/src/createSwitchNavigator.tsx, packages/core/src/types.tsx, packages/drawer/src/navigators/createDrawerNavigator.tsx, packages/drawer/src/types.tsx, packages/drawer/src/views/DrawerItemList.tsx, packages/drawer/src/views/DrawerView.tsx, packages/material-bottom-tabs/src/navigators/createMaterialBottomTabNavigator.tsx, packages/material-bottom-tabs/src/types.tsx, packages/material-bottom-tabs/src/views/MaterialBottomTabView.tsx, packages/material-top-tabs/src/navigators/createMaterialTopTabNavigator.tsx, packages/material-top-tabs/src/types.tsx, packages/material-top-tabs/src/views/MaterialTopTabView.tsx, packages/routers/src/DrawerRouter.tsx, packages/routers/src/StackRouter.tsx, packages/routers/src/TabRouter.tsx, packages/routers/src/__tests__/DrawerRouter.test.tsx, packages/routers/src/__tests__/TabRouter.test.tsx, packages/routers/src/types.tsx, packages/stack/src/navigators/createStackNavigator.tsx, packages/stack/src/types.tsx, packages/stack/src/views/Stack/CardStack.tsx, packages/stack/src/views/Stack/StackView.tsx
The commit improves the navigation state object to have more specific types.
e.g. The `routeNames` array will now have proper type instead of `string[]`
=> feat: improve types for navigation state

packages/core/src/__tests__/getActionFromState.test.tsx, packages/core/src/__tests__/index.test.tsx, packages/core/src/getActionFromState.tsx, packages/core/src/types.tsx, packages/core/src/useNavigationBuilder.tsx, packages/native/src/useLinkTo.tsx, packages/native/src/useLinking.native.tsx, packages/native/src/useLinking.tsx, packages/routers/src/types.tsx
Currently when we receive a deep link after the app is rendered, it always results in a `navigate` action. While it's ok with the default configuration, it may result in incorrect behaviour when a custom `getStateForPath` function is provided and it returns a routes array different than the initial route and new route pair.
The commit changes 2 things:
1. Add ability to reset state via params of `navigate` by specifying a `state` property instead of `screen`
2. Update `getStateForAction` to return an action for reset when necessary according to the deep linking configuration
Closes #8952
=> feat: allow deep linking to reset state

packages/native/src/types.tsx, packages/native/src/useLinking.native.tsx
For apps with push notifications linking to screens inside the app, currently we need to handle them separately (e.g. [instructions for firebase](https://rnfirebase.io/messaging/notifications#handling-interaction), [instructions for expo notifications](https://docs.expo.io/push-notifications/receiving-notifications/)). But if we add a link in the notification to use for deep linking, we can instead reuse the same deep linking logic instead.
This commit adds the `getInitialURL` and `subscribe` options which internally used `Linking` API to allow more advanced implementations by combining it with other sources such as push notifications.
Example usage with Firebase notifications could look like this:
```js
const linking = {
prefixes: ['myapp://', 'https://myapp.com'],
async getInitialURL() …
```
=> feat: add `getInitialURL` and `subscribe` options to linking config

packages/core/src/views/__tests__/NavigationFocusEvents.test.js
This PR adds a few unit tests on the NavigationFocusEvents. It asserts that events are emitted in the expected order in different cases.
=> test: add navigation focus events tests

packages/core/src/__tests__/getEventManager.test.js
Decided to contribute back some tests I've written when porting over the implementation of getEventManager. Let me know if I can improve anything :)
=> test: add tests to getEventManager

packages/stack/src/views/KeyboardManager.tsx
When navigating from ScreenA to ScreenB and then back to ScreenA,
react-navigation unconditionally calls `Keyboard.dismiss()`.
If the user is fast enough and taps on a `TextInput` after coming
back from ScreenB, the keyboard opens, just to be dismissed again.
This would also happen if some logic automatically focuses the
`TextInput` in ScreenA. This behaviour can be observed in
https://snack.expo.io/lTDZhVNhV.
=> fix: android textinput gets blurred after navigating back

example/package.json, packages/stack/package.json, packages/stack/src/views/MaskedViewNative.tsx, yarn.lock
replaced `@react-native-community/masked-view` with `@react-native-masked-view/masked-view` due to namespace change.
=> chore: replace community maskedview

packages/routers/src/DrawerRouter.tsx
openByDefault in connection with expo-links only works for `getInitialState()`. When a page of the application is refreshed, `getRehydratedState()` is called and the drawer stays closed. This should fix the issue.
=> fix: consider openByDefault prop when rehydrating drawer state

packages/native/src/theming/ThemeContext.tsx
Set displayName for ThemeContext, so that it'll show ThemeContext.Provider instead of mere Context.Provider in React Devtools.
=> chore: set displayName for ThemeContext

packages/drawer/src/views/DrawerItem.tsx, packages/drawer/src/views/TouchableItem.ios.tsx, packages/stack/src/views/BorderlessButton.tsx, packages/stack/src/views/TouchableItem.ios.tsx
- Include pressColor property that could override the default grey value presented in TouchableItem
=> feat: add pressColor and pressOpacity props to drawerItem

example/src/Screens/NotFound.tsx, packages/core/package.json, packages/core/src/BaseNavigationContainer.tsx, packages/core/src/__tests__/getActionFromState.test.tsx, packages/core/src/__tests__/getPathFromState.test.tsx, packages/core/src/__tests__/getStateFromPath.test.tsx, packages/core/src/findFocusedRoute.tsx, packages/core/src/getActionFromState.tsx, packages/core/src/getPathFromState.tsx, packages/core/src/getStateFromPath.tsx, packages/core/src/index.tsx, packages/core/src/types.tsx, packages/core/src/useNavigationBuilder.tsx, packages/native/src/useLinking.tsx, packages/routers/src/CommonActions.tsx, packages/routers/src/StackRouter.tsx, packages/routers/src/TabRouter.tsx, packages/routers/src/__tests__/StackRouter.test.tsx, packages/routers/src/__tests__/TabRouter.test.tsx, packages/routers/src/types.tsx, yarn.lock
This commit adds a new optional property on the `route` object called `path`.
This property will be added if the screen was opened from a deep link.
Having this property helps with few things:
- Preserve the URL when the path was unmatched, e.g. 404 routes
- Expose the path to the user so they could handle it manually if needed, e.g. open in a webview
- Avoid changing URL if state to path doesn't match current path, e.g. if orders of params change
Fixes #9102
https://user-images.githubusercontent.com/1174278/110035095-81d9a900-7d3b-11eb-8c94-856f5fecfc00.mp4
=> feat: associate path with the route it opens when deep linking

packages/stack/src/views/Header/Header.tsx
Use `headerStatusBarHeight` that was passed in `options`
=> fix: respect headerStatusBarHeight option in Stack

packages/drawer/src/views/DrawerView.tsx, packages/tabs/src/navigators/createBottomTabNavigator.tsx
Added a check for `screensEnabled` in `ScreenContainer` to make it behave the same as `Screen` in `ResourceSavingScreen.tsx`. Should resolve https://github.com/expo/expo/issues/12374.
=> fix: check for screens enabled in ScreenContainer

packages/bottom-tabs/src/utils/useIsKeyboardShown.tsx
Keyboard.removeEventListener was restored in https://github.com/facebook/react-native/commit/035718ba97bb44c68f2a4ccdd95e537e3d28690c but not Keyboard.removeListener. In this case we can use the subscription object returned from addListener. The addListener method always returned a subscription object so no need to check if the return value is an object (like in other cases of addEventListener methods).
=> fix: remove calls to removed Keyboard.removeListener in useIsKeyboardShown

packages/core/src/__tests__/getStateFromPath.test.tsx, packages/core/src/getStateFromPath.tsx
Changed the logic of resolving if we should add `initialRouteName` to the current state part from being only based on the name of the routes of the navigator with `initialRouteName` specified to checking if we are in the same place in the config tree as the `initialRouteName` we are trying to add.
Should resolve #9466.
=> fix: properly resolve initialRouteNames

packages/stack/src/views/TouchableItem.ios.tsx
fixes https://github.com/react-navigation/react-navigation/issues/9496
`this.props.pressOpacity` is used for the opacity animation. HeaderBackButton does not pass an explicit value for this prop so the default should be used. But the default does not exist because the name `activeOpacity` is invalid.
=> fix default `pressOpacity` for `TouchableItem.ios.tsx`

packages/stack/src/views/Stack/Card.tsx
This enables navigating back on iPadOS by swiping right with two fingers on a connected trackpad, which is the default behaviour of the native navigator. This could be made configurable, but I am not sure there is a reason to not have it enabled by default. Happy to discuss and adjust the PR.
=> Enable iPad Trackpad Two Finger back gesture in Stack Navigator

.github/workflows/expo-preview.yml, .github/workflows/expo.yml
This version allows you to skip installing `expo-cli`. If you want to use EAS, this also got you covered! Having no CLI installed prevents the GH action from validating the `EXPO_TOKEN`, the [GH action handles this case](https://github.com/expo/expo-github-action/blob/main/src/tools.ts#L54) and I'm pretty confident this is set up properly 😄
=> chore: upgrade to expo-github-actions v6

packages/core/src/__tests__/getStateFromPath.test.tsx, packages/core/src/getStateFromPath.tsx
We want to server user profile like https://github.com/zhigang1992 or https://twitter.com/zhigang1992 along side with screens in the app.
```typescript
const configs = {
screens: {
debugPanel: 'debugPanel',
user: ':userSlug',
},
}
getStateFromPath('/debugPanel', configs)
```
and
```typescript
const configs = {
screens: {
debugPanel: 'debugPanel',
user: '*',
},
}
getStateFromPath('/debugPanel', configs)
```
have different behaviors under Hermes engine, because we are only sorting '*'.
IMHO `:urlCode` is also a form of wildCard.
=> fix: sort wildcard and :params 

packages/stack/src/views/Stack/Card.tsx
I noticed that accessing `closing` through `cardStyleInterpolator` would always return an Animated node with value 0. It looks like it isn't being updated anywhere, so I added it to the `animate` method.
I am using this functionality to allow screens to have different in and out transitions.
On a side note, I feel like this would be more useful as a boolean, instead of an Animated value.
=> fix: update isClosing in Stack Card

packages/native/src/types.tsx, packages/native/src/useLinking.native.tsx
This is useful for libraries like `expo-auth-session` which also use links for authentication.
Usage:
```js
const linking = {
prefixes: ['myapp://'],
filter: (url) => !url.includes('+expo-auth-session'),
};
```
=> feat: add a way to filter out deep links from being handled

packages/native/src/useLinkTo.tsx
When an object was passed to the `to` parameter in `useLinkTo`, an error message would be thrown (*Cannot find property 'root'*). Apparently, this was introduced in commit 1d40279, where the `root` variable was removed.
=> fix: fix useLinkTo crash when an object is passed as a parameter

packages/drawer/src/views/DrawerView.tsx
Fix to prevent showing blank screen while screens switching process.
Currently we can see it using dark background color in screens.
This fix also makes clear work with eager loading of screens (`detachInactiveScreens={false}` `lazy={false}`).
=> fix: blink while switching screens

packages/drawer/src/views/DrawerContent.tsx, packages/drawer/src/views/DrawerContentScrollView.tsx
Closes #9350 
Fixed to use ref in DrawerContent and DrawerContentScrollView.
Please review.
=> feat: use forwardRef with DrawerContent and DrawerContentScrollView

packages/stack/src/views/Header/HeaderSegment.tsx
I'm having an issue with a custom back button in v6: I'm passing a react component as headerLeft and I'm expecting it to receive some props such as onPress (see v5. https://github.com/react-navigation/react-navigation/blob/89d3365efb48c48e879c05ece2423f42c20f26cb/packages/stack/src/views/Header/HeaderSegment.tsx#L296) but in v6, these props are no longer passed, they are only passed to the default back button (https://github.com/react-navigation/react-navigation/blob/b0130570be938268bcd40e1552a64cc14545cea4/packages/stack/src/views/Header/HeaderSegment.tsx#L161). 
This PR fixes it.
test plan: use the following diff in the example app. Currently, the button does not react to presses. With the fix, it works as expected (takes user to previous screen).
```diff
diff --git …
```
=> fix: pass all props to custom headerLeft

packages/elements/src/types.tsx, packages/stack/src/types.tsx, packages/stack/src/views/Header/HeaderSegment.tsx
similar to https://github.com/react-navigation/react-navigation/pull/9806 but for headerTitle's onlayout prop
=> fix: pass onlayout to headerTitle

packages/stack/src/views/Stack/CardStack.tsx
We were encountering an error on this piece of code.
I don't have clear reproduction paths with an Expo snack, but if you look at the TypeScript types, you see that `nextDescriptor` can be undefined, causing the error on this line of code.
=> Fixing nullpointer exception

packages/elements/src/SafeAreaProviderCompat.tsx
When using SafeAreaProvider I can pass style directly and when I decide to SafeAreaProviderCompat I discover that style props is missing.
=> feat(elements): add style to SafeAreaProviderCompat props

packages/native-stack/src/views/NativeStackView.tsx
`flex: 1` needs to be set on the `View` container sits between the `Screen` component and screen contents in `NativeStackView` otherwise content on tabs nested inside native stack will not be visible, along with other similar types of bugs.
Reproducible example: https://gist.github.com/brentvatne/273d34be0c937237eb353e4100c49949
Apply the fix from this diff to see it resolves the issue.
=> fix: content container in native web stack should fill parent

packages/native/src/useScrollToTop.tsx
This fix makes `useScrollToTop` work with `react-native-largelist`. Otherwise you get error `Argument 1 (CGFloat) of SpringScrollView.scrollTo must not be null`. Should not break anything, because it's still compatible with original `scrollTo` signature.
=> fix: make useScrollToTop work with react-native-largelist

packages/elements/src/ResourceSavingView.tsx
I created the original issue, found the root cause and was able to fix it.
Original issue: https://github.com/react-navigation/react-navigation/issues/9889
=> fix: resized view never re-appears on macos #9889

packages/native-stack/src/types.tsx, packages/native-stack/src/views/HeaderConfig.tsx
Thanks to https://github.com/software-mansion/react-native-screens/discussions/1071#discussioncomment-1227326.
PR exposing `disableBackButtonMenu` from react-native-screens to `@react-navigation/native-stack` under new name - `headerBackButtonMenuEnabled`.
=> feat: add headerBackButtonMenuEnabled prop

packages/native-stack/src/navigators/createNativeStackNavigator.tsx
This pull request fixes #10287.
When we use `Link`, we actually use `useLinkProps` hook under the hood and it uses `navigation` object to`dispatch` events. That `navigation` object is a bit different than what we get when we use `useNavigation` hook.
`useNavigation` gets the navigation object [using `NavigationContext`](https://github.com/react-navigation/react-navigation/blob/b91c9b05ff96727f5fa6ef0bec51b5d7eac06600/packages/core/src/useNavigation.tsx#L16) while `useLinkProps` get its `navigation` object [using `NavigationHelperContext`](https://github.com/react-navigation/react-navigation/blob/b91c9b05ff96727f5fa6ef0bec51b5d7eac06600/packages/native/src/useLinkProps.tsx#L26). To my understanding, `NavigationHelperContext` wraps navigators (StackNavigator, TabNavigator etc.) while …
=> fix: wrap native stack with NavigationContent

packages/stack/src/views/Stack/Card.tsx
With the release of Gesture Handler 2 some gesture handlers have been updated to follow state-flow more consistently across the platforms. Among them was the Pan gesture which was changed to transition to the `BEGAN` state as soon as finger touches the screen opposed to just before transitioning to the `ACTIVE` state.
`@react-navigation/stack` is relying on the old behavior which may be causing some unexpected issues in apps, for example: https://github.com/software-mansion/react-native-gesture-handler/issues/1801.
This PR changes the swipe-back gesture to start when the Pan transitions to the`ACTIVE` state. Since previously Pan gesture was transitioning to the `BEGAN` state just before transitioning to the `ACTIVE` state this change would be compatible with older versions of Gesture …
=> Change state at which swipe back gesture starts to `ACTIVE`

packages/native/src/useLinking.tsx
Hello 👋 
We've been seeing [this crash](https://github.com/react-navigation/react-navigation/pull/9970#issuecomment-941908688) (shown in the following screenshot) happening in our production code. I unfortunately don't know how to consistently reproduce this problem, but I believe this PR is very safe and will fix the issue.
As explained in [this comment](https://github.com/react-navigation/react-navigation/pull/9970/files#r784475821), `TypeError: Cannot read property 'id' of undefined` tells us that somehow the `items` array is actually getting in a state where it contains `undefined`.
Now, there's only four places the `items` array is written to: [line 84](https://github.com/react-navigation/react-navigation/blob/fb84805c889bbb7059e7e95592c004aea2a510d6/packages/native/src/useLinking.tsx …
=> fix: useLinking crash

CONTRIBUTING.md
Oddly enough the CONTRIBUTING.md file had two documentation typos on the commit guide for docs :)
Very meta
=> docs: correct typos on line 75

packages/native/src/useLinking.tsx
this avoids an uncaught exception from getPathFromState
it appears root state is undefined during full root navigation switch
(for example during a login event and going from unprotected to protected nav)
This is tested and works in my app, including the linking URL behavior as expected
Fixes #10185
Here's the patch-package patch I'm using
[@react-navigation+native+6.0.6.patch.txt](https://github.com/react-navigation/react-navigation/files/7672638/%40react-navigation%2Bnative%2B6.0.6.patch.txt)
=> fix(web): avoid passing undefined root state in web

packages/bottom-tabs/src/index.tsx, packages/drawer/src/index.tsx, packages/material-bottom-tabs/src/index.tsx, packages/material-top-tabs/src/index.tsx, packages/native-stack/src/index.tsx, packages/stack/src/index.tsx
Currently, there is no way to create a custom navigator and router on top of **Native-Stack**
So by exporting **NativeStackView** along with its types from native-stack, we can use it along with **useNavigationBuilder** to create custom navigators​ with some additional functionality built on top of it.
We can also use **StackRouter** from **@react-navigation/native** to create customised routers and use it with the navigator we created on top of **NativeStackView**.
We can follow the same doc to extend NativeStackView with our own router or build additional functionality on top of it.
https://reactnavigation.org/docs/custom-navigators#extending-navigators.
=> feat(native-stack): export NativeStackView to support custom routers on native-stack

example/ios/Podfile
Causing pod install to abort.
Match [correct syntax](https://github.com/facebook/flipper/blob/main/react-native/ReactNativeFlipperExample/ios/Podfile).
Before
After
=> fix: example CocoaPodsError invalid Podfile

packages/core/src/__tests__/createNavigationContainerRef.test.tsx, packages/core/src/createNavigationContainerRef.tsx
Calling `removeListener` on event that doesn't have any listeners will add new key for that event to listeners with value `undefined`. After that attempts to set `ref.current` will fail with "Cannot read property 'forEach' of undefined" error. Fix is quite simple. Just needed to add check if there is listeners for the given event.
FYI @satya164. This is related to your recent change https://github.com/react-navigation/react-navigation/commit/acdde18d8938741fd27d8ff8c8249977e0cb03e7
=> fix(core): removal of non-existing listener should not break updating navigation container ref

packages/drawer/src/views/legacy/Drawer.tsx, packages/drawer/src/views/modern/Drawer.tsx
regarding to 
https://github.com/react-navigation/react-navigation/issues/10210
and after latest updates for 
https://github.com/react-navigation/react-navigation/commit/524657484e6b21ecc5754b63468dd00304a8e450
=> fix(drawer): fix drawer when changing drawertype (ex: front -> permanent)

packages/native/src/useLinking.tsx
This PR aims to fix a crash when quickly navigating back and forward in browser (same as [#10306](https://github.com/react-navigation/react-navigation/pull/10306) but in a different way).
I'm not sure either it's by design to allow _empty_ elements in [items](https://github.com/react-navigation/react-navigation/blob/c864c9ecfe825d293f0fe354f21a161f934d4f56/packages/native/src/useLinking.tsx#L30) array (then type definition should be also changed [here](https://github.com/react-navigation/react-navigation/pull/10306) to reflect the runtime, or it's safe to also reset the index when [items is reset](https://github.com/react-navigation/react-navigation/blob/c864c9ecfe825d293f0fe354f21a161f934d4f56/packages/native/src/useLinking.tsx#L109) (this PR).
=> fix: broken history items index when items reset

packages/drawer/src/types.tsx, packages/drawer/src/views/DrawerItem.tsx, packages/drawer/src/views/DrawerItemList.tsx
Add `drawerAllowFontScaling` to the drawer options, so consumers can enable or disable font scaling for drawer labels to respect Text Size accessibility settings. The option functions similarly to [`tabBarAllowFontScaling`](tabBarAllowFontScaling).
=> feat(drawer): add `drawerAllowFontScaling` option

packages/bottom-tabs/src/views/BottomTabView.tsx, packages/bottom-tabs/src/views/ScreenFallback.tsx, packages/drawer/src/views/DrawerView.tsx, packages/drawer/src/views/ScreenFallback.tsx
Added new prop `tabsOrDrawer` for `ScreenContainer` which makes `react-native-screens` on `iOS` use new component if it is available. See https://github.com/software-mansion/react-native-screens/pull/1029 for context.
=> feat: add prop for new container

packages/tabs/src/views/BottomTabBar.tsx
Fixes https://github.com/react-navigation/react-navigation/issues/9803
In React Native 0.65 [`Keyboard.removeListener`](https://github.com/react-navigation/react-navigation/issues/9803) has been deprecated, therefore unmounting the `BottomTabBar` component in a RN 0.65 app causes a crash.
This change replaces that method with the `.remove()` method returned by `Keyboard.addListener`.
=> fix: remove React Native Keyboard method deprecated in 0.65

packages/drawer/src/types.tsx
Added type definition  and documentation for contentOptions
Resources:
[react-navigation.d.ts#L999](https://github.com/react-navigation/react-navigation/blob/3.x/typescript/react-navigation.d.ts#L999)
[react-navigation.d.ts#L1004](https://github.com/react-navigation/react-navigation/blob/3.x/typescript/react-navigation.d.ts#L1024)
[Official docs](https://reactnavigation.org/docs/4.x/drawer-navigator/#contentoptions-for-draweritems)
=> chore: add type definition for contentOptions

example/src/Screens/NativeStack.tsx, packages/native-stack/src/types.tsx, packages/native-stack/src/views/NativeStackView.native.tsx
**Motivation**
This PR adds two missing props from `react-native-screens` - `customAnimationOnGesture` (renamed from `customAnimationOnSwipe`) and `fullScreenGestureEnabled` (renamed from `fullScreenSwipeEnabled `).
Also, the `isNativeStack` prop is set in order to make transition progress work correctly.
PR to docs to accommodate the changes: https://github.com/react-navigation/react-navigation.github.io/pull/1112
**Test plan**
`fullScreenGestureEnabled` in action:
https://user-images.githubusercontent.com/39658211/152153496-a844d034-78f4-4f19-9722-ad04f1baddf7.mov
`fullScreenGestureEnabled` & `customAnimationOnGesture` & animation: `fade`:
https://user-images.githubusercontent.com/39658211/152153654-5e9f1dd5-dc2f-4897-b975-76591ff7dbe3.mov
=> feat: add customAnimationOnGesture & fullScreenSwipeEnabled props to native-stack

packages/native-stack/src/views/NativeStackView.native.tsx
Original PR: https://github.com/software-mansion/react-native-screens/pull/830
iOS 14 added a back button menu that isn't correctly handled in react-navigation v6. This PR fixes this by taking the number of screens that need to be dismissed from the native side.
This number is always 1 on Android: https://github.com/software-mansion/react-native-screens/pull/830/files#diff-6056183a278fe1325ac5dee21004ce6dad735d37b3b855a5de50bccf25ba789dR31
And it is computed on iOS: https://github.com/software-mansion/react-native-screens/pull/830/files#diff-e988f8ab84e7063d6cc9ad4e634806389882ce6727b5c95f3cfbc9f9d3921a67R531 which defaults to 1.
https://user-images.githubusercontent.com/39658211/155331514-6b562864-01b1-43bf-b9a9-87afaa5a84b4.mov …
=> fix: iOS back button menu in native-stack

example/types.check.tsx, package.json, packages/bottom-tabs/src/navigators/createBottomTabNavigator.tsx, packages/bottom-tabs/src/types.tsx, packages/core/src/SceneView.tsx, packages/core/src/__tests__/index.test.tsx, packages/core/src/types.tsx, packages/core/src/useDescriptors.tsx, packages/core/src/useNavigationBuilder.tsx, packages/core/src/useNavigationCache.tsx, packages/core/src/useNavigationHelpers.tsx, packages/drawer/src/navigators/createDrawerNavigator.tsx, packages/drawer/src/types.tsx, packages/material-bottom-tabs/src/navigators/createMaterialBottomTabNavigator.tsx, packages/material-bottom-tabs/src/types.tsx, packages/material-top-tabs/src/navigators/createMaterialTopTabNavigator.tsx, packages/material-top-tabs/src/types.tsx, packages/native-stack/src/navigators/createNativeStackNavigator.tsx, packages/native-stack/src/types.tsx, packages/stack/src/navigators/createStackNavigator.tsx, packages/stack/src/types.tsx, yarn.lock
When we have nested navigators, we often may want control over which navigator should handle an action that we dispatch. This is often handled automatically, e.g. if you navigate to a screen named `Settings`, the navigator which contains the `Settings` screen will handle the action. But in some cases, it's not possible to figure out the navigator automatically.
Some example cases:
We may want to have nested drawers to have a drawer on the left, and one on the right - and still be able to open/close them. We can use `getParent` to achieve this:
```js
navigation.getParent().openDrawer();
```
However, this is prone to error if we nest another navigator inside (e.g. a stack). So we need a way to distinguish between which drawer we want to target.
An alternative way to distinguish different …
=> feat: add an ID prop to navigators

CONTRIBUTING.md, package.json
Clean-up PR removing references to detox as react-navigation repo doesn't use the detox package for e2e tests anymore.
- removed detox config from package.json
- updated CONTRUBUTING.md to use playwright in place of detox
=> chore: remove detox references

example/package.json, packages/bottom-tabs/package.json, packages/core/package.json, packages/devtools/package.json, packages/drawer/package.json, packages/elements/package.json, packages/flipper-plugin-react-navigation/package.json, packages/material-bottom-tabs/package.json, packages/material-top-tabs/package.json, packages/native-stack/package.json, packages/native/package.json, packages/stack/package.json, yarn.lock
**Motivation**
After the upgrade of dependencies in https://github.com/react-navigation/react-navigation/pull/10655 CI is failing while building packages. The problem seems to lay in the inconsistency of taking types from the `@types/react` package. This PR unifies the `@types/react` package version in the repository.
**Test plan**
```sh
yarn
yarn lint
yarn typescript
yarn lerna run prepare
```
=> fix: ensure same @types/react version in repo

packages/core/src/__tests__/useEventEmitter.test.tsx, packages/core/src/useChildListeners.tsx, packages/core/src/useEventEmitter.tsx
**Motivation**
This PR prevents removing more event listeners than necessary when called `unsubscribe` multiple times.
Fixes https://github.com/react-navigation/react-navigation/issues/10664
**Test plan**
Automatic tests:
```sh
yarn test
```
<details>
<summary>Manual testing snippet:</summary>
<br>
```jsx
import { createNativeStackNavigator } from '@react-navigation/native-stack';
import * as React from 'react';
import { Button, Text, View } from 'react-native';
function SettingsScreen({ navigation }: any) {
return (
<View style={{ flex: 1, alignItems: 'center', justifyContent: 'center' }}>
<Text>Settings Screen</Text>
<Button
title="Go to third"
onPress={() => navigation.navigate('nested', { screen: 'third' })}
/>
</View>
); …
```
=> fix: make event listeners idempotent

packages/native-stack/src/views/NativeStackView.native.tsx
This fix uses the top inset for iPad header height calculation in the native stack.
There is a misplaced condition that uses `&&` when it should be `||`.
I hope to have this fix in some version of `react-navigation` soon.
Fixes: #10609
=> fix: use top inset for header height on ipad

example/ios/Podfile, example/ios/Podfile.lock, example/ios/ReactNavigation.xcodeproj/project.pbxproj, example/package.json, packages/devtools/package.json, yarn.lock
Hardcoded Flipper version to 0.75.1 in Podfile caused a crash while building the Example app without the Expo. Currently used react-native 0.68 comes with Flipper v0.125.0.
- Updated Podfile lock to automatically take the correct flipper version.
- Updated `react-native-flipper` package to match the version used in Example
- Removed deprecated `react-native-appearance` which doesn't seem to be used anywhere in the repo.
```sh
yarn
yarn example ios
yarn example android
```
Ran react-navigation's plugin with the changes both on iOS and Android:
lint, typescript tests pass ✅
=> chore: update flipper

packages/native-stack/src/types.tsx, packages/native-stack/src/views/NativeStackView.native.tsx, packages/native-stack/src/views/NativeStackView.tsx
** Motivation **
This PR cleans up native-stack's new props docs and sets `gestureDirection` default value depending on `presentation` prop.
=> fix: explicitly set gestureDirection default value in native-stack

packages/native/src/index.tsx
Without this, it is impossible to build your own hooks using `getPathFromState` and `getStateFromAction`.
This addresses https://github.com/react-navigation/react-navigation/discussions/10517
**Motivation**
This lets `solito` implement a `replace('/users/fernando')` logic using URLs.
**Test plan**
It's only exporting a variable.
=> Expose `LinkingContext`

packages/core/src/useFocusEffect.tsx
Unmatched parentheses in the sample code included in the error message when an async function is passed to `useFocusEffect`.
**Motivation**
People who copy/paste from the error message and adapt it to their requirements would have a syntax error.
**Test plan**
Pass an async function to useFocusEffect, check that the parens are balanced in the sample code shown in the error message.
=> fix: typo in useFocusEffect with async function error

packages/core/src/__tests__/getStateFromPath.test.tsx, packages/native/src/__tests__/extractPathFromURL.test.tsx, packages/native/src/useLinking.native.tsx
**Motivation**
At the moment, a linking url without a path (with or without an ending slash) cannot match the linking configuration, as it is ignored.
Consider the following linking configuration:
```
{
prefixes: ['https://myapp.com/'],
config: {
screens: {
MyScreen: '',
},
},
};
```
If the received linking url is equal to `https://myapp.com/` it won't be matching `MyScreen` as the empty path is ignore. To be able to match an empty path, we need to change the path validation (see change in `useLinking.native.tsx`).
The `getStateFromPath` function is already able to match an empty string. Tests have been added to clearly expose the expected behaviour. 
**Test plan**
Use a deeplink url without a path in your app and match that deeplink in your linking configuration using an empty path.
=> Fix linking path

packages/core/src/__tests__/getPathFromState.test.tsx, packages/core/src/getStateFromPath.tsx
**Motivation**
`parseQueryParams()` could had unexpected behavior when parameter names where valid `Object.prototype` properties. For example:
```
> parseQueryParams('?toString=42', {})
[Object: null prototype] { toString: '[object Object]' }
```
The code above was returning `{toString: '[object Object]'}` instead of the expected `{toString: '42'}`.
**Test plan**
Added a unit test reproducing the bug.
=> Prevent Object properties to be used as parsing functions

packages/core/src/useEventEmitter.tsx, packages/core/src/useKeyedChildListeners.tsx
Prevent event listeners of type `"__proto__"` to pollute the global Object prototype. This is fixed by creating objects with null prototype so they don't have a `__proto__` property.
**Motivation**
I found a potential [prototype pollution vulnerability](https://raw.githubusercontent.com/HoLyVieR/prototype-pollution-nsec18/master/paper/JavaScript_prototype_pollution_attack_in_NodeJS.pdf) while reading the code of the package. I'm not sure if it has any security impact, but I think it's better to fix it anyway.
Please let me know if you need more information about this type of vulnerability and why this change is important.
**Test plan**
I tested that the changes compile ok. Also checked that no property of the Object prototype (such as `toString()` of `hasOwnProperty()`) is being accessed …
=> Fix potential prototype pollution attacks

example/types.check.tsx, packages/core/src/types.tsx
**Motivation**
Fixes #10471
If a RouteList type has a route with params set to undefined, for example:
```ts
type ExampleRouteList = {
HasArgs: {someArg?: string};
NoArgs: undefined;
};
```
Then `navigation.setParams` for `NoArgs` would be typed as `(params: Partial<unknown>): void`, since `NavigationProp` would type it as `(params: Partial<RouteList[RouteName]>): void`.
This would cause issues with `CompositeScreenProps` because a route with `undefined` params would not extend the `NavigationProp` type correctly, so that screen would not actually get all the options the parent navigators have available.
Conditionally setting `setParams` to `undefined` if `RouteList[RouteName]` extends `undefined` fixes this issue.
**Test plan**
Adding a test case in `example/types.check.tsx` for …
=> fix: wrong setParams type if route does not have params

example/src/Screens/NativeStack.tsx, example/src/Screens/SimpleStack.tsx, packages/core/src/__tests__/useOnAction.test.tsx, packages/core/src/__tests__/usePreventRemove.test.tsx, packages/core/src/types.tsx, packages/routers/src/StackRouter.tsx, packages/routers/src/__tests__/StackRouter.test.tsx
BREAKING CHANGE: Previously, `navigate` method navigated back if the screen
already exists in the stack. I have seen many people get confused by this
behavior. This behavior is also used for sending params to a previous
screen in the documentation. However, it's also problematic since it could
either push or pop the screens based on the scenario.
This removes the going back behavior from `navigate` and adds a new method
`popTo` to go back to a specific screen in the stack.
The methods now behave as follows:
- `navigate(screenName)` will stay on the current screen if the screen is
already focused, otherwise push a new screen to the stack.
- `popTo(screenName)` will go back to the screen if it exists in the stack,
otherwise pop the current screen and add this screen to the stack.
- To …
=> feat!: add `popTo` method for stack and remove going back behaviour of `navigate`

example/src/Screens/NativeStack.tsx, example/src/Screens/SimpleStack.tsx, packages/core/src/__tests__/useOnAction.test.tsx, packages/core/src/__tests__/usePreventRemove.test.tsx, packages/core/src/types.tsx, packages/routers/src/CommonActions.tsx, packages/routers/src/StackRouter.tsx, packages/routers/src/TabRouter.tsx, packages/routers/src/__tests__/CommonActions.test.tsx, packages/routers/src/__tests__/StackRouter.test.tsx, packages/routers/src/__tests__/TabRouter.test.tsx, packages/stack/src/views/Stack/StackView.tsx
BREAKING CHANGE: Previously, you could specify a route `key` to navigate to, e.g.
`navigation.navigate({ key: 'someuniquekey' })`. It's problematic since `key` is an internal
implementation detail and created by the library internally - which makes it weird to use. None
of the other actions support such usage either.
In addition, we have already added a better API (`getId`) which can be used for similar use
cases - and gives users full control since they provide the ID and it's not autogenerated by the
library.
So this change removes the `key` option from the `navigate` action.
=> refactor!: drop support for key property in navigate

example/src/index.tsx, packages/core/src/BaseNavigationContainer.tsx, packages/core/src/__tests__/BaseNavigationContainer.test.tsx, packages/core/src/types.tsx, packages/native/src/NavigationContainer.tsx
BREAKING CHANGE: Previously, the `onReady` prop and `navigationRef.isReady()` work slightly
differently. The `onReady` callback fired when `NavigationContainer` finishes mounting and deep links is resolved. The `navigationRef.isReady()` method additionally checks if there are any navigators rendered - which may not be `true` if the user is rendering their navigators conditionally inside a
`NavigationContainer`.
This changes `onReady` to work similar to `navigationRef.isReady()`. The `onReady` callback will now fire only when there are navigators rendered - reflecting the value of `navigationRef.isReady()`.
=> fix!: align onReady callback and navigationRef.isReady

packages/native-stack/src/views/NativeStackView.native.tsx
Unfortunately the changes from #10761 caused an issue I reported on the react-native-screens repo. (See software-mansion/react-native-screens#1589)
Essentially, the [documentation](https://reactnavigation.org/docs/native-stack-navigator#headerbacktitle) states that per native behavior, the back button on iOS will automatically use the title of the previous screen or "Back" if there's not enough space. However, with the latest version of react-navigation, the back button was the title of the previous screen no matter what. In some cases, this caused the title of the current screen to be completely pushed off the screen.
In UIKit this happens when the title of the back button is deliberately set, or when a custom UIBarButtonItem is set as the back button. `react-native-screens` creates a …
=> fix: restore native behavior of back button

packages/native-stack/src/__tests__/index.test.tsx, packages/native-stack/src/views/HeaderConfig.tsx, packages/native-stack/src/views/NativeStackView.native.tsx
`useHeaderHeight` should return the height of the closest header but in native-stack but it returns incorrect values.
Fixes https://github.com/react-navigation/react-navigation/issues/10333
https://user-images.githubusercontent.com/39658211/189142087-d5e2570a-3196-4034-bf25-0448c4922725.mov
https://user-images.githubusercontent.com/39658211/189142292-0c0efc03-af46-482d-ab91-e9977e67bc04.mov
https://user-images.githubusercontent.com/39658211/189142323-2985fffc-e250-4356-bb63-013f13795cdf.mov
https://user-images.githubusercontent.com/39658211/189142337-b2762252-f623-4c3a-a8ef-c034dc0cf127.mov
https://user-images.githubusercontent.com/39658211/189142594-19e5afb3-5f0b-4d6b-8269-ab923f0c1034.mp4
https://user-images.githubusercontent.com/39658211/189142666-5f0b6644-df24-433e-8a7d-5a74adaa6572.mp …
=> fix: fix useHeaderHeight in native-stack

packages/bottom-tabs/src/types.tsx, packages/bottom-tabs/src/views/BottomTabView.tsx, packages/bottom-tabs/src/views/ScreenFallback.tsx, packages/drawer/src/types.tsx, packages/drawer/src/views/DrawerView.tsx, packages/drawer/src/views/ScreenFallback.tsx, packages/native-stack/src/types.tsx, packages/native-stack/src/views/NativeStackView.native.tsx, packages/stack/src/types.tsx, packages/stack/src/views/Screens.tsx, packages/stack/src/views/Stack/CardStack.tsx
Since version v3.9.0 `react-native-screens` exposed `enableFreeze()` function which allows to suspend all hidden screens from rendering with the use of `react-freeze` library.
This PR adds a new prop called `freezeOnBlur` which makes it possible to decide per screen which screen should be suspended from rendering.
This feature needs `react-native-screens` with version >=3.16 so as of today we're not able to test this prop within Expo Go.
`yarn up react-native-screens`
`yarn example ios`
`yarn example android`
Only a visible screen should `console.log` in native-stack. 
In stack, two top-most screens should `console.log`.
<details>
<summary>Code example for Stack and Native-Stack</summary>
<br>
```jsx
// import { …
```
=> feat: add freezeOnBlur prop 

packages/stack/src/views/Stack/Card.tsx
Changed introduced in https://github.com/react-navigation/react-navigation/pull/10767 created a regression reported in https://github.com/react-navigation/react-navigation/issues/10856 which made it impossible to close a modal with a gesture.
As we want to change pointer-events on Card in `componentDidUpdate` previous use of `setNativeProps` in this context made a lot of sense. Since `setNativeProps` is going to be removed in the new architecture we had to migrate it to the component state as stated [in the migration guide](https://reactnative.dev/docs/next/new-architecture-library-intro#moving-setnativeprops-to-state).
This PR adds an additional `closing !== prevProps.closing` check on top of https://github.com/react-navigation/react-navigation/pull/10767 within `componentDidUpdate` in …
=> fix: add additional check before running `animate` in `componentDidUpdate`

packages/bottom-tabs/package.json, packages/bottom-tabs/src/navigators/createBottomTabNavigator.tsx, packages/drawer/package.json, packages/drawer/src/navigators/createDrawerNavigator.tsx, packages/material-top-tabs/package.json, packages/material-top-tabs/src/navigators/createMaterialTopTabNavigator.tsx, packages/stack/package.json, packages/stack/src/navigators/createStackNavigator.tsx, yarn.lock
PR removes deprecation warnings introduced in https://github.com/react-navigation/react-navigation/commit/8e0ae5fc79dc7de1fe39e867184233958e3f82bd
=> refactor!: remove deprecated options & warnings

packages/stack/src/views/Stack/Card.tsx, packages/stack/src/views/Stack/CardSheet.tsx
This PR is a third attempt to migrate `setNativeProps` to state in @react-navigation/stack following official [Moving setNativeProps to state](https://reactnative.dev/docs/next/new-architecture-library-intro#moving-setnativeprops-to-state) guide.
After issues with the implementation of https://github.com/react-navigation/react-navigation/pull/10767 and more problems with the fix in https://github.com/react-navigation/react-navigation/pull/10871 we had to take a step back and rethink where the problem lays with these implementations.
The solution was to move the state inside the CardSheet component and use `useImperativeHandle` to hoist a setter function up to Card to avoid triggering a rerender during Card `animate` function. 
Thanks so much @satya164 for pointing that out! …
=> fix: migrate setNativeProps to state

packages/elements/src/Header/getDefaultHeaderHeight.tsx, packages/native-stack/src/views/NativeStackView.native.tsx, packages/stack/src/TransitionConfigs/CardStyleInterpolators.tsx
**Motivation**
This PR supersedes a deprecated `Platform.isTVOS` which got removed in https://github.com/facebook/react-native/pull/34071 for the currently used standard - a `Platform.isTV` check.
`Platform.isTV` check exists since react-native `v0.61` that way no breaking changes are introduced to react-navigation.
Ref: https://github.com/software-mansion/react-native-screens/pull/1605
=> fix: supersede Platform.isTVOS for Platform.isTV

packages/native-stack/src/views/HeaderConfig.tsx
**Motivation**
As reported in [#10845](https://github.com/react-navigation/react-navigation/issues/10845), the behavior that native software in the iOS ecosystem applies is that even transparent headers _can_ have a border in the NavigationBar/TopBar. In React Navigation, it was assumed that `headerTransparent=true` would also imply `hideShadow=true`, which would prevent this behavior (and therefore, make the behavior of this library inconsistent with native apps)
This fix allows the behavior to continue on Android, while allowing the native iOS behavior to be present (also providing the option to hide it forcefully).
Issue here: https://github.com/react-navigation/react-navigation/issues/10845
**Test plan**
- Configure a NativeStack to have a transparent header on iOS
- Observe that this …
=> HeaderConfig: Updates hideShadow to allow native iOS behavior to be applied

packages/bottom-tabs/package.json, packages/core/package.json, packages/devtools/package.json, packages/drawer/package.json, packages/elements/package.json, packages/material-bottom-tabs/package.json, packages/material-top-tabs/package.json, packages/native-stack/package.json, packages/native-stack/src/__tests__/index.test.tsx, packages/native-stack/src/views/NativeStackView.native.tsx, packages/native/package.json, packages/stack/package.json, yarn.lock
**Motivation**
Current Stack navigator (and other navigations) have accessibility props like `importantForAccessbility` & `accessibilityElementsHidden` for screens that are not currently visible on the screen. However, NativeStack navigator does not have it, which breaks new React Native Testing Library [`includeHiddenElements`](https://callstack.github.io/react-native-testing-library/docs/api-queries#includehiddenelements-option) query options which allows for ignoring elements hidden from accessibility.
As far as I understand this works correctly with iOS/Android screen readers because of using native primitives which are understood by screen readers/assistive tech. This PR includes the two accessibility props which should cause no harm to React Navigation user but would support RNTL …
=> fix: add accessibility props to NativeStack screens

packages/material-top-tabs/src/types.tsx, packages/material-top-tabs/src/views/MaterialTopTabBar.tsx
This PR replaces #10984
**Motivation**
the new `tabBarGap` option helps to configure `gap` option of `react-native-tab-view` : see https://github.com/react-navigation/react-navigation/tree/main/packages/react-native-tab-view#gap
**Test plan**
Just set a tabBarGap option and check that there is a gap between tabs
=> feat: expose tabBarGap option in material top tabs

packages/react-native-tab-view/src/TabBar.tsx, packages/react-native-tab-view/src/TabBarIndicator.tsx
**Motivation**
As reported here: https://github.com/satya164/react-native-tab-view/issues/1405, when using really long lists header wouldn't get all tab widths and therefore would stop rendering. If we have more than 10 routes we split rendering into multiple batches using onViewableItemsChanged.
**Test plan**
https://user-images.githubusercontent.com/52801365/204381404-47fe743c-e79a-45ba-9c05-08c8cdd9f92e.mp4
Launch Scrollable tab bar example and scroll.
=> feat: split updating state to batches on long lists

packages/bottom-tabs/src/utils/useBottomTabBarHeight.tsx
discrepancy makes it harder for consumers of this package to understand the internals
I've removed the template because of how simple this change is. Let me know if y'all would like me to expound on my reasoning for opening this.
=> refactor: use consistent naming for useBottomTabBarHeight

packages/core/package.json, yarn.lock
fix vulnerability in decode-uri-component, dependency of query-string, fixed in version 7.1.3
more info
https://security.snyk.io/vuln/SNYK-JS-DECODEURICOMPONENT-3149970
=> fix: bump query-string version

packages/drawer/src/index.tsx, packages/drawer/src/utils/DrawerStatusContext.tsx
**Motivation**
`DrawerStatusContext` should be exported and available to the library's users.
For example, someone might want to create a custom Drawer navigator using `useNavigationBuilder` and reuse this context.
(Previous PR: https://github.com/react-navigation/react-navigation/pull/10976)
=> fix: drawerstatuscontext should be exported

packages/native/src/createMemoryHistory.tsx
**Motivation**
Fixes this issue that I discovered https://github.com/react-navigation/react-navigation/issues/11026
**Test plan**
1. Run the example
2. Visit http://localhost:19006/simple-stack/article/gandalf#test
3. The with #test part still exists
4. Note that if you change the hash it will be gone (this is expected)
=> fix: keep hash/fragment section for initial render

packages/native/src/useScrollToTop.tsx
**Motivation**
This PR answers this open issue: https://github.com/react-navigation/react-navigation/issues/11045
When tapping on a bottom tab, the screen scrolls back to the top. However, when adding a second tab navigator at the top of the screen, tapping the bottom tap does not automatically scroll to top anymore. Only tapping the top navigation tab will scroll the screen up. It is expected that the bottom tab tap will still scroll the screen to the top, just like tapping the status bar.
**Context**
This issue has previously been reported [here](https://github.com/react-navigation/react-navigation/issues/8586) by [@iirovi](https://github.com/iirovi), and a pull request to fix the issue has been proposed by [@Gregoirevda](https://github.com/Gregoirevda) …
=> Fix useScrollToTop not working when nesting multiple tab navigators

packages/elements/src/Header/HeaderTitle.tsx
follow-up on https://github.com/react-navigation/react-navigation/pull/10449
**Motivation**
I have a custom header which looks like this:
```
import {HeaderTitle} from '@react-navigation/elements'
export const MyStackHeader = (props: StackHeaderProps) => {
return (
<HeaderTitle {...props}>
<Text style={{color: 'red'}}>red</Text>
<Text>black</Text>
</HeaderTitle>
)
}
...
// used then as follows
headerTitle: MyStackHeader,
```
Nesting <Text> is valid with `Animated.Text`, but with `HeaderTitle`, TS complains because it expects `children: string`. But because `HeaderTitle` is based on `Animated.Text`, it should allow such construct as well - it does work just fine at runtime.
**Test plan**
works fine:
=> fix: allow complex children in HeaderTitle

packages/stack/src/types.tsx
Fixes a typo in headerBackTickVisible description after `false` keyword. (missing backtick)
```typescript
/**
* Whether the back button title should be visible or not.
*
* Defaults to `true` on iOS, `false on Android.
*/
headerBackTitleVisible?: boolean;
```
=> docs: fix typo

packages/native-stack/src/views/HeaderConfig.tsx
**Motivation**
Currently, using a transparent header on native-stack shows the headerBackground with iOS, but **not** with Android, resulting in a completely transparent background and headerBackground not visible. It might not be clear when this is useful, but opacity interpolation based on scroll position is one use-case where this is needed.
https://user-images.githubusercontent.com/25879490/208209362-04d4aef9-53d8-4e2e-9187-4000bd7153b8.mov
https://user-images.githubusercontent.com/25879490/208209359-5eed0cfc-71e6-4d94-96b8-4ae344ed620f.mov
https://user-images.githubusercontent.com/25879490/208209361-9db44bf8-b68d-4afb-83e5-8f67449e4fe2.mov
```ts
useLayoutEffect(() => {
const transparencyInterpolation = scrollOffset.interpolate({
inputRange: [NAVIGATION_START_FADE_Y, …
```
=> fix: make headerBackground visible with transparent header

packages/drawer/src/views/DrawerItem.tsx
Added support for testIDs for the tappable DrawerItem and the DrawerItem label
Addresses https://github.com/react-navigation/react-navigation/issues/7492 and https://github.com/react-navigation/react-navigation/issues/8906
This was attempted before with https://github.com/react-navigation/react-navigation/pull/11009 but that PR was closed due to an update in the main branch.
=> feat: add testID and accessibilityLabel to DrawerItem

example/src/index.tsx, packages/drawer/src/types.tsx, packages/drawer/src/views/DrawerView.tsx, packages/drawer/src/views/legacy/Drawer.tsx, packages/drawer/src/views/legacy/Overlay.tsx, packages/drawer/src/views/modern/Drawer.tsx, packages/drawer/src/views/modern/Overlay.tsx
**Motivation**
Currently, a user can tap the `Overlay` next to an open drawer to close the drawer. This is useful in an Accessibility setting when swipe actions are not obvious to the user. Unfortunately, it is not obvious to someone with a visual deficit that this area can be tapped to close the drawer, as this overlay does not have an accessibilityLabel prop exposed. 
This PR exposes an `accessibilityLabel` prop on this overlay component and modifies existing accessibility props to allow for accessibility tap permissions on the overlay component. It then surfaces this prop at the `Drawer` level as `closeAccessibilityLabel`.
**Test plan**
Open up the example app with TalkBack (Android) or VoiceOver (iOS) enabled. Tap on the overlay next to the drawer and observe that it will now read out …
=> fix: added close drawer accessibility tap area

packages/react-native-tab-view/README.md, packages/react-native-tab-view/src/TabView.tsx
Add support to override pager's overScrollMode.
**Motivation**
The default value of `overScrollMode` in `react-native-pager-view` is set to `auto`, which makes the first and last scenes streched when over scroll the `TabView`. We should provide a way to change the default behavior.
=> feat: add support to override pager's overScrollMode

packages/native/src/useScrollToTop.tsx
Recreation of https://github.com/react-navigation/react-navigation/pull/10775 due to the git changes.
**Motivation**
Close https://github.com/react-navigation/react-navigation/issues/10722
`getScrollResponder` has a type error around `SectionList` due to missing type for `SectionList`
-----
FlatList - https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-native/index.d.ts#L4057
```ts
getScrollResponder: () => JSX.Element | null | undefined;
```
SectionList - https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-native/index.d.ts#L4294
```ts
getScrollResponder(): ScrollView | undefined;
```
**Test plan**
Use
- `@types/react`: `^18.0.15` 
- `@react-navigation/native`: `ken0nek/react-navigation.git#react-navigation-native-v6.1.1-gitpkg`
Check no …
=> fix: add `ScrollView` type to 'getScrollResponder'

packages/material-top-tabs/src/types.tsx, packages/material-top-tabs/src/views/MaterialTopTabBar.tsx, packages/react-native-tab-view/src/TabBar.tsx, packages/react-native-tab-view/src/TabBarItem.tsx
**Motivation**
This PR solves an issue with setting transparent background color of tab-view on Android. It allows users to overwrite `android_ripple` config. (#11198) 
https://user-images.githubusercontent.com/52801365/217030596-4a4fe2ce-c974-4c37-b3ee-84733bf1eb79.mp4
**Test plan**
Run the test app, passing `{ backgroundColor: transparent }` to tabBar.
=> fix: allow users to pass `android_ripple` config in TabView

packages/stack/src/views/Stack/CardStack.tsx
We got a custom `cardStyleInterpolator` in our app that actually calls [forModalPresentationIOS](https://github.com/react-navigation/react-navigation/blob/main/packages/stack/src/TransitionConfigs/CardStyleInterpolators.tsx#L93) but we add some own customizations to it. This worked fine in `v5` of react-navigation, and started to act weird after the upgrade to `v6`, the screen under the modal was displayed right until the animation was finished, then the screen under disappeared, which is unintended.
This PR just checks for the name instead. Making it do the same as this check: https://github.com/react-navigation/react-navigation/blob/main/packages/stack/src/views/Stack/Card.tsx#L580 and will allow for custom cardStyleInterpolators.
This can be reproduced by creating your own …
=> fix: Check cardStyleInterpolator name to allow for custom animation as well

packages/bottom-tabs/src/views/Badge.tsx, packages/bottom-tabs/src/views/BottomTabItem.tsx, packages/drawer/src/views/DrawerItem.tsx, packages/elements/src/Header/HeaderBackButton.tsx, packages/elements/src/Header/HeaderTitle.tsx, packages/material-top-tabs/src/views/MaterialTopTabBar.tsx, packages/native-stack/src/views/HeaderConfig.tsx, packages/native/src/theming/DarkTheme.tsx, packages/native/src/theming/DefaultTheme.tsx, packages/native/src/theming/fonts.tsx, packages/native/src/types.tsx
**Motivation**
React Navigation 5 introduced a theming API. However, the theme only supported customizing colors. With this change, the theme can be used to customize font family as well - making it simpler to use a specific font across all of React Navigation's UI elements.
**Test plan**
Specify a custom font in the theme and check that React Navigation's UI elements use the new font. The following screenshots show the usage of the "Lato" font.
=> feat: add ability to customize the fonts with the theme

packages/react-native-tab-view/src/TabBarItem.tsx, packages/react-native-tab-view/src/TabBarItemLabel.tsx
**Motivation**
The goal of this PR is to memoize the result of getter functions passed to TabBarItem like: `getAccessibilityLabel()`. This is currently _the best_ we can do to optimize material-top-tabs re-renders.
**Test plan**
Go to Material top tabs example and examine re-renders using React Profiler.
=> fix: optimize tabBarItem by memoizing getter functions

example/src/Screens/TabView/AutoWidthTabBar.tsx, example/src/Screens/TabView/CustomIndicator.tsx, example/src/Screens/TabView/ScrollableTabBar.tsx, example/src/Screens/TabView/TabBarIcon.tsx, packages/react-native-tab-view/src/TabBar.tsx, packages/react-native-tab-view/src/TabBarIndicator.tsx
Use `padding(Horizontal|Left|Right)` values on `contentContainerStyle` for better styling on TabBar in `react-native-tab-view`
**Motivation**
Useful to create a custom style or adding insets values on left and right padding on contentContainer.
Use case is similar to existing `gap` prop (that I also fixed in this PR)
It's also fix #8667 
**Test plan**
I use TabViews existing examples, I adding `gap` and `contentContainerStyle` `paddingHorizontal` to AutoWidthTabBar, CustomIndicator, ScrollableTabBar and TabBarIcon.
=> Tabview tabbar horizontal padding for contentContainer

packages/native-stack/src/views/DebugContainer.native.tsx, packages/native-stack/src/views/NativeStackView.native.tsx
**Motivation**
`UIKit` requires `ScrollView` to be at index 0 in given view's subview array to enable it's interaction with navigation bar. On Fabric `DebugContainer` view got flattened, however it was not removed from hierarchy -- instead the view was attached as first child of the `RNSScreenView` disabling system interaction between navigation bar and a scroll view. 
See
* https://github.com/software-mansion/react-native-screens/pull/1825
for broader context and explanation.
**Test plan**
https://github.com/software-mansion/react-native-screens/assets/50801299/3b89dee8-a307-44ba-a9f4-02e4dfdd95ac
https://github.com/software-mansion/react-native-screens/assets/50801299/205f24d4-590b-402e-8b0a-848fd4482d59
=> fix: buggy behaviour of search bar / large title on Fabric with native stack v7

packages/native-stack/src/views/DebugContainer.native.tsx, packages/native-stack/src/views/NativeStackView.native.tsx
**Motivation**
`UIKit` requires `ScrollView` to be at index 0 in given view's subview array to enable it's interaction with navigation bar. On Fabric `DebugContainer` view got flattened, however it was not removed from hierarchy -- instead the view was attached as first child of the `RNSScreenView` disabling system interaction between navigation bar and a scroll view. 
See
* https://github.com/software-mansion/react-native-screens/pull/1825
for broader context and explanation.
**Test plan**
https://github.com/software-mansion/react-native-screens/assets/50801299/3b89dee8-a307-44ba-a9f4-02e4dfdd95ac
https://github.com/software-mansion/react-native-screens/assets/50801299/205f24d4-590b-402e-8b0a-848fd4482d59
=> fix: buggy behaviour of search bar / large title on Fabric with native stack v6

example/src/Screens/BottomTabs.tsx, packages/bottom-tabs/src/views/BottomTabView.tsx
**Motivation**
Follow-up after the previous PR, when we used only the upper-most descriptor. Also, example has been adjusted to use either fully turned on or off animation., 
**Test plan**
press the button
=> fix: bottom bar animation tied with a screen

example/package.json, example/src/Screens/BottomTabs.tsx, example/src/Screens/NativeStackHeaderCustomization.tsx, example/src/Screens/Static.tsx, example/src/Screens/TabView/TabBarIcon.tsx, example/src/index.tsx, packages/bottom-tabs/package.json, packages/bottom-tabs/src/types.tsx, packages/bottom-tabs/src/views/BottomTabItem.tsx, packages/bottom-tabs/src/views/TabBarIcon.tsx, packages/drawer/package.json, packages/drawer/src/types.tsx, packages/drawer/src/views/DrawerItem.tsx, packages/elements/src/Header/HeaderTitle.tsx, packages/elements/src/MissingIcon.tsx, packages/elements/src/types.tsx, packages/material-top-tabs/src/types.tsx, packages/native-stack/package.json, packages/native-stack/src/types.tsx, packages/native/src/types.tsx, packages/react-native-tab-view/src/TabBar.tsx, packages/react-native-tab-view/src/TabBarItem.tsx, packages/react-native-tab-view/src/TabBarItemLabel.tsx, packages/stack/package.json, yarn.lock
Fix: https://github.com/react-navigation/react-navigation/issues/11481
=> fix: Allow to use `PlatformColor` in the theme

packages/native/src/__tests__/extractPathFromURL.test.tsx, packages/native/src/extractPathFromURL.tsx
**Motivation**
fix: https://github.com/react-navigation/react-navigation/issues/10924
**Test plan**
```tsx
import extractPathFromURL from '@react-navigation/native/src/extractPathFromURL';
test('extractPathFromURL', () => {
expect(extractPathFromURL(['https://mysite.com'], 'https://mysite.com/readPolicy?url=https://test.com')).toBe(
'/readPolicy?url=https://test.com',
);
});
// test fail ^^^ because `extractPathFromURL` removed all double slashes
// Expected: "/readPolicy?url=https://test.com"
// Received: "/readPolicy?url=https:/test.com"
```
=> fix: incorrect url parsing (isssue: #10924)

packages/native/src/__tests__/NavigationContainer.test.tsx, packages/native/src/useLinking.tsx
**Motivation**
This function is used to ensure that all state change callbacks to sync the local browser history state run in series. The functions are async because `history.go` is not a synchronous function.
I noticed that in chrome, the URL was updating to the previous url instead of the new one in some navigations and tracked it down to the fact that the `history.go` navigation takes longer than in other browsers. This function is supposed to mitigate that, but I believe it has a bug. The function will not properly return early, because the finally clause will still always run and immediately reset the `isRunning` state. Even after fixing this, the function didn't quite work right for queuing more than two callbacks.
I have replaced the function with a simpler implementation that does …
=> fix: replace series function used to queue async callbacks

example/src/Screens/BottomTabs.tsx, packages/core/src/useRouteCache.tsx
Optimize route cache to prevent re-rendering.
**Motivation**
Routes shouldn't re-render, we are now using route key as the cache key
=> fix: optimize route cache

example/src/Restart.native.tsx, example/src/Restart.tsx, example/src/Screens/SimpleStack.tsx, example/src/index.tsx, packages/drawer/src/views/DrawerContentScrollView.tsx, packages/drawer/src/views/DrawerView.tsx, packages/elements/src/Header/HeaderBackButton.tsx, packages/native-stack/src/views/HeaderConfig.tsx, packages/native/src/LocaleDirContext.tsx, packages/native/src/NavigationContainer.tsx, packages/native/src/index.tsx, packages/native/src/types.tsx, packages/native/src/useLocale.tsx, packages/react-native-drawer-layout/src/views/legacy/Drawer.tsx, packages/react-native-drawer-layout/src/views/modern/Drawer.tsx, packages/react-native-tab-view/src/types.tsx, packages/stack/src/TransitionConfigs/HeaderStyleInterpolators.tsx, packages/stack/src/navigators/createStackNavigator.tsx, packages/stack/src/types.tsx, packages/stack/src/utils/getDistanceForDirection.tsx, packages/stack/src/utils/getInvertedMultiplier.tsx, packages/stack/src/views/Header/HeaderSegment.tsx, packages/stack/src/views/Stack/Card.tsx, packages/stack/src/views/Stack/CardContainer.tsx, packages/stack/src/views/Stack/CardStack.tsx, packages/stack/src/views/Stack/StackView.tsx
BREAKING CHANGE: Previously the navigators tried to detect RTL automatically and
adjust the UI. However this is problematic since we cannot detect RTL in all cases
(e.g. on Web).
This adds an optional `direction` prop to `NavigationContainer` instead
so that user can specify when React Navigation's UI needs to be adjusted for RTL. It defaults to the value from `I18nManager` on native platforms, however it needs to be explicitly passed for Web.
=> feat!: add a direction prop to NavigationContainer to specify rtl

packages/react-native-tab-view/src/TabBarIndicator.tsx
**Motivation**
I want to be able to display a `<LinearGradient/>` component inside the `<TabBarIndicator/>`. While you can use the `renderIndicator` prop on `TabBar`, you cannot render a wrapper or child of the indicator and have it inherit the animation the library already provides. By providing a `children` option to `TabBarIndicator`, this problem is easily solved.
**Test plan**
Tests all still pass and to test this specific change, try something like this:
```
<TabBar
renderIndicator={(props) => {
return (
<TabBarIndicator {...props}>
{someChildComponent}
</TabBarIndicator>
)
}}
/>
```
This allows more complex components to be animated and accurately denote the active tab. I have some screenshots of an example where I'm using a `<LinearGradient/>` container to display a gradient …
=> feat: add children prop to tab bar indicator component

packages/bottom-tabs/src/views/BottomTabBar.tsx, packages/bottom-tabs/src/views/BottomTabItem.tsx, packages/elements/src/Label/Label.tsx, packages/elements/src/Label/getLabel.tsx, packages/elements/src/index.tsx
**Motivation**
Moves the default label component to the elements package, similar to the HeaderTitle component.
It uses logic similar to the Header element component.
Please let me know if this was not the intended refactor, I can fix it.
**Test plan**
There should be no visible changes in the bottom tabs examples in the example app.
=> refactor: export label from bottom-tabs to elements package

example/src/Screens/BottomTabs.tsx, packages/bottom-tabs/src/types.tsx, packages/bottom-tabs/src/views/BottomTabBar.tsx, packages/bottom-tabs/src/views/BottomTabItem.tsx, packages/bottom-tabs/src/views/BottomTabView.tsx, packages/bottom-tabs/src/views/TabBarIcon.tsx, packages/drawer/src/views/DrawerView.tsx, packages/elements/src/getDefaultSidebarWidth.tsx, packages/elements/src/index.tsx
**Motivation**
This adds ability to render the tab bar on left/right as a sidebar. It useful on larger screens where we may want to take advantage of the available horizontal screen and show a sidebar instead of a bottom tab bar.
**Test plan**
Open the "Bottom Tabs" example and resize the screen to see the different modes of the tab bar. Tap on the "<<" button on the bottom left to switch between a smaller and larger sidebar.
**Video**
https://github.com/react-navigation/react-navigation/assets/1174278/224beaa9-8e26-4d94-a70d-11e54c37d944
=> feat: add option to show tabs on the side

packages/bottom-tabs/src/views/BottomTabItem.tsx
**Motivation**
#11246 refactored the usage of the label, during which the `tintColor` was not forwarded to the new `Label` component. This PR forwards the `tintColor` derived from `options` using `tabBarActiveTintColor` and `tabBarActiveTintColor` to the `Label` component reverting the UI with the previously expected colors.
**Test plan**
There are some visible changes and the following are the steps to see the change
- Run the app
- Go to `Bottom Tabs`
- Before this PR, the color of the label for the active tab was based on `tintColor` from the theme and not the `tintColor` from options passed to the screen (`tabBarActiveTintColor` and `tabBarActiveTintColor`).
- In this PR, notice the color of the label changes according to the `tintColor` from screen options.
> Note: The color …
=> fix: pass `tintColor` to `Label`

packages/core/src/BaseNavigationContainer.tsx
Before, we observed that `onReady` was not called as the component was re-rendered (hence, `isReady() not called`. 
**Test plan**
Add a console.log to `<NavigationContainer onReady={cosole.log} />`
=> fix: onReady not getting called on native

example/src/Screens/CustomLayout.tsx, example/src/screens.tsx, packages/bottom-tabs/src/navigators/createBottomTabNavigator.tsx, packages/core/src/types.tsx, packages/core/src/useNavigationBuilder.tsx, packages/drawer/src/navigators/createDrawerNavigator.tsx, packages/material-top-tabs/src/navigators/createMaterialTopTabNavigator.tsx, packages/native-stack/src/navigators/createNativeStackNavigator.tsx, packages/stack/src/navigators/createStackNavigator.tsx
**Motivation**
This adds a new `layout` prop to navigators. It can be useful for augmenting the navigators with additional UI with a wrapper. The difference from adding a regular wrapper is that the code in `layout` callback has access to the navigator's state, options etc.
**Test plan**
Tested by implementing a breadcrumb UI in stack navigator in the example app.
https://github.com/react-navigation/react-navigation/assets/1174278/5ee2b7f5-f000-4d43-a147-33a1e1562b4c
=> feat: add a layout prop for navigators

packages/bottom-tabs/src/TransitionConfigs/SceneStyleInterpolators.tsx
**Motivation**
Noticed tabs were 1px off to the right when I was testing the new bottom-tab animations, the ShiftingTransition Present in the alpha.
**Test plan**
install:
`"@react-navigation/bottom-tabs": "^7.0.0-alpha.4",`
`"@react-navigation/core": "^7.0.0-alpha.3",`
`"@react-navigation/elements": "^2.0.0-alpha.1",`
`"@react-navigation/native": "^7.0.0-alpha.3",`
`"@react-navigation/native-stack": "^7.0.0-alpha.4",`
`"@react-navigation/stack": "^7.0.0-alpha.4",`
create Tab Navigator with these screen options:
```
const Tab = createBottomTabNavigator<TabsNavigatorStack>();
const animation = TransitionPresets.ShiftingTransition;
const screenOptions = {
headerShown: false,
animationEnabled: true,
...animation,
};
....
<Tab.Navigator
initialRouteName={...}
screenOptions={screenOptions}
> …
```
=> fix: forShifting bottom-tabs animation

packages/stack/src/views/Stack/CardSheet.tsx
**Motivation**
Related to https://github.com/react-navigation/react-navigation/issues/11274 and https://github.com/Expensify/App/issues/15749.
In mobile Chrome, the address bar collapses, which causes some problems: in an SPA and using a `flex: 1; height: 100%` style for the document, if the navigation is made with the address bar collapsed, it will show an empty space at the bottom of the screen (only visible if there are differences in background color). 
A possible fix is updating the body height using viewport height units based on the `window.innerHeight`, which should have the correct height taking into consideration the collapsed address bar. 
Resources:
- https://developer.chrome.com/blog/url-bar-resizing/
- https://css-tricks.com/the-trick-to-viewport-units-on-mobile/ 
**Test …
=> fix: workaround for mChrome empty space when navigating after address bar collapses

packages/bottom-tabs/src/views/BottomTabItem.tsx, packages/drawer/src/views/DrawerItem.tsx, packages/drawer/src/views/DrawerToggleButton.tsx, packages/elements/src/Header/HeaderBackButton.tsx, packages/elements/src/Header/HeaderBackContext.tsx, packages/elements/src/PlatformPressable.tsx, packages/elements/src/types.tsx, packages/native-stack/src/types.tsx, packages/native-stack/src/views/NativeStackView.native.tsx, packages/native-stack/src/views/NativeStackView.tsx, packages/native/src/useLinkProps.tsx, packages/stack/src/types.tsx, packages/stack/src/views/Header/Header.tsx, packages/stack/src/views/Header/HeaderContainer.tsx, packages/stack/src/views/Header/HeaderSegment.tsx, packages/stack/src/views/Stack/CardContainer.tsx
**Motivation**
In order to make the react-navigation web experience more 'native' this PR brings a link to a header back button. This makes UX more natural as users could now right-click to open a route in new tab or hover over to see where does 'go back' leads them.
<details>
<summary>Code example</summary>
<br>
```tsx
import { createStackNavigator } from '@react-navigation/stack';
import { createURL } from 'expo-linking';
import * as React from 'react';
import { Button, StyleSheet, View } from 'react-native';
function FirstScreen({ navigation }: any) {
return (
<View style={styles.container}>
<Button
title="Go to second"
onPress={() => navigation.navigate('second')}
/>
</View>
);
}
function SecondScreen({ navigation }: any) …
```
=> feat!: add href to back button

packages/core/src/__tests__/index.test.tsx, packages/core/src/useNavigationBuilder.tsx
BREAKING CHANGE:
Previously when using nested navigation API, we used that screen as `initialRouteName`.
e.g.
```js
navigation.navigate('MyScreen', { screen: 'NestedScreen' });
```
Here, the `'NestedScreen'` will be set as `initialRouteName`.
It has the result of rendering the navigator with that screen as focused screen. While this behaviour is expected, that screen was also used as the `initialRouteName` for every other operation ignoring the `initialRouteName` prop - which is not expected.
This change refactors the way the focused screen for initial render is set to avoid this behavior.
=> fix!: don't use screen from params as initialRouteName

packages/native-stack/src/types.tsx, packages/native-stack/src/views/NativeStackView.native.tsx
**Motivation**
This PR renames `customAnimationOnGesture` native-stack prop to `animationMatchesGesture` for `react-navigation` v7.
`customAnimationOnGesture` makes you think this prop takes an object with an animation provided by the developer. In reality, it's just a boolean flag that `animationMatchesGesture` name reflects better.
**Test plan**
<details>
<summary>Code example</summary>
<br>
```jsx
import { createNativeStackNavigator } from '@react-navigation/native-stack';
import * as React from 'react';
import { Button, Text, View } from 'react-native';
function HomeScreen({ navigation }) {
return (
<View
style={{
flex: 1,
alignItems: 'center',
justifyContent: 'center',
backgroundColor: 'papayawhip',
}}
>
<Text>Home …
```
=> feat!: rename customAnimationOnGesture prop

packages/core/package.json, packages/drawer/package.json, packages/native/package.json, packages/react-native-drawer-layout/package.json, packages/react-native-tab-view/package.json, yarn.lock
upgrade version of use-latest-callback which contains the fix issue not able to locate the main file
**Motivation**
I encounter the issue below after install latest version of @react-navigation/core and it is the same with this issue https://github.com/react-navigation/react-navigation/issues/11690
@satya164 already fixed the issue in this pr: 
https://github.com/satya164/use-latest-callback/pull/5
```bash
iOS Bundling failed 1448ms
Unable to resolve "use-latest-callback" from "node_modules/@react-navigation/core/src/PreventRemoveProvider.tsx"
```
```bash
Metro has encountered an error: While trying to resolve module `use-latest-callback` from file `../node_modules/@react-navigation/core/src/PreventRemoveProvide …
```
=> fix: cannot resolve use-latest-callback

example/src/Screens/StackHeaderCustomization.tsx, example/src/Screens/Static.tsx, packages/core/src/BaseNavigationContainer.tsx, packages/core/src/__tests__/theming.test.tsx, packages/core/src/index.tsx, packages/core/src/theming/ThemeContext.tsx, packages/core/src/theming/ThemeProvider.tsx, packages/core/src/theming/useTheme.tsx, packages/core/src/types.tsx, packages/core/src/useDescriptors.tsx, packages/native/src/Link.tsx, packages/native/src/NavigationContainer.tsx, packages/native/src/index.tsx, packages/native/src/theming/ThemeContext.tsx, packages/native/src/types.tsx
This moves theming logic to `@react-navigation/core`. So we can now pass the `theme` to the `options` and `screenOptions` callbacks. As `options` often specifies UI elements and styles, it's nice to have theme available there.
=> feat: move theming to core and pass theme to options

example/src/Screens/Layouts.tsx, example/src/screens.tsx, packages/core/src/__tests__/useDescriptors.test.tsx, packages/core/src/types.tsx, packages/core/src/useDescriptors.tsx, packages/core/src/useNavigationBuilder.tsx, packages/drawer/src/navigators/createDrawerNavigator.tsx, packages/material-top-tabs/src/navigators/createMaterialTopTabNavigator.tsx, packages/native-stack/src/navigators/createNativeStackNavigator.tsx, packages/stack/src/navigators/createStackNavigator.tsx
**Motivation**
This adds a new `layout` prop that can be used to wrap screens.
It makes it easier to provide things such as a global error boundary and suspense fallback for a group of screens without having to manually add HOCs for every screen separately.
See https://github.com/react-navigation/react-navigation/discussions/11152
**Test plan**
This adds unit tests for testing, as well as a demo screen in the example app showing error boundary and suspense using the `layout` prop.
https://github.com/react-navigation/react-navigation/assets/1174278/545f7bef-e087-45e9-800a-ed9fbded5166
=> feat: add layout and screenLayout props for screens

packages/elements/src/Header/HeaderBackButton.tsx
**Motivation**
This API is "deprecated" according to `react-native-web` so we get the following warning whenever anyone attempts to render React Navigation: `Warning: "transform" style array value is deprecated. Use space-separated string functions, e.g., "scaleX(2) rotateX(15deg)".`
**Test plan**
=> chore: update transform style for web

example/src/Screens/TabPreloadFlow.tsx, packages/bottom-tabs/src/__tests__/index.test.tsx, packages/core/src/types.tsx, packages/drawer/src/__tests__/index.test.tsx, packages/material-top-tabs/src/views/MaterialTopTabView.tsx, packages/react-native-tab-view/src/TabView.tsx, packages/routers/src/CommonActions.tsx, packages/routers/src/StackRouter.tsx, packages/routers/src/__tests__/StackRouter.test.tsx, packages/stack/src/__tests__/index.test.tsx
=> chore: move removePreload to the stack router and enable preloading in the material-top-tabs

example/src/Screens/StackPreloadFlow.tsx, packages/routers/src/CommonActions.tsx, packages/routers/src/StackRouter.tsx, packages/routers/src/TabRouter.tsx, packages/routers/src/__tests__/StackRouter.test.tsx, packages/stack/src/__tests__/index.test.tsx, packages/stack/src/views/Stack/CardStack.tsx
The changes are pretty straightforward and should be expressive enough to understand by reading the codebase. This PR:
- Adds the new retaining feature including changes in the router and minor changes in the card stack (as temporarily scene can include both the preloaded route and the one getting detached ) 
- Moves around some leftovers from the previous PR (#11758 )
- Adds tests 
To test, try the example.
=> feat: add retaining of the screen to the stack navigator

packages/bottom-tabs/src/types.tsx, packages/bottom-tabs/src/views/BottomTabBar.tsx, packages/bottom-tabs/src/views/BottomTabView.tsx
**Motivation**
Currently in `bottom-tabs`, the `tabBarPosition` prop can only have `bottom`, `left`, or `right` values.
For Apple TV and Android TV, it is helpful to allow `top` as well, so that there can be a top nav bar without absolute positioning (which causes problems for TV focus navigation).
**Test plan**
Test app that works correctly with this change: https://github.com/douglowder/IgniteTV/tree/top-navigation
=> feat: [bottom-tabs] allow position = top

packages/native-stack/src/types.tsx, packages/native-stack/src/views/NativeStackView.native.tsx
**Motivation**
For some time now, people are complaining that current native stack does not have some props that are included in v5, but not in v6.
I've deeply investigated the `props.tsx` file and I can make a conclusion some of the things that are missing include:
- no `hideKeyboardOnSwipe` `gestureResponseDistance` property,
- no props for managing the form sheet - `sheetX` properties,
- missing support for `onWillAppear` (is it intentional?) and `onGestureCancel` events.
This PR fixes all those things by adding them to `props.tsx` and their support in `NativeStackView.native.tsx` file.
One thing I also wanted to mention is that some of the events from the event map in `types.tsx` like `dismiss`, `appear` or `headerHeightChange` were not included in changes. That's because I think …
=> feat: introduce missing props from native-stack v5

packages/stack/src/views/Stack/Card.tsx
**Motivation**
This PR prevents the native view hierarchy built by `Stack` from re-mounting to prevent blurring focus - when a view is removed from the hierarchy it's blurred on Android, but it's not focused back when added again. Due to one of the views in the `Card` component being flattened, children of `Card` were removed from the hierarchy and attached under a different parent.
<details>
<summary>Before the change</summary>
https://github.com/react-navigation/react-navigation/assets/21055725/38ce6cbe-a717-4ca4-be04-0fdfe6e2e796
Native hierarchy on the first screen:
Native hierarchy on the second screen:
Notice the different nesting levels between the two - one of the views got collapsed during navigation.
</details>
<details>
<summary>After the change</summary> …
=> fix(Android): don't remount components during navigation on the new architecture

packages/stack/src/views/Stack/Card.tsx
The same as https://github.com/react-navigation/react-navigation/pull/11806 but targeting 6.x branch
=> fix(Android): don't remount components during navigation on the new architecture for 6.x

packages/core/src/BaseNavigationContainer.tsx, packages/core/src/types.tsx, packages/core/src/useNavigation.tsx, packages/native/src/useScrollToTop.tsx
This PR addresses the issue: [11701](https://github.com/react-navigation/react-navigation/issues/11701)
=> fix: type errors when getState used outside of a screen

packages/elements/src/Screen.tsx
**Motivation**
This PR is a part of ongoing investigation on PR [#1997](https://github.com/software-mansion/react-native-screens/issues/1997) in React Native Screens.
Because of how the views are being flattened, in some components (like bottom-tabs) large title of a header does not collapse while swiping the content vertically. That's because of an unnecessary view that is being rendered above the ScrollView in native view hierarchy.
**Test plan**
Below you can find the code that reproduces this issue.
```tsx
import { Text, ScrollView, TouchableOpacity } from 'react-native';
import { createNativeStackNavigator } from '@react-navigation/native-stack';
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs'; …
```
=> fix(iOS): disable collapsable option from Background in Screen

packages/native/src/useLinking.tsx
**Motivation**
Fix for #11832
Before going to negative history index check if the history will return anything for that index. If that's not the case the previous behavior would open previously opened page from that tab.
**Test plan**
From my testing project you can test it by
To replicate the issue in my example open the app and do:
1. Open new tab and go to any page. After that manually put the app address to the address bar and navigate to it.
2. Navigate with menu to PageA
3. Navigate with menu to PageB
4. Use browser go back (can be button, keyboard shortcut or mouse button)
5. Navigate with menu to PageB again
6. Try navigating Home with menu
7. You will no longer get redirected to a previous page from step 0 but to the home page instead
=> fix: browser navigating out after using back feature and going home

packages/native-stack/src/views/NativeStackView.native.tsx, packages/native-stack/src/views/NativeStackView.tsx
This PR fixes the issue #11797
Even with the DarkTheme during the transition ScreenStack comes up with a white background. I solved it by setting the backgroundColor as the theme color
=> fix: White flash transitions with DarkTheme

example/src/Screens/TabView/AutoWidthTabBar.tsx, example/src/Screens/TabView/ScrollableTabBar.tsx, packages/drawer/src/views/DrawerItem.tsx, packages/material-top-tabs/src/views/MaterialTopTabBar.tsx, packages/react-native-tab-view/src/TabBarItemLabel.tsx
some of elements was not according to material design
=> fix: md update - change styles of drawer item and remove uppercase from top tabs

packages/core/src/__tests__/getStateFromPath.test.tsx, packages/core/src/getStateFromPath.tsx
**Motivation**
Given a linking config with same screen name at different levels and a wildcard at one level, the derived navigation state does not always resolve to the correct screen. This PR makes a change to include a check for the pattern in such cases where there are two different path configs with the same screen name.
Its a very niche edge case which I stumbled into trying to implement another feature and I thought I would share this fix in case others are running into the issue.
**Test plan**
To verify that existing functionality is failing, first checkout to `main`, then copy the added test, paste it in `packages/core/src/__tests__/getStateFromPath.test.tsx`, execute the tests and note that it fails.
Now, checkout to this branch run all tests and note that the added test passes. …
=> fix: linking on initial path plus wildcard

packages/core/src/__tests__/getStateFromPath.test.tsx, packages/core/src/getStateFromPath.tsx
**Motivation**
params was not decoded before put to the state - it can lead to different path
=> fix: [6.x] - decode params for state creation 

packages/material-top-tabs/src/views/MaterialTopTabBar.tsx, packages/react-native-tab-view/src/PlatformPressable.tsx, packages/react-native-tab-view/src/TabBar.tsx, packages/react-native-tab-view/src/TabBarItem.tsx, packages/react-native-tab-view/src/types.tsx
**Motivation**
Material tabs on web had no links for better UX
=> fix: add links href to material top tabs

packages/elements/src/Header/Header.tsx, packages/elements/src/Header/getDefaultHeaderHeight.tsx, packages/native-stack/src/__tests__/index.test.tsx, packages/react-native-drawer-layout/src/constants.tsx, packages/react-native-drawer-layout/src/views/Drawer.tsx
correct some styles according to material design
=> fix: add drawer and header styles according to material design

packages/core/src/__tests__/getStateFromPath.test.tsx, packages/core/src/getPathFromState.tsx, packages/core/src/getStateFromPath.tsx, packages/core/utils/encodeParams.ts
**Motivation**
sometimes encodes characters unnecessarily, e.g. @ is converted to %40 even though it's valid in a URL.
valid characters - A–Z, a–z, 0–9, -, ., _, ~, !, $, &, ', (, ), *, +, ,, ;, =, :, @
=> fix: Adjust URL encoding to avoid encoding unnecessarily

packages/core/src/__tests__/getStateFromPath.test.tsx, packages/core/src/getStateFromPath.tsx
**Motivation**
When a path configuration contains multiple path parameters with the same name, the last path parameter value wins when constructing the navigation state.
For example consider the following scenario:
```ts
const path = '/foo/42/bar/43';
const config = {
initialRouteName: 'Foo',
screens: {
Foo: {
path: 'foo/:id',
screens: {
Bar: {
path: 'bar/:id',
},
},
},
},
};
const state = {
routes: [
{
name: 'Foo',
params: { id: '43' }, // PROBLEM: This should be 42
state: {
routes: [
{
name: 'Bar',
params: { id: '43' },
path,
},
],
},
},
],
}
```
This PR updates the resolution logic to assign positions to each of the path segments, so that we can assign the correct values to the screen in the navigation state based on the position which it appears in the path, and not just the name. …
=> fix: conflicting nested path params in state for linking

example/src/Screens/MixedNativeStack.tsx, example/src/screens.tsx, packages/native-stack/src/utils/getModalRoutesKeys.ts, packages/native-stack/src/views/NativeStackView.native.tsx, packages/stack/src/utils/getModalRoutesKeys.ts, packages/stack/src/views/Stack/CardStack.tsx
Make all screens after presentation: 'modal' as modal unless specified
=> fix: Make all screens after presentation: 'modal' as modal unless specified

example/e2e/config/setup-server.ts, example/e2e/tests/Link.test.ts, example/src/Screens/LinkComponent.tsx, packages/native/src/createMemoryHistory.tsx, packages/native/src/useLinking.tsx
**Motivation**
when updating some params on the page, the hash shouldn’t be removed
=> fix: preserve # in the URL if the screen hasn't changed - partially done

packages/native-stack/src/views/HeaderConfig.tsx
Passing a custom font for the `headerTitleStyle` configuration is ignored because the user set values always get overridden by the `fonts` values from the `useTheme()` hook. 
By changing the order of the values passed to `Stylesheet.flatten()`, any user passed `fontFamily` configurations then get retained.
I believe this fixes the issue raised in #11429. It's not just iOS specific; it cuts across all platforms.
=> fix: support custom fontFamily configurations in headerTitleStyle

packages/react-native-drawer-layout/src/types.tsx, packages/react-native-drawer-layout/src/utils/getDrawerWidth.tsx, packages/react-native-drawer-layout/src/utils/useFakeSharedValue.tsx, packages/react-native-drawer-layout/src/views/Drawer.native.tsx, packages/react-native-drawer-layout/src/views/Drawer.tsx, packages/react-native-drawer-layout/src/views/Overlay.native.tsx, packages/react-native-drawer-layout/src/views/Overlay.tsx
**Motivation**
Currently, the drawer doesn't use Gesture Handler on the Web, so there are no interactive animations. So including Reanimated unnecessarily increases the bundle size.
This re-implements the drawer on the Web using CSS transitions instead of Reanimated. 
**Test plan**
Open the "Drawer Layout" screen in the example app.
https://github.com/react-navigation/react-navigation/assets/1174278/8d46d9e3-0269-47b7-9931-be1019d95be0
=> refactor: implement drawer on Web with CSS transitions

packages/core/src/__tests__/getStateFromPath.test.tsx, packages/core/src/getStateFromPath.tsx
**Motivation**
I first noticed this in `@react-navigation/core@6.4.14`. I think it happened in  https://github.com/react-navigation/react-navigation/pull/11869
When you decode a path param that has an encoded `/` it removes the encoded param and leaves the trailing param in state.
**Test plan**
Create a route that have a path param with a`%2F` in it, verify that it comes out correctly decoded
=> fix: [6.x] - only replace trailing slash on decode

packages/native/src/__tests__/useUnhandledLinking.test.tsx
**Motivation**
In `useUnhandledLinking.test.tsx` file, we're trying to query the element with given label and press it with `fireEvent.press`. Unfortunately, in my case Typescript prints several warnings about the wrong return type of passed argument. In fact, Typescript is correct there - we're trying to pass the argument of type `ReactTestInstance | null` to the function that accepts arguments of type `ReactTestInstance`. Because of that, I'm willing to change `queryByText` to `getByText` in places where the tests are trying to press the element with queried label.
I'm also leaving remains of the `queryByText` in the expect functions intentionally, since we're still expecting that some elements will be null there.
**Test plan**
Passing CI should be enough to check if that works! ✅
=> test: change queryByText to getByText in useUnhandledLinking.test.tsx

.eslintrc.json
**Motivation**
Currently, ESlint crashes when someone has bundled react-navigation as a submodule to the project (here, in react-native-screens we've got one 😁 ). Our goal is to mark react-navigation's ESlint RC file as a root configuration, to omit configuration mismatching.
=> chore: add `root` prop to .eslintrc

example/src/Screens/NativeStack.tsx, packages/native-stack/src/utils/debounce.tsx, packages/native-stack/src/utils/useAnimatedHeaderHeight.tsx, packages/native-stack/src/views/NativeStackView.native.tsx
**Motivation**
Currently the `useHeaderHeight` hook returns a hardcoded value since previously we didn't have a way to measure the header height. But now there's a `onHeaderHeightChange` listener that we can use to measure the accurate height.
This PR makes sure that we use this event when measuring header height.
**Test plan**
Tested in the example app:
https://github.com/react-navigation/react-navigation/assets/1174278/c6e415eb-3cba-4e65-8717-9fd2d03f8987
=> fix: use measured header height when exposing it

packages/native-stack/src/views/HeaderConfig.tsx
**Motivation**
According to [the docs](https://reactnavigation.org/docs/7.x/native-stack-navigator#headerbacktitlevisible), setting `headerBackTitleVisible` to `false` should hide the back title on iOS, while this is not the case with `react-native-screens` v3.29+.
**Cause**
With the current code, `backTitle={headerBackTitleVisible ? headerBackTitle : ' '}`, the back title is set to a blank string if `headerBackTitleVisible` is false. However, in newer versions of `react-native-screens`, [the `backTitle` will be considered blank if it only contains white spaces](https://github.com/software-mansion/react-native-screens/blob/d54a19a/ios/RNSScreenStackHeaderConfig.mm#L506), making it fallback to the default title - which makes the back title not hidden at all.
**Fix**
Assign [the …
=> fix: setting headerBackTitleVisible to false not working on iOS

packages/native-stack/src/views/NativeStackView.native.tsx
**Motivation**
*copied & slightly redacted message from discord* 😄 
Currently we set `headerTopInsetEnabled: true` when `safe-area-context` reports any non-zero top inset. This prop is intended to handle missing inset when `statusBarTranslucent` is set to `true` (so whole header is moved up, and headerTitle is partially obfuscated by the status bar, just like on the first screenshot, so in the place I've sent you it seems that it is a bit misused?
I'm opening this PR, because I'm handling all header-related issues right now and: when `statusBarTranslucent: false` & `headerTopInsetEnabled == topInset !== 0` we get buggy behaviour on native stack, because `safe-area-context` does report `topInset > 0` only during the initial render & on every consecutive render `topInset === 0`, thus …
=> fix(native-stack):  set `headerTopInstetEnabled` to the same value as `statusBarTranslucent` to prevent header content jump

packages/native-stack/src/views/NativeStackView.native.tsx
**Motivation**
Backporting #12014 to v6
**Test plan**
Same as in #12014
=> fix(native-stack, v6): set `headerTopInsetEnabled` to the same value as `statusBarTranslucent` to prevent header content jump

packages/native-stack/src/types.tsx, packages/native-stack/src/views/NativeStackView.native.tsx
**Motivation**
This PR intents to enable navigation bar translucency control. You can find more about this feature [here](https://github.com/software-mansion/react-native-screens/pull/2152)
**Test plan**
Play around with following screen options:
```
<Stack.Navigator
screenOptions={{
navigationBarColor: 'transparent',
navigationBarTranslucent: true,
navigationBarHidden: false,
}}>
```
=> feat(Android): added navigationBarTranslucent option

packages/material-top-tabs/src/views/MaterialTopTabView.tsx
**Motivation**
The pr is due to https://github.com/orgs/react-navigation/projects/1/views/3?pane=issue&itemId=57472726
**Test plan**
Go to material top tabs -> click on different pages -> url path should update immediately after clicking
=> fix: immediately update navigation state after tapping tabs on material top tabs

packages/bottom-tabs/src/views/BottomTabBar.tsx, packages/bottom-tabs/src/views/BottomTabItem.tsx
**Motivation**
Motivation for this change comes from a task, named the same as the Title
**Test plan**
Drawer:
Bottom Tabs:
=> Adjust sidebar styling in bottom tabs to match drawer

example/src/Screens/BottomTabs.tsx, packages/bottom-tabs/src/types.tsx, packages/bottom-tabs/src/views/BottomTabView.tsx, packages/drawer/src/types.tsx, packages/drawer/src/views/DrawerView.tsx
This drops the `unmountOnBlur` option of bottom tabs and drawer in favor of a `popToTopOnBlur` option.
In many cases, the requirement is to return to the first screen of the stack nested in tabs. However using `unmountOnBlur` in those scenarios would also destroy any state of the screen. It's also slower to remount a nested navigator on tab navigation.
The `popToTopOnBlur` option provides an alternative approach - it pops the screens on a nested stack to go back to the first screen in the stack. It's much faster than remounting the nested navigator, and also doesn't destroy the state of the first screen in the stack.
It's still possible to achieve the old behavior of `unmountOnBlur` by using the `useIsFocused` hook in the screen:
```js
const isFocused = useIsFocused();
if (!isFocused) { …
```
=> refactor: drop unmountOnBlur in favor of popToTopOnBlur

example/package.json, packages/bottom-tabs/package.json, packages/drawer/package.json, packages/native-stack/package.json, packages/native-stack/src/types.tsx, packages/native-stack/src/views/HeaderConfig.tsx, packages/native-stack/src/views/NativeStackView.native.tsx, packages/stack/package.json, yarn.lock
**Motivation**
Follow-up for PR #11803 that introduced props from native-stack v5 to v7. Here, I'm migrating missing props also to native-stack v6. Take a look in [original PR](https://github.com/react-navigation/react-navigation/pull/11803) for more information about this change.
**Test plan**
You can test these props by checking how they affect screens after adjusting them in Native Stack example. Remember about setting `presentation` to `formSheet` while using `sheetX` props.
Some of the examples I've already prepared:
<details>
<summary>Using GestureResponseDistance on NewsFeed</summary>
This will enable changing the area of the gesture with a rectangle starting from the ~middle of the screen down to bottom.
`NativeStack.tsx:139`
```tsx
<Stack.Screen
name="NewsFeed" …
```
=> feat: introduce missing props from native-stack v5 (v6)

packages/native-stack/src/types.tsx, packages/native-stack/src/views/NativeStackView.native.tsx
Same as https://github.com/react-navigation/react-navigation/pull/12053 but for `6.x`
=> feat: add fullScreenSwipeShadowEnabled prop to NativeStackView

example/src/Screens/StackHeaderCustomization.tsx, packages/elements/src/Header/Header.tsx, packages/elements/src/Header/HeaderBackButton.tsx, packages/elements/src/types.tsx, packages/stack/src/types.tsx, packages/stack/src/views/Header/HeaderSegment.tsx
BREAKING CHANGE: This removes the `headerBackTitleVisible` option, and changes `headerTruncatedBackTitle` to `headerBackTruncatedTitle`.
Similarly, `headerLeft` now receives `displayMode` instead of `labelVisible`, and `HeaderBackButton` accepts `displayMode` instead of `labelVisible`
=> feat: add headerBackButtonDisplayMode for stack

packages/core/src/validatePathConfig.tsx
**Motivation**
When validating the linking config, undefined values cause a validation error. I think undefined values should be treated as if the config value was omitted.
For example:
```ts
{
a: {
path: '/',
parse: undefined,
}, 
}
```
Causes the following error:
```
Error: Found invalid properties in the configuration:
- parse (expected 'object', got 'undefined')
You can only specify the following properties:
- path (string)
- initialRouteName (string)
- screens (object)
- exact (boolean)
- stringify (object)
- parse (object)
If you want to specify configuration for screens, you need to specify them under a 'screens' property.
See https://reactnavigation.org/docs/configuring-links for more details on how to …
```
=> Allow undefined in path config validation

example/__typechecks__/common.check.tsx, packages/core/src/types.tsx, packages/core/src/useNavigationBuilder.tsx, packages/native/src/useLinkProps.tsx, packages/routers/src/StackRouter.tsx, packages/routers/src/TabRouter.tsx
The current conditional (`RouteName extends unknown`) is confusing to understand. This updates the logic to make it clearer.
=> fix: improve how navigate and other methods are typed

packages/native-stack/src/types.tsx, packages/native-stack/src/views/HeaderConfig.tsx
We can't use `backButtonDisplayMode` prop from `react-native-screens` in the following scenarios:
- The iOS version is lower than 14
- Custom back title is set
- Custom back title style is set (`fontFamily` or `fontSize`)
- Back button menu is disabled
This change falls back to `backTitleVisible` in those scenarios.
=> fix: add more fallbacks for headerBackButtonDisplayMode

packages/core/src/getPathFromState.tsx, packages/core/src/getStateFromPath.tsx, packages/elements/src/SafeAreaProviderCompat.tsx, packages/native-stack/src/utils/debounce.tsx, packages/native/src/createStaticNavigation.tsx, packages/react-native-tab-view/src/SceneView.tsx, packages/stack/src/utils/throttle.tsx
**_Problem_**
When `getStateFromPath` receives big _linking config_ ([example](https://github.com/Expensify/App/blob/071f11ce1012db7d07eb750d74f58b552eba6144/src/libs/Navigation/linkingConfig/config.ts#L1152)) as an option parameter, it tends to slow down quite drastically.
**_Investigations_** 
The config-related data is created every time`getStateFromPath` is called, resulting in noticeable overhead.
Often times, configs provided to `getStateFromPath` are going to be static (e.g. initialised once at the app setup and remained untouched throughout its lifetime) and the data derived from it could also be static.
**_Solution_**
PR tries to improve `getStateFromPath` helper performance by extracting and caching calculations related to last linking config provided (due to its static nature, …
=> refactor: getStateFromPath config calculations caching

packages/devtools/package.json, packages/devtools/src/useDevToolsBase.tsx, yarn.lock
Switch to `fast-deep-equal` from `deep-equal` for `@react-navigation/devtools` package. By the way, `fast-deep-equal` already used in `@react-navigation/native` package.
**Motivation**
`deep-equal` is a terribly heavy library: [https://npmgraph.js.org/?q=%40react-navigation%2Fdevtools](https://npmgraph.js.org/?q=%40react-navigation%2Fdevtools)
**Test plan**
Lint, typescript and tests are passed.
=> Reduce number of dependencies for `@react-navigation/devtools` package

packages/native/src/useScrollToTop.tsx
Closes #12139 
A `scrollToOffset` function needs to expect an `offset` otherwise there no place to scroll to. Making it optional throws a typescript error with FlashList
**Motivation**
Using useScrollToTop with FlashList in a type safe way
**Test plan**
The change doesnt really affect runtime behavior
=> fix: update scroTloOffset type of useScrollToTop

packages/react-native-tab-view/src/TabBar.tsx
**Motivation**
After bumping up versions of `react` from `18.2.0` to `18.3.1` as well as `react-native` from `0.74.5` to `0.75.2` in one of my projects, the application started to give me a warning `A props object containing a "key" prop is being spread into JSX`.
It happens on the screens which use `@react-navigation/material-top-tabs`.
Addresses the existing issue https://github.com/react-navigation/react-navigation/issues/11989.
**Test plan**
1. Initialize a new project with the latest versions of `react` and `react-native`
2. Make use of `@react-navigation/material-top-tabs`
3. See the warning in the console
**Solution**
Passing the key straight to the component instead of spreading it.
I've also removed the `renderTabBarItem` prop since it doesn't seem to be used anywhere and …
=> fix: spread key into JSX warning

packages/native-stack/src/types.tsx
This PR aligns JSDoc for "stackAnimation" with current state of react-native-screens (4.0.0) https://github.com/software-mansion/react-native-screens/pull/2361.
=> docs: add new or missing stackAnimations to JSDoc

packages/bottom-tabs/src/__tests__/index.test.tsx
**Motivation**
The existing test was pressing a button inside the scene, which was calling `navigation.navigate`.
This can cause the tests to pass even if the `BottomTabBar` is not rendered.
**Test plan**
=> test: press tab instead of button-in-scene

packages/core/src/getPathFromState.tsx, packages/core/src/getStateFromPath.tsx
**Motivation**
The mechanism for caching config resources of `getStateFromPath` and `getPathFromState` relies on simple tuple approach.
It works as expected but @satya164 noticed that the reference hold by cache might lead to memory leaks.
This PR swaps out tuple approach for WeakMap one for both `gSFP` and `gPFS` caching.
**Test plan**
Testing was mainly focused on whether cache still works as supposed to. 
In the example app, logs were added to the cache retrieval methods (for both `gSFP` and `gPFS`). 
Here's a code snippet showing one of them:
```tsx
function getConfigResources<ParamList extends {}>(
options: Options<ParamList> | undefined
) {
console.log('Deboog', 'gSFP', 'cached skipped empty config');
if (!options) return prepareConfigResources();
const cached = …
```
=> refactor: Use WeakMap as underlying caching mechanism for linking config resources

packages/react-native-tab-view/package.json, packages/react-native-tab-view/src/__tests__/index.test.tsx, yarn.lock
**Motivation**
`react-native-tab-view` doesn't have Jest tests yet. This provides the setup as well as initial component and interaction tests for rendering and switching tabs.
Closely related to https://github.com/react-navigation/react-navigation/issues/11493
**Test plan**
=> test: react-native-tab-view

packages/react-native-tab-view/src/PlatformPressable.tsx, packages/react-native-tab-view/src/__tests__/PlatformPressable.test.tsx
Prevents react-native-tab-view from throwing an error on fireEvent.press when running Jest tests
**Motivation**
Apps that use react-native-tab-view can't test tab switching using only `fireEvent.press(component)` and devs have to delve into the code to realize that they have to use `fireEvent.press(component, eventObject)` [reproduction proof](https://github.com/bytehala/rntv-issue/pull/1)
When using `fireEvent.press(component)`, Jest throws an error `TypeError: Cannot read properties of undefined (reading 'metaKey')`. This is because of 2 main reasons:
1. The React Native Testing Library fireEvent API [does not send an event](https://callstack.github.io/react-native-testing-library/docs/api/events/fire-event)
2. The code was checking for web-only attributes outside of the `Platform.OS …
=> refactor: move web-only checks inside the Platform.OS web condition

example/package.json, packages/bottom-tabs/package.json, packages/drawer/package.json, packages/native-stack/package.json, packages/native-stack/src/types.tsx, packages/native-stack/src/views/NativeStackView.native.tsx, packages/stack/package.json, yarn.lock
**Motivation**
`react-navigation@v7` brings support for `screens@v4` stable version of which will be released soon. This PR bumps used version of react native screens in all the packages and example application.
**Test plan**
Example app.
=> chore: bump react-native-screens version to 4-beta for v7

packages/native/src/index.tsx
**Motivation**
Expo Router is a library built on top of React Navigation. It customises the linking behaviour of React Navigation by providing a custom `<NavigationContainer />` and changes the behaviour how it performs linking.
In React Navigation 7, the packages were changed to use `package.json#exports` which only expose the public APIs and not the internal contexts/hooks that are needed by to create a custom `<NavigationContainer />`.
Instead of adding these values to the public exports, this PR proposes that a new submodule is exposed `@react-navigation/native/extend` which exports public API and the required hooks/contexts needed to create a custom `<NavigationContainer />`
=> feat: export LocaleDirContext and UNSTABLE_UnhandledLinkingContext

example/package.json, packages/bottom-tabs/package.json, packages/drawer/package.json, packages/native-stack/package.json, packages/stack/package.json, yarn.lock
**Motivation**
This PR bumps `react-native-screens` to 4.0.0-beta.9, which contains native code for `preload` functionality for `native-stack`.
**Test plan**
`TestPreload` in `FabricExample` / `Example` in `react-native-screens` repository.
=> chore: bump react-native-screens to 4.0.0-beta.9

packages/bottom-tabs/src/__tests__/index.test.tsx
**Motivation**
There is currently no integration test on the `tabBarHideOnKeyboard` property, which internally sets some states and ultimately sets `pointerEvents: 'none'` inside BottomTabBar.
By adding this test, we can be confident regarding existing and future code on BottomTabBar's visibility-related behaviors.
For example, this issue https://github.com/react-navigation/react-navigation/issues/11691 demonstrates that `style={display: 'none'}` can sometimes still "leak" pointerEvents. This test would be a good starting point for fixing said issue.
**Test plan**
=> test: integration test on pointerEvents 'none'

packages/elements/src/PlatformPressable.tsx, packages/elements/src/__tests__/PlatformPressable.test.tsx
**Motivation**
When writing tests that have `fireEvent.press(somePlatformPressable)` the test throws an error because event is undefined.
This change is similar to https://github.com/react-navigation/react-navigation/pull/12161 
**Test plan**
=> refactor: move web-only checks inside web condition

packages/native-stack/src/views/NativeStackView.native.tsx, packages/native-stack/src/views/ScreenStackContent.tsx, packages/native-stack/src/views/useHeaderConfigProps.tsx
Currently there is a lot of logic to make `Screens` work properly in native-stack, including:
- Making sure screens is enabled and mark it for native-stack
- Making sure screens knows that it contains a large title
- Rendering a `DebugContainer` for `LogBox`
- Making sure the `DebugContainer` contains appropriate logic and wrapper
- Rendering a nested stack to be able to show header in modals
This diff consolidates this logic to a new component `ScreenStackContent`. This makes it possible to move the above logic to the `react-native-screens` package by moving this component. Moving the logic will make it easier to fix bugs in screens.
**Next Steps**: Once we merge this, we should move the `DebugContainer` and `ScreenStackContent` to `react-native-screens` package and update native-stack's …
=> refactor: move screen specific logic for native stack to own component

example/package.json, packages/bottom-tabs/package.json, packages/drawer/package.json, packages/native-stack/package.json, packages/native-stack/src/views/NativeStackView.native.tsx, packages/stack/package.json, yarn.lock
Bump react-native-screens in react-navigation to beta.17.
**Motivation**
Custom Screen Transition landed in react-native-screens. To finish react-navigation part I need to have the newest react-native-screens (due types imported from the second one).
=> chore: bump react-native-screens to beta 17

packages/native-stack/src/types.tsx
**Motivation**
In `react-native-screens` v4 we change default animation on iOS duration to 500ms.
See: 
* https://github.com/software-mansion/react-native-screens/pull/2477
=> docs(native-stack): update JSDoc on default animation duration

packages/devtools/src/useLogger.tsx
**Motivation**
Firstly congrats on the release of v7 🎊 , my pr attepmts to give better colors for the devtools logger if user was on dark mode 
because It was hard to read for me 
Here is a demo on how the new color will look like 
| ligth | dark |
|--------|--------|
| <img width="565" alt="Screenshot 1446-05-06 at 9 32 31 PM" src="https://github.com/user-attachments/assets/00f0ccac-3f65-442e-9f7c-88bf5cb6fae0"> | <img width="567" alt="Screenshot 1446-05-06 at 9 32 27 PM" src="https://github.com/user-attachments/assets/7379b0bd-55f6-4123-89a8-ee3dada0513b">
| 
**Test plan**
Tested it on the example project 
https://github.com/user-attachments/assets/7f59150d-9485-4118-a4e4-a8600e931aa4
=> chore(devtools): have proper colors in dark mode for the logger

packages/react-native-drawer-layout/src/views/Drawer.native.tsx
**Motivation**
After upgrading to v7, Drawer started throwing this warning: (at least on `"react-native-gesture-handler": "2.20.2"`)
`[react-native-gesture-handler] None of the callbacks in the gesture are worklets. If you wish to run them on the JS thread use '.runOnJS(true)' modifier on the gesture to make this explicit. Otherwise, mark the callbacks as 'worklet' to run them on the UI thread. [Component Stack]`
I identified the issue by adding a `console.log` on `react-native-gesture-handler` `utils.ts`:
```ts
export function checkGestureCallbacksForWorklets(gesture: GestureType) {
if (!__DEV__) {
return;
}
console.log(gesture.handlers)
...
```
output: 
`{"changeEventCalculator": [Function changeEventCalculator], "gestureId": 10, "handlerTag": 3, "isWorklet": [undefined, true, true, …
=> fix: `None of the callbacks in the gesture are worklets` on Drawer

packages/bottom-tabs/src/navigators/createBottomTabNavigator.tsx
**Motivation**
`screenLayout` prop was missing in  BottomTabNavigator
=> fix: add missing screenLayout prop to the bottom tabbar navigator

packages/native-stack/src/views/NativeStackView.native.tsx
**Motivation**
The footer is currently broken, as in the effect of recent refactors it erroneously ended up being rendered as child as `ScreenStackItem`, thus due to internal implementation it is rendered under `ScreenContentWrapper`. However it has to be rendered as direct child of `Screen` component (the same as `HeaderConfig`). 
Under usual circumstances this would be a breaking change, however the prop is marked as `unstable`, therefore I'm proceeding. 
**Test plan**
`Test1649` in `FabricTestExample`.
=> refactor: move unstable_sheetFooter rendering to `react-native-screens`

packages/elements/src/types.tsx
**Motivation**
I noticed while migrating from v6 to v7 that `labelVisible` was changed to `displayMode`. The migration guide and the elements documentation pages did not include this information, so I went ahead and [updated them](https://github.com/react-navigation/react-navigation.github.io/pull/1384) (the PR just landed).
However, I noticed while hovering in my IDE (VS Code) that the description for `displayMode` was not updated. I went ahead and updated it in the types to match the `headerBackButtonDisplayMode` description (it's the same property).
**Test plan**
There are no code changes, this is strictly related to TypeScript DX.
Before:
After:
=> fix: `displayMode` description

packages/elements/src/Screen.tsx
**Motivation**
This fixes a problem on web where headerTransparent might overlap other elements and make it unresponsive. By adding box-none, this problem can easily be fixed (all the children containers already have that prop)
**Test plan**
In the browser
The screenshot shows a site with `statusbarTranslucent`. The header overlaps `Edit Token`, even though there is no title or HeaderRight.
=> fix: add pointerEvents box-none to Header container

packages/react-native-drawer-layout/src/index.tsx, packages/react-native-drawer-layout/src/utils/DrawerGestureContext.tsx, packages/react-native-drawer-layout/src/views/Drawer.native.tsx
**Motivation**
The drawer gesture can conflict with other gestures in the app. To coordinate multiple gestures, the app code can use APIs like `requireExternalGestureToFail`. However, since the gesture is hidden in the library, this is not currently possible without patching. This exposes the gesture to the app code so you can use `requireExternalGestureToFail` with it.
```js
import { DrawerGestureContext } from 'react-native-drawer-layout';
// ...
const drawerGesture = useContext(DrawerGestureContext)
const nativeGesture = Gesture.Native()
.requireExternalGestureToFail(drawerGesture)
// ...
<GestureDetector gesture={nativeGesture}>
<PagerView
// ...
/>
</GestureDetector>
```
Note that the existing `configureGestureHandler` is not enough because we need it in the other direction: *other* …
=> feat: provide gesture in DrawerGestureContext

packages/bottom-tabs/src/index.tsx, packages/bottom-tabs/src/navigators/createBottomTabNavigator.tsx, packages/bottom-tabs/src/types.tsx, packages/drawer/src/index.tsx, packages/drawer/src/navigators/createDrawerNavigator.tsx, packages/drawer/src/types.tsx, packages/material-top-tabs/src/index.tsx, packages/material-top-tabs/src/navigators/createMaterialTopTabNavigator.tsx, packages/material-top-tabs/src/types.tsx, packages/native-stack/src/index.tsx, packages/stack/src/index.tsx, packages/stack/src/navigators/createStackNavigator.tsx, packages/stack/src/types.tsx
**Motivation**
Fix the TypeScript error when trying to use inferred types with React Navigation navigators
```
The inferred type of 'NativeStackNavigator' cannot be named without a reference to '../node_modules/@react-navigation/native-stack/lib/typescript/module/src/types'. This is likely not portable. A type annotation is necessary.
```
The inferred type of `NativeStackNavigator` references `NativeStackNavigatorProps` which is located in `@react-navigation/native-stack/lib/typescript/module/src/types` and not exposed by `package.json#exports`. 
This issue only affects apps using `moduleResolution: nodenext/bundler`
I have added additional types to support type inference for `NativeStack`, `Tab` & `Drawer`
**Issue Reproduction**
`npx create-expo-app@latest --template …
=> feat: export *NavigatorProps for each navigator

packages/core/package.json, packages/devtools/package.json, packages/native/package.json, packages/routers/package.json, yarn.lock
This PR is to update the version of the **nanoid** library used in core, native and routers packages.
**Motivation**
There were 9 vulnerabilities with **low** severity reported in **nanoid** library of version 3.3.7.
The next closest version of the library with no vulnerabilities is 3.3.8.
Link to the vulnerability report: https://github.com/advisories/GHSA-mwcw-c2x4-8c55
This migration is already tested in a side project react native app. No difference observed, works fine. This migration solved all vulnerabilities.
=> fix: nanoid vulberable version

packages/native/src/__tests__/extractPathFromURL.test.tsx, packages/native/src/extractPathFromURL.tsx
**Motivation**
`extractPathFromURL` gobbles up parts of url if it contains multiple `?` characters.
For example:
```typescript
extractPathFromURL(
['https://mysite.com'],
'https://mysite.com/readPolicy?url=https://test.com?param=1'
)
// expected (good): /readPolicy?url=https://test.com?param=1
// got (bad):       /readPolicy?url=https://test.com
```
**Test plan**
Added test case which passes with this PR.
=> fix(native): correctly extract path from url with multiple `?` characters

example/package.json, yarn.lock
**Motivation**
There is a problem with building the examples app for Android. The build fails because of one of the dependencies of expo-blur. The issue has been resolved in newest version of expo-blur@14.0.3 (https://github.com/expo/expo/pull/34012).
**Test plan**
Build the examples app for Android.
=> chore(example): update expo-blur version to 14.0.3 to fix issues with building on Android

packages/core/src/StaticNavigation.tsx, packages/core/src/types.tsx, packages/core/src/useComponent.tsx, packages/native/src/useScrollToTop.tsx
**Motivation**
This PR addresses some TypeScript errors under React Native 0.78.x, namely React 19. They are also discussed in #12468 .
Specifically, 2 parts are modified in this PR:
1. Rewrite `JSX` into `React.JSX`: since React 19 `JSX` global namespace is removed ([ref](https://react.dev/blog/2024/04/25/react-19-upgrade-guide#the-jsx-namespace-in-typescript)). We need to use `React.JSX` instead.
2. Add `null` type into `ScrollableWrapper` type definition: React 19 removes `MutableRefObject` and makes all refs mutable ([ref](https://react.dev/blog/2024/04/25/react-19-upgrade-guide#useref-requires-argument)). That makes the `ref` argument of `useScrollToTop` become `RefObject<ScrollView | null>` (using `ScrollView` as an example here) under React 19. In order to take this change into …
=> fix: fix JSX and useScrollToTop types for React 19 compatibility

packages/elements/src/types.tsx
Allows sending `onSubmitEditing` to the underlying `TextInput` element. Useful when searching should happen after user hits the keyboard submit button.
=> feat: add typing for onSubmitEditing

packages/elements/src/Header/Header.tsx
**Motivation**
This problem occurs when using `headerTitleAlign` set to `"center"` when using the simple stack. The search should span the entire header.
**Test plan**
1. Open example app;
2. Go to Simple Stack > Navigate to feed > Replace with contacts;
3. Change `headerTitleAlign` to `"center"` in the code;
4. Check result.
Without fix:
With fix:
=> fix: header search not taking remaining space when title centered

packages/drawer/src/views/DrawerToggleButton.tsx
**Motivation**
Want a feature which could change the togglebutton image.
**Test plan**
You can now give props to the drawertogglebutton so that its image can change. I checked myself in my app through importing the edited file.
=> feat: drawerToggleButton image option

packages/elements/src/Header/HeaderSearchBar.tsx, packages/elements/src/types.tsx
Adds and passes `enterKeyHint` to header search's text input. Defaults to `"search"`.
=> feat: add enterKeyHint

packages/native-stack/src/types.tsx, packages/native-stack/src/views/useHeaderConfigProps.tsx
The problem is that the back button jumps, when the`backButtonDisplayMode` is set to `minimal`.
|The Problem|
|-|
|<video src="https://github.com/user-attachments/assets/214c3af9-fdea-43a8-9976-453246a48079" />
The problem is noted as caused by the `backButtonDisplayMode` set to `minimal`, but that's not true. The flag that enables the `backButtonDisplayMode` looks as follows:
```
const isBackButtonDisplayModeAvailable =
// On iOS 14+
Platform.OS === 'ios' &&
parseInt(Platform.Version, 10) >= 14 &&
// Doesn't have custom back title
headerBackTitle == null &&
// Doesn't have custom styling
backTitleFontFamily == null &&
backTitleFontSize == null &&
// Back button menu is not disabled
headerBackButtonMenuEnabled !== false;
```
but as stated in …
=> fix: jumping back button

packages/native-stack/src/types.tsx, packages/native-stack/src/views/useHeaderConfigProps.tsx
**Motivation**
The iOS has a default behavior how to deal with back title label - it changes its size depending on available space. It didn't work for custom back title, as react-native-screens used custom back button item when custom back title was provided. This changes in https://github.com/software-mansion/react-native-screens/pull/2860, thus we can remove check on react-navigation side.
Corresponding docs update: https://github.com/react-navigation/react-navigation.github.io/pull/1422
**Test plan**
See `Test code and steps to reproduce` in https://github.com/software-mansion/react-native-screens/pull/2860 or test this snippet (very long custom back button title should be changed to `Back`):
<details>
<summary>Source code</summary>
```
import * as React from 'react';
import { Button, …
```
=> fix(native-stack): align headerBackTitle with iOS behavior 

packages/core/src/StaticNavigation.tsx, packages/core/src/index.tsx
**Motivation**
I am working in an app where we are breaking up the static screen and group configs into feature folders. Ultimately they are consumed by `createNativeStackNavigator`, which is correctly type checking them. But the type errors are indirect because an error in a static config will warn in `createNativeStackNavigator` instead of closer to their feature screen config, making it harder to debug.
Exporting these types that are used by `createNativeStackNavigator` make it easier to break up the screen config into smaller chunks and type check using `satisfies`.
Example:
```tsx
// feature/profile/screens.tsx
// base type with loose default type arguments to be used with satisfies later
type BaseScreenConfig = StaticConfigScreens<
ParamListBase,
NavigationState,
Record<string, …
```
=> chore: add `GroupConfig` and `StaticConfigScreens` to public type exports in `@react-navigation/core`

packages/stack/src/index.tsx
**Motivation**
- This adds a missing type, StackHeaderRightProps, to the stack types export
**Test plan**
No tests needed as this is a change to a type file for developer experience
=> feat: add StackHeaderRightProps type to exports

packages/native-stack/src/types.tsx
**Motivation**
Recently noticed that docs for `statusBarStyle` and `statusBarHidden` are not kept in sync between files in `react-native-screens` repo, `react-naviagtion` in-code docs and `reactnavigation.org/docs`.
I added information about support on Android for `statusBarStyle` and `statusBarHidden` props and `auto` and `inverted` values not being supported on Android for `statusBarStyle`.
Similar PR in `react-native-screens`: https://github.com/software-mansion/react-native-screens/pull/2953, `react-navigation.github.io`: https://github.com/react-navigation/react-navigation.github.io/pull/1432.
=> docs: add missing information in status bar docs

example/src/Screens/DrawerView.tsx, packages/react-native-drawer-layout/src/views/Drawer.tsx
**Motivation**
Currently, the Drawer component on web has an incorrect tab order when positioned on the left side of the screen and when the `drawerType` is `'permanent'` . This creates accessibility issues for keyboard users and those using assistive technologies, as the tab sequence doesn't follow a logical left-to-right order when the drawer is on the left side.
**Problem**
The current implementation uses `flex-direction: row-reverse` to position the drawer on the left side. While this achieves the desired visual layout, it creates an incorrect tab order because the DOM elements are rendered in a sequence that doesn't match the visual layout. This violates accessibility best practices and makes navigation difficult for keyboard users.
**Solution**
This PR fixes the tab order by:
1. …
=> fix: 🐛 Drawer tab order on web for better accessibility

packages/native-stack/src/types.tsx
**Motivation**
This is a follow-up to https://github.com/react-navigation/react-navigation/pull/12618#issuecomment-2918729663. Changed the in-code docs for `statusBarAnimation` to match [current online docs](https://reactnavigation.org/docs/native-stack-navigator#statusbaranimation).
Similar PR in `react-native-screens`: https://github.com/software-mansion/react-native-screens/pull/2953.
=> docs: add missing information in statusBarAnimation docs

packages/core/src/__tests__/getStateFromPath.test.tsx, packages/core/src/getPathFromState.tsx
**Motivation**
After https://github.com/react-navigation/react-navigation/pull/11867, we only encode the necessary characters from the path. However, this fails if the path contains emojis and causes a crash.
**Test plan**
Run the unit test
=> fix: crash when path contains emoji

packages/core/src/useRouteCache.tsx
https://github.com/react-navigation/react-navigation/issues/12685
I think that the cost of unnecessary re-renders of each navigator is higher than the cost of computing map for each route, especially considering complex pages. However, I don't have concrete evidence for that.
**Test plan**
1. Run the app in the production and development
=> fix: remove production check in useRouteCache
