react-navigation/react-navigation

docs/guides/Web-Integration.md

Fix link to web site

---

docs/guides/Redux-Integration.md

Just correcting a tiny typo in some code of the documentation. No biggie, nor is it urgent.
Great work everyone!

Correct tiny typo

---

docs/guides/Screen-Navigation-Prop.md

Changes `const {navigate} = this.props.navigation;` to `const {goBack} = this.props.navigation;` in the `goBack` section.

Documentation Update Screen-Navigation-Prop.md

---

docs/guides/Screen-Nav-Options.md

thanks to @mkonicek for writing this!

refactor the default navigation options guide

---

docs/guides/Guide-Headers.md

Just fixed a few typos - there was a missed closing parentheses in 2 places.

fix minor typos

---

examples/ReduxExample/index.js

motivation - using es6 default values.
no functionality change, just cosmetics.

Use es6 default values for initial state

---

package.json
src/views/TabView/TabBarBottom.js
src/views/TabView/TabBarIcon.js
src/views/TabView/TabBarTop.js
yarn.lock

Fix TabNavigator bugs

---

.gitignore
docs/api/navigators/DrawerNavigator.md
src/navigators/DrawerNavigator.js
src/views/Drawer/DrawerView.js

Resolves #87.
I also added an entry to the `.gitignore` regarding IntelliJ.

Added drawerPosition prop into DrawerView (left - right)

---

docs/guides/Guide-Headers.md

Fix typos and corrections in header guide

---

docs/guides/Screen-Navigation-Prop.md

Related to #59  
- Added the index
- Actions is now an array 
Let me know if I need to fix anything :)

Fixed reset action docs

---

src/views/TabView/TabBarBottom.js
src/views/TabView/TabBarTop.js

Per https://github.com/react-community/react-navigation/pull/176#issuecomment-277480911

Allow labelStyle to override tab label color

---

docs/api/withNavigation.md
examples/NavigationPlayground/js/App.js
examples/NavigationPlayground/js/SimpleTabs.js
examples/NavigationPlayground/js/WithNavigation.js
package.json
src/TypeDefinition.js
src/react-navigation.js
src/views/SceneView.js
src/views/withNavigation.js
yarn.lock

Add withNavigation HOC

---

src/views/Header.js
src/views/HeaderBackButton.js
src/views/HeaderTitle.js

Caused some issues, need to iterate on it a bit more. Will re-submit with fixes later.
What needs to be checked:
- Android compatibility
- iOS layouts
Used `Revert` Github functionality

Revert "Better back button label"

---

docs/guides/Screen-Navigation-Prop.md

This address some confusion over how to use the reset action (#59).

Elaborate on how to use the reset action in docs (#59)

---

examples/HelloHybrid/HybridContainer.js

Just adding a missing right parenthesis

fix typo on HybridContainer

---

docs/guides/Redux-Integration.md

Insert clarification in docs on Redux and nested Navigators per https://github.com/react-community/react-navigation/issues/16

Add clarification for Redux <-> Nested Navigators

---

docs/guides/Screen-Tracking.md

the code was originally from exponent/ex-navigation repo. adapted slightly.

updated doc with code sample for google analytics integration

---

src/views/HeaderTitle.js

HeaderTitle should display only one line of text.

Set HeaderTitle numberOfLines to 1

---

examples/NavigationPlayground/js/SimpleStack.js

adds button to photo screen

---

src/views/Header.js
src/views/HeaderBackButton.js

Fix backgrounds in header and header.item. Step one to better animations.
CC: @ericvicenti, applied the patch :)

Fix header item background

---

docs/guides/Screen-Nav-Options.md

Remove confusing mention of `color`

Update `StackNavScreen` docs

---

docs/guides/Screen-Tracking.md

This is a hack and we shouldn't put it in official documentation.

Remove screen tracking without redux

---

docs/guides/Redux-Integration.md

It took me a while to figure out where 'addNavigationHelpers' comes from, maybe adding the import in the doc here will help the next guy.
The code must pass tests and shouldn't add more Flow errors.
Look …

add import to clarify source of helper

---

package.json
src/views/Drawer/DrawerView.js
yarn.lock

**Motivation**: We would be able to use the (likely) more performant native Drawer solution on Android.
**Test Plan**: See the navigation example and check if the drawer still works as expected
@satya164 Could you review this change?

Move from drawer-layout to drawer-layout-polyfill

---

src/views/Drawer/DrawerScreen.js
src/views/Drawer/DrawerSidebar.js

Currently the descriptions of [DrawerSidebar](https://github.com/react-community/react-navigation/blob/master/src/views/Drawer/DrawerSidebar.js#L36) and of [DrawerScreen](https://github.com/react-community/react-navigation/blob/master/src/views/Drawer/DrawerScreen.js#L26) are the same. AFAIU (I may be wrong) the component in DrawerSidebar is responsible for drawing the side menu so I updated its description accordingly.

Drawer sidebar description

---

docs/api/navigators/TabNavigator.md

- The example provides styling for the tab icon via the `icon` property in the styles object. However in the example, it is used as `tabIcon` which does not exist.
The code must pass tests and shouldn't add more Flow errors. …

fix(docs): Fix incorrect style in TabNavigator sample

---

examples/NavigationPlayground/js/App.js
examples/NavigationPlayground/js/SampleText.js

flow fixes for the NavigationPlayground

Fix flow in Navigation Playground

---

docs/guides/Contributors.md

I messed up the git commands when adding the updating section to the contributor docs. Sorry about that

Fix rebase commands

---

package.json
yarn.lock

The new version includes support for accessibility and should fix #871.
@satya164 Can you verify / review this?

Bump react-native-drawer-layout-polyfill version

---

docs/guides/Guide-Headers.md

Clarifies where header configuration applies #764

Docs: Added clarification for header configuration #764

---

docs/api/navigators/TabNavigator.md
src/views/TabView/TabBarTop.js

I created a tab bar using TabNavigator and I wanted to place icons instead of labels.
This is my TabNavigator configuration:
```
var MainTabNavigator = TabNavigator({
JobList: {
screen: JobList
},
SearchPieces: {
screen: SearchPieces
},
SideMenu: {
screen: SideMenu
}
}, {
lazyLoad: true,
animationEnabled: false,
tabBarOptions: {
activeTintColor: '#3b5998',
inactiveTintColor: '#cccccc',
showIcon: true,
showLabel: false,
style: {
backgroundColor: 'white'
},
pressColor: '#d5dcea',
indicatorStyle: {
backgroundColor: 'white'
}
}
});
```
and this is one of the tabs with the icon that gives me problems:
```
static …
```

add iconStyle prop to tabBarOptions for TabBarTop

---

examples/NavigationPlayground/js/ModalStack.js
src/routers/StackRouter.js
src/routers/__tests__/StackRouter-test.js

Navigate to nested router within stack

---

package.json
yarn.lock

Not much info necessary on this one. Fixes the issue discussed in #1045.

Update flow-react-proptypes to ^1.2.0

---

.babelrc
.flowconfig
examples/NavigationPlayground/package.json
examples/NavigationPlayground/yarn.lock
package.json
src/views/CardStack.js
yarn.lock

Follow up to #970 adding few things on top of it.

Joemckie bugfix/render inner card flowtype

---

website/src/BrowserAppContainer.js
website/src/Link.js

This pull request fixes hash behaviour (in particular it fixes broken links to `navigator#drawer` etc. in docs)

Fix hashbang behaviour

---

docs/api/navigators/Navigators.md
docs/guides/Deep-Linking.md
src/TypeDefinition.js
src/createNavigationContainer.js
src/navigators/DrawerNavigator.js
src/navigators/StackNavigator.js
src/navigators/TabNavigator.js
src/navigators/createNavigator.js
src/views/SceneView.js

This is a breaking change but eventually, the API will become simpler.

Breaking: Replace `containerOptions` with just `props`

---

docs/api/navigators/StackNavigator.md

Fixes #1124 - regression after flat options.
CC: @ericvicenti

Update docs on headerLeft/Right

---

docs/api/navigators/DrawerNavigator.md
docs/api/navigators/TabNavigator.md
src/navigators/DrawerNavigator.js
src/navigators/TabNavigator.js
src/react-navigation.js
src/views/Drawer/DrawerView.js
src/views/Header.js
src/views/TabView/TabView.js

This PR removes inconsistencies between static properties and exported interface.

Export all the things

---

src/navigators/TabNavigator.js

Fix lazy prop not passed

---

package.json

I cannot push to master, so making a PR. Already on `npm`.
If possible, select `rebase and merge` or something different than `squash` so that commit sha matches `git tag`.

Release v1.0.0-beta.9.

---

docs/guides/Screen-Nav-Options.md

Fix navigator links

---

src/views/TabView/TabView.js

Hide overflow on individual pages in tab view

---

src/views/TabView/TabBarBottom.js

Changing the View to Animated.View for TabBarBottom connected to this discussion:
https://github.com/react-community/react-navigation/issues/1270

Changed View to Animated.View for TabBarBottom

---

docs/guides/Navigation-Actions.md

Just fixing some broken links in the docs 🙂

Fixes NavigationActions docs links

---

examples/NavigationPlayground/js/Drawer.js

Code cleanup.
Component Text is unused in Drawer component.
That's typo changes, so testing is not necessary.

Delete unused import component

---

docs/api/navigators/DrawerNavigator.md

styles.tabIcon leads to nowhere, only has styles.icon
The code must pass tests and shouldn't add more Flow errors.
Look around. Match the style of the rest of the codebase.

Minor update

---

docs/api/navigators/StackNavigator.md

Updated StackNavigator.md to match variable names throughout the docs

Variable name consistency in StackNavigator.md

---

jest-setup.js
src/routers/StackRouter.js
src/routers/__tests__/Routers-test.js
src/routers/__tests__/StackRouter-test.js

- Fix #1312 #1041 #937 (Init to Init-UUID)

Fix #1312 #1041 #937

---

src/NavigationActions.js
src/routers/__tests__/StackRouter-test.js
src/routers/__tests__/TabRouter-test.js

- Fixes NavigationActions.js flow typing (we need to use string literals -- flow can't infer these)
- Updates eslint on StackRouter/TabRouter tests
- Use expect.objectContaining so that we don't rely on keys

Fix Flow and Tests

---

.codecov.yml
circle.yml
examples/NavigationPlayground/package.json
examples/NavigationPlayground/yarn.lock
examples/ReduxExample/package.json
examples/ReduxExample/yarn.lock
package.json
yarn.lock

Adds test coverage reporting to PRs, etc using CodeCov.io

Add codecov.io support

---

.codecov.yml
circle.yml
examples/NavigationPlayground/package.json
examples/NavigationPlayground/yarn.lock
examples/ReduxExample/package.json
examples/ReduxExample/yarn.lock
package.json
yarn.lock

We don't need to start up the whole flow server. This makes CI run ever-so-slightly faster.

Run 'flow check' instead of 'flow' in CI

---

.codecov.yml
.eslintignore
.flowconfig
circle.yml
examples/NavigationPlayground/package.json
examples/NavigationPlayground/yarn.lock
examples/ReduxExample/package.json
examples/ReduxExample/yarn.lock
package.json
yarn.lock

Upgrades dependencies/.flowconfig accordingly.
Tests still pass.

Upgrade to React Native 0.44 + Flow 0.42

---

README.md

I think some mention of the channel on Reactiflux might be good as the signal to noise ratio in issues is out of control.

Mention Reactiflux channel in README.md

---

docs/guides/Contributors.md
src/react-navigation.js

For beginners who just want to try out NavigationPlayground, this results in confusing errors messages.

Clarify in docs that npm install in main dir is needed for NavigationPlayground

---

src/views/CardStack.js

fix the wrong movedDistance value, sorry for my foolish mistake made in #1500 , ping @ericvicenti

fix movedDistance

---

docs/api/navigators/StackNavigator.md

Clarifying something in the documentation which I only learned by searching the closed issue queue :)
https://github.com/react-community/react-navigation/issues/1358#issuecomment-298918466

Clarify headerBackTitle usage

---

website/config/env.js

This fixed the website development server. I got the error `__DEV__ is undefined` before.

Fixed website dev bug

---

src/views/Header.js
src/views/HeaderTitle.js

- headerTitle fontSize on Android
- header left TITLE_OFFSET on Android

fix header metrics based on Material design guidelines

---

website/src/App.js

withNavigation is missing from the website's docs but is present in the markdown docs.

Added with navitation to website’s docs

---

docs/api/routers/Routers.md

Adds missing parenthesis to **Handling Custom URIs** code example.

Updates Routers.md - adds missing parenthesis

---

.github/ISSUE_TEMPLATE.md

Add additional guidance information to the GitHub issue template.
- Provides links to best places to ask usage questions.
- Uncomments guiding information in issue template that wasn't visible when creating issue.
- Based on questions asked here: https://new-issue.vuejs.org
If this info is in the GitHub issue template I feel better closing usage related issues 😄 
N/A
N/A

Add additional guidance information to the GitHub issue template.

---

docs/api/navigators/DrawerNavigator.md

[Docs] Fix style variable

---

docs/api/views/Views.md

Fixing broken links on website,https://reactnavigation.org/docs/views/

Fix broken links

---

docs/api/views/Views.md

Updated links for Card.js, CardStack.js and Header.js
Correct documentation is key to any project!

Corrected broken links.

---

docs/guides/Redux-Integration.md

Hi and thanks for this awesome library.
As explained in the documentation, we need to handle ourselves back button press.
I've been searching on many place to achieve that... I finally found a way "up to date".
I think it can be a nice contribution to mark something that explains the things to do in order to successfully apply this behavior. Don't you ?
Best regards

Add helper doc for BackButton on android

---

package.json

> Explain the **motivation** for making this change. What existing problem does the pull request solve?
Because react-native-tab-view insists on sticking at 0.0.*, 
the caret version pinning won't install "minor" updates.
Semver rules are weird with 0. major versions.
Is this something you'd be interested in?
> Prefer **small pull requests**. These are much easier to review and more likely to get merged. Make sure the PR does only one thing, otherwise split it.
> Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.
I'm updating a dependency, so let's see what the CI says.
> Look …

Pin react-native-tab-view with ~ instead of ^

---

docs/api/navigators/DrawerNavigator.md

For https://github.com/react-community/react-navigation/pull/2568

Add documentation for `useNativeAnimations` option in DrawerNavigator

---

src/routers/StackRouter.js

Accidentally updated the main repo instead of a fork. Apologies all.

Reverting last commit

---

src/createNavigationContainer.js
src/routers/TabRouter.js
src/routers/createConfigGetter.js
src/routers/getScreenForRouteName.js
src/routers/validateRouteConfigMap.js
src/routers/validateScreenOptions.js

motivation: see #2258 
I rewrote selected parts of code that used invariant and were resulting in unnecessary evaluations. For the most part, I replaced code that did some json serialization, or concatenating large/ish strings.
I ran the code with my app which has a drawer and several stack. Everything works.

remove ineffective invariant usages, fixes #2258

---

docs/guides/Screen-Navigation-Prop.md

Just a broken link in the docs.

fix broken link to the Navigation Actions guide

---

README.md
website/src/Server.js

Pretty self-explanatory, a lot of open (now mostly closed) issues around performances are basically duplicates of the two main issues; adding a section in the readme should help people out with this hot topic.

Adding a FAQ about performances

---

docs/api/navigators/DrawerNavigator.md
src/views/Drawer/DrawerNavigatorItems.js

I am trying to remove the icon opacity when an item is inactive. Currently, it is not possible so far.
This PR adds the ability to set custom styles inside of the icon container.

Added iconContainerStyle prop to Drawer

---

docs/api/routers/Routers.md

A very minor docs improvement based on https://github.com/react-community/react-navigation/issues/2892

improve wording in router docs

---

README.md

A guide for integrating redux and react-navigation with authentication flow. 
Motivation: The official redux integration documentation is very very brief. There are other tutorials which I personally felt carry unnecessary complexity. Then I couldn't found any tutorial for authentication flow with redux integrated. I have tried to write this article from the ground up.

Added a guide under intermediate concepts.

---

docs/guides/Guide-Headers.md

Spelling/Typos fixes
The code must pass tests and shouldn't add more Flow errors.
Look around. Match the style of the rest of the codebase.

Guide-Headers.md

---

docs/guides/Redux-Integration.md

Fix handling the Hardware Back Button link in Redux section

---

examples/NavigationPlayground/package.json
examples/NavigationPlayground/yarn.lock
examples/ReduxExample/package.json
examples/ReduxExample/yarn.lock

By removing react-addons-test-utils, test should pass without troubles.

Fix CircleCI run

---

docs/guides/Navigation-Actions.md

**Motivation**
Sectional link to Reset section fails due to case difference.
**Test plan**
As this is a view change on the doc, test plan does not apply.

Fix the section link for Reset action

---

src/views/Header/Header.js

**Motivation**
On Android the ripple animation on the header's default back button is not as smooth as it could be. This is obvious in Dev mode where the animation proceeds very slowly and only upon completion does the action occur. Wrapping the `onPress` function in `InteractionManager` allows the animation to be as performant as possible.
**Test plan**
It's a simple enough PR. Not sure much testing is required here. I tested this with a complex app on a physical Android device and on iOS via Expo Snack. No problems.

HeaderBackButton animation performance

---

.circleci/config.yml
package.json

Remove website deploy from CI and clean up scripts

---

examples/NavigationPlayground/js/ModalStack.js

Navigation structure not correct is seems to be . fixed #3156  
Test plan (required)
Works on  iOS  (Issue exist in iOS in the first place)

navigation back fix in example

---

examples/NavigationPlayground/rn-cli.config.js
examples/ReduxExample/rn-cli.config.js
examples/SafeAreaExample/rn-cli.config.js

Fixes rn-cli.config.js for RN 0.52

metro-bundler -> metro

---

src/__tests__/getChildEventSubscriber-test.js
src/getChildEventSubscriber.js

Fixes tabs bug mentioned by @noxee in #3345
Also adds a test for the event subscription implementation

Fix tab events and test event nested event subscriptions

---

src/NavigationActions.js
src/addNavigationHelpers.js
src/navigators/__tests__/__snapshots__/StackNavigator-test.js.snap
src/routers/StackRouter.js
src/routers/__tests__/TabRouter-test.js
src/views/__tests__/__snapshots__/TabView-test.js.snap

New 'pop' action type for StackRouter with 'n' and 'immediate' options

StackRouter PopN Action

---

src/views/SafeAreaView.js

Look around. Match the style of the rest of the codebase.

remove unuseful SafeAreaView component

---

src/createNavigationContainer.js

Straightforward fix to #3446
Dumb mistake from the initial implementation: we had not been firing the initial event at all!

Fix focus event for initial screen

---

examples/NavigationPlayground/js/SimpleStack.js
src/routers/StackRouter.js
src/routers/__tests__/StackRouter-test.js

Same as https://github.com/react-navigation/react-navigation/pull/3453. Also cleaned up the tests from that PR a bit here.
Run tests, try playground.

Prevent push from bubbling up

---

src/navigators/__tests__/__snapshots__/StackNavigator-test.js.snap
src/routers/StackRouter.js
src/routers/__tests__/Routers-test.js
src/routers/__tests__/StackRouter-test.js

This problem was found and fixed by @matthargett and @jayphelps in #3397. I’m just rebasing and cleaning a few things up
Also shoutout to @muramasa who wrote the test to diagnose this

Fix StackRouter initial navigate child router behavior and key consistency

---

examples/NavigationPlayground/js/App.js
examples/NavigationPlayground/js/StacksWithKeys.js
src/routers/StackRouter.js
src/routers/__tests__/StackRouter-test.js

Fixes https://github.com/react-navigation/react-navigation/issues/3477
- Run tests (added one)
- Try the example in NavigationPlayground

Get rid of unused routes when navigating back with key

---

examples/NavigationPlayground/js/App.js
examples/NavigationPlayground/js/StacksWithKeys.js

Make the playground app more pleasant
Let CI run. Try the app on https://expo.io/@react-navigation/NavigationPlayground

Make it possible to go back to menu from key example and improve banner on menu screen

---

src/__tests__/addNavigationHelpers-test.js
src/addNavigationHelpers.js
src/navigators/__tests__/__snapshots__/StackNavigator-test.js.snap
src/views/__tests__/__snapshots__/TabView-test.js.snap

Reverts react-navigation/react-navigation#3510
Should have waited for RFC first: https://github.com/react-navigation/rfcs/pull/21

Revert "Add getParam navigation helper"

---

src/routers/StackRouter.js
src/routers/__tests__/StackRouter-test.js

- Make StackRouter a bit easier to read, update and add some comments
- Add an explicit test around stack and navigate
I was experimenting with the code and improving my understanding of it. Made a few changes here in the process so hopefully it's a bit easier for the next person to understand.
Run the tests. This should not have any impact on functionality.

Cleanup around StackRouter

---

package.json

Bump react-native-safe-area-view dep to 0.7.0 

---

.circleci/config.yml
src/navigators/__tests__/__snapshots__/StackNavigator-test.js.snap

First crack at publish from circle

---

README.md

Fix RFC link

---

src/views/CardStack/CardStack.js

Currently the gesture release animation curve is pretty weird - it feels very slow and not as "alive" as the iOS one. The reason is that it uses a simple timing animation. This changes it to use the 'new' spring animation type when its available. I looked at animations frame-by-frame before and after and it's not perfect with this config but it's pretty close. It would be nice if someone who cares deeply about getting it perfect (if such a person exists) could dig in more to tweak the parameters to be "just right". 
Try the playground app on iOS.

Use a closer-to-correct spring animation when releasing a gesture in CardStack

---

src/views/Drawer/DrawerSidebar.js
src/views/Drawer/DrawerView.js

Fix issues with tabs in drawer example
cc @brentvatne

Fix issue in drawer actions

---

src/navigators/createStackNavigator.js

Cherrypicking PR #3701 to `master`

Pass initialRouteKey into StackRouter (#3540)

---

src/views/Header/Header.js
src/views/StackView/StackViewLayout.js

I just replaced some inline styles with styles created by StyleSheet.create().

replace inline styles by StyleSheet

---

examples/NavigationPlayground/README.md

fix contribution docs link

---

src/views/CardStack/CardStack.js

fix for https://github.com/react-navigation/react-navigation/issues/3729 , https://github.com/react-navigation/react-navigation/issues/3746

fix for withNavigationFocus

---

src/views/Drawer/DrawerSidebar.js
src/views/TabView/TabView.js

this PR is to refactor removing unuseful SafeAreaView.

Remove unuseful SafeAreaView

---

examples/NavigationPlayground/yarn.lock
examples/ReduxExample/src/navigators/AppNavigator.js
src/NavigationActions.js
src/__tests__/NavigationActions-test.js
src/createNavigationContainer.js
src/navigators/createNavigator.js
src/react-navigation.js
src/react-navigation.web.js
src/routers/DrawerActions.js
src/routers/DrawerRouter.js
src/routers/StackActions.js
src/routers/StackRouter.js
src/routers/SwitchRouter.js
src/routers/__tests__/DrawerRouter-test.js
src/routers/__tests__/Routers-test.js
src/routers/__tests__/StackRouter-test.js
src/routers/__tests__/TabRouter-test.js
src/routers/getNavigationActionCreators.js
src/views/Drawer/DrawerView.js
src/views/StackView/StackView.js
src/views/StackView/StackViewLayout.js

Introduce the concept of navigator-specific actions
WIP implementation of the action creators proposed API here: https://github.com/react-navigation/rfcs/pull/18

Action creators overhaul

---

src/routers/StackRouter.js
src/routers/SwitchRouter.js

getCustomActionCreators API support for all routers.
Still needs a test though

getCustomActionCreators API

---

flow/react-navigation.js

add defintion for `isFocused` helper from #3651

[flow] add isFocused helper definition

---

src/routers/DrawerRouter.js
src/routers/__tests__/DrawerRouter-test.js

Addresses feedback from https://github.com/react-navigation/react-navigation/issues/3924

Drawer actions accept targeting key

---

src/createNavigationContainer.js

Fixes https://github.com/react-navigation/react-navigation/issues/4097
TODO: need to come back and do this.

Container state can be out of date if we have async functions between getting and using it

---

src/routers/DrawerRouter.js
src/routers/__tests__/DrawerRouter-test.js

Fixes to drawer router handling of child routers
Addresses #4129, and also lets child routers swallow actions with null. Tests added

Fixes to drawer router handling of child routers

---

src/createNavigationContainer.js

Previously we had been emiting an action event with a null state when the router handles the action by returning null from getStateForAction.
- Fixes the case of null state getting emitted
- Renames a few things for clarity
- Refactors conditionals to read easier
- Comments to explain intent

Fix dispatch implementation

---

src/react-navigation.js

Hello,
These two were missing. They are needed in order to create a custom navigator based on the existing Drawer. (off-canvas sidebar 😃)

Export missing Drawer components

---

src/views/Drawer/DrawerView.js

Without maintaining this state, an infinite loop happens when rapidly opening and closing the drawer. Better fix would be inside the drawer component itself, but... ¯\_(ツ)_/¯

Fix race condition in DrawerView

---

src/routers/__tests__/StackRouter-test.js

Hello! I've seen that there were a small test missing and I took the opportunity to do a first contribution to this repo. See https://github.com/react-navigation/react-navigation/pull/2982#issuecomment-392223790

Add missing tests about DeepLinking 

---

src/navigators/__tests__/NestedNavigator-test.js
src/navigators/__tests__/__snapshots__/NestedNavigator-test.js.snap
src/navigators/createNavigator.js

rebase of https://github.com/react-navigation/react-navigation/pull/3823

throw readable error when wrong navigation prop is passed

---

src/__tests__/getNavigation-test.js
src/createNavigationContainer.js
src/getChildNavigation.js
src/getChildRouter.js
src/getNavigation.js
src/navigators/createNavigator.js
src/routers/StackRouter.js
src/routers/SwitchRouter.js

Re-doing #4425 without isFocused bug on child navigation

Refactor redo, child navigation to navigation prop

---

src/__tests__/__snapshots__/NavigationContainer-test.js.snap
src/utils/docsUrl.js

fix broken link to Common mistakes

fix broken link to Common mistakes

---

flow/react-navigation.js

Unrelated change in here: typing `tabBarOnPress`'s `defaultHandler`. Wasn't sure if I should make a separate PR for a single unrelated line, let me know if you'd prefer that going forward.

[flow] Type getNavigation

---

.github/PULL_REQUEST_TEMPLATE.md

Also link to the "Unreleased" section in CHANGELOG.

Fix typo in Pull Request Template

---

package.json
src/__tests__/NavigationContainer-test.js
src/__tests__/__snapshots__/NavigationContainer-test.js.snap
src/navigators/__tests__/NestedNavigator-test.js
src/navigators/__tests__/StackNavigator-test.js
src/navigators/__tests__/SwitchNavigator-test.js
src/navigators/createContainedStackNavigator.js
src/navigators/createContainedSwitchNavigator.js
src/navigators/createStackNavigator.js
src/navigators/createSwitchNavigator.js
src/react-navigation.js
src/routers/validateRouteConfigMap.js
src/utils/invariant.js
src/utils/shallowEqual.js
src/views/NavigationConsumer.js
src/views/NavigationContext.js
src/views/NavigationProvider.js
src/views/SceneView.js
src/views/StackView/StackView.js
src/views/StackView/StackViewLayout.js
src/views/StackView/StackViewTransitionConfigs.js

This cleanup is necessary for the universe hacks. It makes core modules more 'importable' to the other repo where I'm working on full-stack navigation

@ericvicenti/universe

---

CHANGELOG.md

Bug fixes should be listed in the "Fixed" section instead of "Changed" according to [keepachangelog](https://keepachangelog.com/en/1.0.0/#how).

Improve changelog format

---

src/react-navigation.web.js

Adds the SwitchNavigator for web since it does not have a view, it is portable.

Adds SwitchNavigator to react-navigation-web

---

src/react-navigation.web.js

getNavigation is a core export. Hard to make web work without it.

Adds getNavigation to web exports

---

CHANGELOG.md

Issue link was missing in removed entry. Left the one with better format.
Check that link is working.
N/A
N/A

Changelog: Remove duplicate entry

---

examples/NavigationPlayground/js/App.js
examples/NavigationPlayground/js/CustomTabUI.js

This example shows how custom navigators can be made from existing navigators, and additional UI can be presented.
The new custom tabs ui example demonstrates this by showing a checkout button under a tabs navigation, depending on the current active screen

Custom Tabs UI Example

---

src/__tests__/NavigationContainer-test.js
src/navigators/__tests__/SwitchNavigator-test.js
src/navigators/__tests__/TabNavigator-test.js
src/navigators/createNavigator.js
src/navigators/createSwitchNavigator.js
src/routers/__tests__/PathHandling-test.js
src/routers/__tests__/StackRouter-test.js
src/routers/__tests__/TabRouter-test.js
src/routers/createConfigGetter.js
src/views/AnimatedValueSubscription.js
src/views/NavigationContext.js
src/views/ResourceSavingSceneView.js
src/views/__tests__/NavigationEvents-test.js
src/views/withNavigation.js
src/views/withNavigationFocus.js

While reading through the code of this library, I found some unused imports and variable declarations. This PR removes them.
Run unit tests
Look around. Match the style of the rest of the codebase. Run `yarn format` before committing.
No need for an entry, it's just a quick technical debt ^^

Removed unused imports and const declarations

---

examples/NavigationPlayground/js/StacksOverTabs.js
examples/NavigationPlayground/yarn.lock
src/react-navigation.js
src/utils/getActiveChildNavigationOptions.js

This is a utility to allow navigationOptions definition functions to access the navigation options of the active child route, which allows people to replicate the v1 behavior of deep nav configuration.

Introduce getActiveChildNavigationOptions

---

src/routers/StackRouter.js

This will resolve this issue
https://github.com/react-navigation/react-navigation/issues/5062

Fix unexpected route switching after the transition is complete

---

examples/NavigationPlayground/js/App.js

Just a minor typo I found while browsing through recent changes! @brentvatne

Fix typo in MainScreen

---

flow/react-navigation.js

This corresponds to three `flow-typed` PRs:
1. [Get rid of deprecated Navigator exports in 3.0](https://github.com/flow-typed/flow-typed/pull/3140)
2. [Refine AnimatedValue type](https://github.com/flow-typed/flow-typed/pull/3147)
3. [Introduce SafeAreaViewInsets type](https://github.com/flow-typed/flow-typed/pull/3148)

[flow] Update Flow libdef with Feb 2019 changes

---

examples/NavigationPlayground/js/CustomTransitioner.js

when i was looking for reference on how to make custom transitioner, i saw this example code and found some unused import and unused destructure on `_renderScene` method (line of code 64).

remove unused import and unused destructure on CustomTransitioner.js

---

typescript/react-navigation.d.ts

Fix this:
Let me know if I need to change the `interface` this is being added to.

Add resetOnBlur type

---

flow/react-navigation.js

Try to solve the issue - https://github.com/react-navigation/react-navigation/issues/6002#issuecomment-502908696

flow cover for getActiveChildNavigationOptions

---

packages/bottom-tabs/src/types.tsx

docs: Update types.tsx

---

example/src/index.tsx
packages/stack/src/views/Stack/CardStack.tsx

This will avoid issues such as #6909

refactor: enable screens only for last screen

---

packages/stack/src/TransitionConfigs/CardStyleInterpolators.tsx

before: 
https://streamable.com/91dpf
after:
https://streamable.com/mltad

feat: enhance border radius in modals on new iPhones

---

example/src/Screens/SimpleStack.tsx

Three of the pages didn't scroll on web. This fixes those.

chore: fix scrolling in web examples

---

packages/core/src/__tests__/getStateFromPath.test.tsx
packages/core/src/getStateFromPath.tsx

Added availability of positioning params in any part of the pattern for a config.

feat: support params anywhere in path segement

---

packages/core/src/__tests__/getStateFromPath.test.tsx
packages/core/src/getPathFromState.tsx
packages/core/src/getStateFromPath.tsx

Added parsing of optional params based on the regex by @satya164.

feat: add support for optional params to linking

---

package.json

chore: fix repo url in readme

---

packages/core/src/BaseNavigationContainer.tsx
packages/core/src/__tests__/index.test.tsx
packages/core/src/types.tsx

I'll add docs when we'll add getCurrentOptions

feat: add getCurrentRoute

---

packages/core/src/BaseNavigationContainer.tsx
packages/core/src/NavigationStateContext.tsx
packages/core/src/SceneView.tsx
packages/core/src/__tests__/BaseNavigationContainer.test.tsx
packages/core/src/useNavigationBuilder.tsx
packages/core/src/useOptionsGetters.tsx

refactor: extract NavigationStateContext

---

packages/core/src/useIsFocused.tsx

React does not care https://github.com/facebook/react/pull/15022/files#diff-8cc42de7446ab6821804017349b5a8b1R74

refactor: remove useless callback arg in useSubscription

---

example/src/index.tsx
packages/core/src/__tests__/getPathFromState.test.tsx
packages/core/src/__tests__/getStateFromPath.test.tsx
packages/core/src/getPathFromState.tsx
packages/core/src/getStateFromPath.tsx

fix: make sure the wildcard pattern catches nested unmatched routes

---

packages/stack/src/views/KeyboardManager.tsx

currentlyFocusedField => currentlyFocusedInput

fix: don't use deprecated currentlyFocusedField

---

packages/drawer/README.md

Removed reference to a tab navigator.

docs: updated description for drawer

---

.github/workflows/triage.yml

Added a github action for submitting issues regarding libraries used in React Navigation.

feat: add action for screens library

---

packages/core/src/routers/__tests__/KeyGenerator.test.js

I think this is pretty self-descriptive!
Let me know if I can improve anything else :)

test: add KeyGenerator tests

---

packages/core/src/navigators/createNavigator.js

Little improvement for a more meaningful variable name :)

refactor: rename reduce accumulator variable

---

packages/core/src/__tests__/getNavigation.test.js

Found this skipped test and it just needed a little refactor!

test: fix and enable skipped test

---

packages/stack/src/types.tsx

gestureResponseDistance vertical and horizontal documentations were swapped

docs: fix comments for gestureResponseDistance

---

packages/stack/src/TransitionConfigs/CardStyleInterpolators.tsx
packages/stack/src/TransitionConfigs/TransitionPresets.tsx
packages/stack/src/views/Stack/Card.tsx

fix: set needsOffscreenAlphaCompositing and update default android animation

---

packages/stack/src/views/Header/HeaderContainer.tsx

Motivation
--
Previously when using `headerMode="float"` with headerTransparent set to true, we cant press header buttons in Android. This PR fixes this. (resolves #8731 )
Been doing some debugging and found out that this is caused by `HeaderContainer` being set as `absolute`. Initially it didn't have width & height in Android when it's set to default, that's why we can't access the children.
So, the solution in this PR is to define the height by using headerHeight. But, since we can't access headerHeight from header, Im using local state for keeping up with the headerHeight. Or should I move the HeaderHeight provider out of StackContainer? I'm not sure, since I think it was intended to be kept inside the StackContainer
Test Plan
--
With this config, now the header button can be clicked. …

fix: fix header buttons not pressable when headerTransparent=true & headerMode=float

---

packages/drawer/src/types.tsx
packages/drawer/src/views/DrawerView.tsx
packages/drawer/src/views/ResourceSavingScene.tsx
packages/tabs/src/navigators/createBottomTabNavigator.tsx
packages/tabs/src/types.tsx
packages/tabs/src/views/ResourceSavingScene.tsx

Added optional screens enabling for v4 bottom-tabs and drawer navigators.

feat: add detachInactiveScreens prop for bottom tabs and drawer

---

packages/core/src/__tests__/getChildrenNavigationCache.test.js

I decided to contribute back some tests cases we had for getChildrenNavigationCache :)

test: add tests for getChildrenNavigationCache

---

packages/drawer/src/views/ResourceSavingScene.tsx
packages/tabs/src/views/ResourceSavingScene.tsx

Added `activityState` to other navigators in 4.x

feat: add activityState to other navigators

---

packages/material-bottom-tabs/src/views/MaterialBottomTabView.tsx

Fixes the `lint` script which is failing CI

chore: format MaterialBottomTabView.tsx

---

packages/react-navigation/typescript/react-navigation.d.ts

```
export interface NavigationRouter<State = NavigationState, Options = {}> {
```

Fix NavigationNavigator type error

---

packages/native-stack/LICENSE
packages/native-stack/README.md
packages/native-stack/package.json
packages/native-stack/src/__tests__/index.test.tsx
packages/native-stack/src/index.tsx
packages/native-stack/src/navigators/createNativeStackNavigator.tsx
packages/native-stack/src/types.tsx
packages/native-stack/src/views/FontProcessor.tsx
packages/native-stack/src/views/HeaderConfig.tsx
packages/native-stack/src/views/NativeStackView.tsx
packages/native-stack/tsconfig.build.json
packages/native-stack/tsconfig.json
yarn.lock

Added `native-stack` package to the repo.

feat: add native-stack to repo

---

packages/core/src/useNavigationBuilder.tsx

Problem:
When using nested navigators, unmounts cause race cleanup races.
Imagine following hierarchy (from tree root downwards, parent to children):
TabNavigator (1) [renders useNavigationBuilder]
SceneView (from TabNavigator)
StackNavigators (N) [each renders useNavigationBuilder] 
SceneView (from StackNavigator)
Now lets test following flow:
1. Mount above navigators with given navigation params (e.g. navigation for unauthenticated users) 
2. Unmount all navigators (e.g. during login process)
3. Mount above navigation with different navigation params than in 1) (e.g. navigation for authenticated users)
What you'll observe, there will be old navigation params preserved in 3) coming from 1).
Source of problem:
BaseNavigationContainer holds global navigation state, exposes API to modify …

fix: prevent navigation state updates after state cleanup

---

packages/elements/src/Header/getDefaultHeaderHeight.tsx
packages/elements/src/Screen.tsx
packages/native-stack/src/views/NativeStackView.native.tsx
packages/stack/src/views/Stack/CardContainer.tsx

Added default header height in native-stack.

feat: expose header height in native-stack

---

packages/flipper-plugin-react-navigation/README.md
packages/flipper-plugin-react-navigation/package.json
packages/flipper-plugin-react-navigation/src/Logs.tsx
yarn.lock

fix: flipper error 

---

packages/native/src/useLinking.tsx

fix: fix navigation when going back and forth in history on web

---

packages/drawer/src/utils/useDrawerStatus.tsx

useDrawerStatus typings for #10066

---

packages/bottom-tabs/src/views/Badge.tsx

Remove unnecessary condition for boolean value.
Reorder if else condition for little improve.
Moved props with default value at the end.

fix: remove unnecessary conditions in the Badge component 

---

packages/drawer/src/views/modern/Drawer.tsx

**Motivation**
Fixes #10337. The modern drawer implementation is leaking `InteractionManager` interaction handles. This causes other code that relies on [runAfterInteractions](https://reactnative.dev/docs/interactionmanager#runafterinteractions) to not run.
Currently, the interaction handle is created `onStart` of `useAnimatedGestureHandler` and only cleared `onEnd`. However, `onEnd` is not guaranteed to be called based on the [state flows](https://docs.swmansion.com/react-native-gesture-handler/docs/under-the-hood/states-events#state-flows). The gesture may enter a failed or cancelled state instead of ended, …

fix(drawer): fix drawer clearing interaction handle

---

packages/bottom-tabs/src/index.tsx

**Motivation**
Custom TabBarView required this to provide the correct height.
```tsx
import { useCallback, useContext } from 'react';
import {
createBottomTabNavigator,
BottomTabBarHeightCallbackContext, // this is required.
} from '@react-navigation/bottom-tabs';
const Tab = createBottomTabNavigator();
const BottomTabBar = () => {
const reportHeight = useContext(BottomTabBarHeightCallbackContext);
const handleLayout = useCallback(e => reportHeight(e.nativeEvent.layout.height), [reportHeight]);
return (
<View onLayout={handleLayout}>
{/* ... */}
</View>
);
};
const App = (
<Tab.Navigator tabBar={BottomTabBar}>
{/* ... */}
</Tab.Navigator>
);
```

export BottomTabBarHeightCallbackContext

---

example/src/index.tsx
packages/drawer/src/views/DrawerContentScrollView.tsx
packages/drawer/src/views/DrawerView.tsx
packages/drawer/src/views/legacy/Drawer.tsx
packages/drawer/src/views/modern/Drawer.tsx
packages/elements/src/Header/HeaderBackButton.tsx
packages/native-stack/src/views/HeaderConfig.tsx
packages/stack/src/TransitionConfigs/HeaderStyleInterpolators.tsx
packages/stack/src/utils/getInvertedMultiplier.tsx

react-native-web removed I18nManager.isRTL , we should migrate to use getConstants

fix: replaced I18nManager.isRTL with 18nManager.getConstants().isRTL

---

packages/stack/src/views/Stack/CardStack.tsx

This PR tries to solve the problem of a background that can be seen between animated screens. The problem seems to lie in unmounting screens too early during the transition.
This PR reverts the `EPSILON` to its initial value. This value decides at which point of the scene progress the screen is detached.
The value was orginally introduced [here](https://github.com/react-navigation/react-navigation/commit/282f62c2584413b96c21f34b8759999494cec60a) and then changed from `1e-5` to `0.01` [here](https://github.com/cntral/react-navigation/commit/3e405b9c61a5852a93f36153933c4d89e6b84344).
Fix originally uncovered in https://github.com/software-mansion/react-native-screens/issues/1285#issuecomment-1026928610 
I'm not certain whether this eliminates the problem fully but it does make it less …

fix: fix previous screen detach too early

---

packages/native-stack/src/views/NativeStackView.native.tsx

Test plan:
Tested by rendering a dummy `View` for the header:
```js
options={{
header: () => (
<View
style={{
backgroundColor: 'rgba(0, 0, 0, 0.5)',
height: 56,
}}
/>
),
headerTransparent: true,
}}
```
Fixes #10822
Closes #10902

fix: fix headerTransparent with custom header in native-stack

---

packages/native-stack/src/types.tsx

Corrected Type definition for headerBackVisible, corresponding with the documentation.
**Motivation**
**Test plan**
Fixes https://github.com/react-navigation/react-navigation/issues/11221

fix: fix headerBackVisible type annotation

---

packages/drawer/src/views/DrawerView.tsx
packages/native/src/useBackButton.web.tsx

**Motivation**
- fix https://github.com/react-navigation/react-navigation/issues/11316
**Test plan**
- ¯\_(ツ)_/¯

fix: prevent back handler usage on web

---

example/package.json
example/src/Screens/BottomTabs.tsx
example/src/Screens/NativeStackHeaderCustomization.tsx
example/src/Screens/Static.tsx
example/src/Screens/TabView/TabBarIcon.tsx
example/src/index.tsx
packages/bottom-tabs/package.json
packages/bottom-tabs/src/types.tsx
packages/bottom-tabs/src/views/BottomTabItem.tsx
packages/bottom-tabs/src/views/TabBarIcon.tsx
packages/drawer/package.json
packages/drawer/src/types.tsx
packages/drawer/src/views/DrawerItem.tsx
packages/elements/src/Header/HeaderTitle.tsx
packages/elements/src/MissingIcon.tsx
packages/elements/src/types.tsx
packages/material-top-tabs/src/types.tsx
packages/native-stack/package.json
packages/native-stack/src/types.tsx
packages/native/src/types.tsx
packages/react-native-tab-view/src/TabBar.tsx
packages/react-native-tab-view/src/TabBarItem.tsx
packages/react-native-tab-view/src/TabBarItemLabel.tsx
packages/stack/package.json
yarn.lock

Reverts react-navigation/react-navigation#11570

Revert "fix: Allow to use `PlatformColor` in the theme"

---

example/src/Screens/TabView/AutoWidthTabBar.tsx
example/src/Screens/TabView/Coverflow.tsx
example/src/Screens/TabView/CustomIndicator.tsx
example/src/Screens/TabView/CustomTabBar.tsx
example/src/Screens/TabView/ScrollableTabBar.tsx
example/src/Screens/TabView/TabBarIcon.tsx
packages/material-top-tabs/src/views/MaterialTopTabBar.tsx
packages/material-top-tabs/src/views/MaterialTopTabView.tsx
packages/react-native-tab-view/src/PanResponderAdapter.tsx
packages/react-native-tab-view/src/TabBar.tsx
packages/react-native-tab-view/src/TabBarIndicator.tsx
packages/react-native-tab-view/src/TabView.tsx

**Motivation**
Goal of this PR is to add direction prop to unify usage of RTL layouts across packages.
**Test plan**
Turn ON / OFF RTL in example app.

feat: add direction prop to TabView

---

packages/core/src/__tests__/useNavigationCache.test.tsx
packages/core/src/useDescriptors.tsx
packages/core/src/useNavigationBuilder.tsx
packages/core/src/useNavigationCache.tsx

feat: add a new 'create' method to create placeholder descriptor

---

packages/core/src/__tests__/useNavigationCache.test.tsx
packages/core/src/useDescriptors.tsx
packages/core/src/useNavigationBuilder.tsx
packages/core/src/useNavigationCache.tsx

feat: add a new 'describe' method to create placeholder descriptor

---

packages/stack/src/views/Stack/Card.tsx

Fix post #11733 
**Motivation**
**Test plan**

fix: remove unnecessary check in the stack navigator

---

packages/material-top-tabs/src/views/MaterialTopTabView.tsx

feat: enable preloading at material-top-tabs

---

packages/material-top-tabs/src/views/MaterialTopTabView.tsx

This reverts commit 58691ac973b40a93f4433dba0639dc3f45b21250.
**Motivation**
**Test plan**

Revert "feat: enable preloading at material-top-tabs (#11755)"

---

packages/material-top-tabs/src/views/MaterialTopTabView.tsx

fix: broken condition in the preloading of material tabs

---

packages/routers/src/StackRouter.tsx

fix: follow-up for the retain-related changes in stack router

---

packages/stack/src/views/Stack/CardContainer.tsx

fix: remove optional check in CardContainer

---

example/src/Screens/NativeStackPreventRemove.tsx
packages/core/src/__tests__/usePreventRemove.test.tsx
packages/core/src/index.tsx
packages/core/src/usePreventRemove.tsx

chore: mark usePreventRemove as stable

---

packages/elements/src/Header/getDefaultHeaderHeight.tsx
packages/native-stack/src/views/NativeStackView.native.tsx

This PR addresses the issue https://github.com/react-navigation/react-navigation/issues/11655

fix: status bar height for iOS devices with dynamic island

---

example/src/index.tsx
packages/devtools/src/index.tsx
packages/devtools/src/useLogger.tsx

https://github.com/user-attachments/assets/c4ea694c-b04e-4954-9c6f-774fd0341f6a

feat: add a logger devtool

---

packages/core/src/SceneView.tsx
packages/core/src/__tests__/index.test.tsx

fix: fix navigator trying to handle params with screens or state again

---

packages/elements/src/Header/Header.tsx
packages/elements/src/types.tsx

As the package already had `onClose`, I thought it would be useful to also have an `onOpen` hook.

feat: add onOpen handler
